### ISSUE TITLE
Create container for aspnet latest dev version

### ISSUE THREAD

**Issue by giggio** [aspnet/aspnet-docker#10]
Right now dev is beta2-10698 [![dev version](http://img.shields.io/myget/aspnetvnext/v/KRE-CLR-x86.svg?style=flat)](https://www.myget.org/gallery/aspnetvnext) and master is 1.0.0-beta1 [![master version](http://img.shields.io/myget/aspnetmaster/v/KRE-CLR-x86.svg?style=flat)](https://www.myget.org/gallery/aspnetmaster).
We don't get a dev version, only a master. We should always have the option to run the latest dev version, which would pull the latest automatically (no need to update the docker file all the time).

**Comment by ahmetalpbalkan** [comment]
This is completed via #20, please close.

**Comment by giggio** [comment]
Cool!
