### ISSUE TITLE
Beta 8 tag for Mono based image is missing

### ISSUE THREAD

**Issue by yousifh** [aspnet/aspnet-docker#102]
Building a Docker image with ```FROM microsoft/aspnet:1.0.0-beta8``` is causing Docker to complain about not finding the image. Running it with ```FROM microsoft/aspnet:latest``` is able to grab the image with beta8 mono runtime. 

Looking here (https://hub.docker.com/r/microsoft/aspnet/tags/) it seems that it's just an issue of having to add the 1.0.0-beta8 tag. 

You can test this on the sample apps provided in the Home repo and trying to build Docker images for them.

**Comment by ahmetalpbalkan** [comment]
You're right, looks like we forgot to update Docker Hub. I'm fixing this now.

@glennc Please don't forget to update Docker Hub automated build settings next time you publish a new version. Full checklist is at `MAINTENANCE.md` to avoid errors.

**Comment by ahmetalpbalkan** [comment]
Umm no I was wrong, apparently the build machine building the beta8 tag crashed (“logs uncoverable” error here: https://hub.docker.com/r/microsoft/aspnet/builds/bsk6mmq3xegztccdtwve4wj/) Apparently build of `beta4` also crashed in the last run.

I am triggering a rebuild now, but we should've checked if all tags built fine.

**Comment by ahmetalpbalkan** [comment]
Fixed now.

**Comment by glennc** [comment]
So I didn't miss anything?

**Comment by ahmetalpbalkan** [comment]
Nope, although we should update the checklist and add "make sure everything builds fine after Docker Hub build trigger occurs". If build of one tag fails, if it is a new tag (like this case) it does not get added, if it is an existing tag then the new build does not replace the old one and these errors are silently discarded in our case...

**Comment by glennc** [comment]
Sounds like a good idea.
