### ISSUE TITLE
"dnu" executable file not found in $PATH

### ISSUE THREAD

**Issue by gencebay** [aspnet/aspnet-docker#104]
I'm trying to build a new container from [my docker hub](https://hub.docker.com/r/gencebay/vnextubuntu/)  repository with this [dockerfile](https://github.com/gencebay/vNextSampleApp/blob/4b443e567a06af237b4e9b6a2011d7128206fe51/src/Dockerfile)

But when it start to build getting the system error below:
>**exec: "dnu": executable file not found in $PATH**

so when I look at the container $PATH output, it seems normal and dnx, dnvm and dnu are already added to path properly! where I am wrong?
sound may have something to do with docker entrypoint or /bin/sh ?

**Comment by ahmetalpbalkan** [comment]
What is in FROM gencebay/vnextubuntu image? Can you please a full dockerfile deriving from microsoft/aspnet? I am trying to understand what version you are running. 

Also your image can be old, please consider directly building on top of microsoft/aspnet instead of the indirection.

**Comment by gencebay** [comment]
It (vnextubuntu) was created to learn comprehensively and educational. Have installed DNX (Microsoft .NET Execution environment CoreClr-x64-1.0.0-beta8-15858) and DNVM (Microsoft .NET Development Utility CoreClr-x64-1.0.0-beta8-15858). 

When I execute 
>docker run gencebay/vnextubuntu dnu
![screen shot 2015-10-30 at 10 24 17 pm](https://cloud.githubusercontent.com/assets/879469/10855880/c33e40d8-7f4c-11e5-8692-937806371142.png)

it returns the same error but when I logged as 

>docker run -t -i gencebay/vnextubuntu /bin/bash

with interactive window connection:
>root@containerId:/# dnu

working expected!
![screen shot 2015-10-30 at 10 21 50 pm](https://cloud.githubusercontent.com/assets/879469/10855808/66db998a-7f4c-11e5-8ee7-f58a62bb8ccb.png)

consequently we will migrate to [microsoft/aspnet](https://hub.docker.com/r/microsoft/aspnet/) base container If we do not overcome this situation.

**Comment by ahmetalpbalkan** [comment]
@gencebay I think it's happening because your entrypoint is:

    ENTRYPOINT ["dnx", "-p", "project.json", "kestrel"]

and when you say `docker run image dnu` I believe it actually will run:

    dnx -p project.json kestrel dnu

command. Can you try changing ENTRYPOINT to CMD in your dockerfile and try again?

**Comment by muratg** [comment]
@gencebay Please reopen if this is still an issue for you after following @ahmetalpbalkan's suggestion. Closing for now.
