### ISSUE TITLE
ASP.NET docker image exposed ports are closed

### ISSUE THREAD

**Issue by sulhome** [aspnet/aspnet-docker#105]
I have added EXPOSE to the [ASPNET Dockerfile][1] and build an image from it however the port exposed in the docker file is always closed? do I need to download a specific package to allow ports to open on this image.

**Dockerfile**

    FROM debian:jessie
    
    ENV DNX_VERSION 1.0.0-beta8
    ENV DNX_USER_HOME /opt/dnx
    
    RUN apt-get -qq update && apt-get -qqy install unzip curl libicu-dev libunwind8 gettext libssl-dev libcurl3-gnutls zlib1g && rm -rf /var/lib/apt/lists/*
    
    RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
    RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
    	&& dnvm install $DNX_VERSION -alias default -r coreclr \
    	&& dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"
    
    # Install libuv for Kestrel from source code (binary is not in wheezy and one in jessie is still too old)
    # Combining this with the uninstall and purge will save us the space of the build tools in the image
    RUN LIBUV_VERSION=1.4.2 \
    	&& apt-get -qq update \
    	&& apt-get -qqy install autoconf automake build-essential libtool \
    	&& curl -sSL https://github.com/libuv/libuv/archive/v${LIBUV_VERSION}.tar.gz | tar zxfv - -C /usr/local/src \
    	&& cd /usr/local/src/libuv-$LIBUV_VERSION \
    	&& sh autogen.sh && ./configure && make && make install \
    	&& rm -rf /usr/local/src/libuv-$LIBUV_VERSION \
    	&& ldconfig \
    	&& apt-get -y purge autoconf automake build-essential libtool \
    	&& apt-get -y autoremove \
    	&& apt-get -y clean \
    	&& rm -rf /var/lib/apt/lists/*
    
    EXPOSE 5003
    
    ENV PATH $PATH:$DNX_USER_HOME/runtimes/default/bin

**Please note** that other images exposing ports like mongodb and nginx are working fine and their exposed ports are open. It is only this image that I am struggling with

**docker inspect output**

    [
    {
        "Id": "46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a",
        "Created": "2015-11-09T10:59:21.613690009Z",
        "Path": "/bin/bash",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 21337,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2015-11-09T10:59:21.800924128Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "2e1b81c113a2a2ba84935be470f9b02ee22f23649136d4408f0340f385e67fc1",
        "ResolvConfPath": "/var/lib/docker/containers/46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a/hostname",
        "HostsPath": "/var/lib/docker/containers/46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a/hosts",
        "LogPath": "/var/lib/docker/containers/46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a/46865fae677bc52a8d7affbd53d8ed3da941fd2d8276514dcbcdebfc3b5d666a-json.log",
        "Name": "/aspnet",
        "RestartCount": 0,
        "Driver": "aufs",
        "ExecDriver": "native-0.2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "181b80dd7744fa16f6e720234c9a9d629b4558cfe84c6e43067f827125a78915"
        ],
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LxcConf": [],
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "KernelMemory": 0,
            "CpuShares": 0,
            "CpuPeriod": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuQuota": 0,
            "BlkioWeight": 0,
            "OomKillDisable": false,
            "MemorySwappiness": -1,
            "Privileged": false,
            "PortBindings": {},
            "Links": null,
            "PublishAllPorts": false,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "VolumesFrom": null,
            "Devices": [],
            "NetworkMode": "default",
            "IpcMode": "",
            "PidMode": "",
            "UTSMode": "",
            "CapAdd": null,
            "CapDrop": null,
            "GroupAdd": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "SecurityOpt": null,
            "ReadonlyRootfs": false,
            "Ulimits": null,
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "CgroupParent": "",
            "ConsoleSize": [
                0,
                0
            ],
            "VolumeDriver": ""
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "46865fae677b",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5003/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dnx/runtimes/default/bin",
                "DNX_VERSION=1.0.0-beta8",
                "DNX_USER_HOME=/opt/dnx"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "Image": "aspnet:try1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b4d6098c499133f57a7bf90c22cc78f603a4857b7baeba652358e8c825564f16",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5003/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/b4d6098c4991",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "48fd94eabaed4216f1f617f046c1495a77f349c163b4bd8e81f2c7c879968d64",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "EndpointID": "48fd94eabaed4216f1f617f046c1495a77f349c163b4bd8e81f2c7c879968d64",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04"
                }
            }
        }
    }
    ]

**nmap port scan for 5003**

    nmap -p 5003 172.17.0.4
    
    Starting Nmap 6.40 ( http://nmap.org ) at 2015-11-09 06:51 EST
    Nmap scan report for 172.17.0.4
    Host is up (0.00011s latency).
    PORT     STATE  SERVICE
    5003/tcp closed filemaker
    MAC Address: 02:42:AC:11:00:04 (Unknown)
    
    Nmap done: 1 IP address (1 host up) scanned in 0.46 seconds

  [1]: https://raw.githubusercontent.com/aspnet/aspnet-docker/master/1.0.0-beta8-coreclr/Dockerfile

**Comment by ahmetalpbalkan** [comment]
in the container inspect output:

```
    "NetworkSettings": {... 
        "Ports": {
            "5003/tcp": null
        },
```

this does not seem normal. Did you map the container to a port while running with 

    docker run -p <host_port>:5003 ...

**Comment by sulhome** [comment]
no I didn't specify port. Why do I need to specify port? I am exposing a port on my container and allowing any one to talk to my container on that port. My host will not talk to this container but another container that has nginx installed.

The problem is that the port is closed. For example I can connect to my enginx container from my asp.net container using nginx ip address:80 and I get a response. But trying to connect to asp.net container using ip:5003 I get connection refused

**Comment by ahmetalpbalkan** [comment]
Hmm in this case I think your question is about Docker, not this image. I don't think there is anything specific to this image right now.

Unless you use `docker run -p <host_port>:5003` to map the ports or `docker run --link` to link the containers,  each port container will make available can be reachable only within that container.

**Comment by ahmetalpbalkan** [comment]
> EXPOSE in dockerfile will open that port on your container allowing connections to it

No, EXPOSE is just merely documentation. Unless you map it, the port will not be opened to outside of container.

**Comment by sulhome** [comment]
do I need to open the port in the host as well? so if I map -p 5003:5003 do I need to open port 5003 on the host?

**Comment by friism** [comment]
@sulhome depending on how you run your docker image, your app will be available on the IP of the VM running your docker container, eg. `docker-machine ip your-vm-name`.

**Comment by ahmetalpbalkan** [comment]
I am not sure what "opening the port on the host" means, but it will make the traffic to 0.0.0.0:5003 on the host routed to the application inside the container. I think you should check out http://docs.docker.com and play with some other types of containers. :)

**Comment by sulhome** [comment]
so I want to run asp.net 5 application in a container. I have nginx container which will host the asp.net application. So the host will map 80:80 to nginx and nginx needs to forward calls to aspnet container:5003.

That is I don't need to open port 5003 on the host (change iptables) but I need to open port 80 so:
http://host public ip address:80 --> nginx forward to 5003 --> aspnet kestrel server

I hope this is clear now. As mentioned. My problem is that the port 5003 is closed on the asp.net container created from the aspnet image. I have changed the image by adding EXPOSE 5003.

Lets say I don't add EXPOSE to docker file and used the file as it is, how will I create a container to fulfill the scenario I mentioned?

**Comment by ahmetalpbalkan** [comment]
First of all you can omit EXPOSE, that doesn't do anything useful at all. It's just documentation as I said before.

In your scenario you have 2 options

* `-p 5003:5003` and block outside-the-machine ingress traffic to this port via firewall. In this case, nginx and other software can reach your app
* Use `docker run --link` feature.

I strongly suggest seeking help at Docker community help channels such as IRC, stackoverflow or forums: https://www.docker.com/community and reading the Docker documentation at http://docs.docker.com/

Closing the issue for now.
