### ISSUE TITLE
Update to beta8 in docker hub

### ISSUE THREAD

**Issue by naveensrinivasan** [aspnet/aspnet-docker#107]
When I looked for the latest aspnet docker file in the docker hub https://hub.docker.com/r/microsoft/aspnet/~/dockerfile/ It still has reference to beta-6. 

Shouldn't it be updated to beta8

**Comment by glennc** [comment]
I don't know where this comes from, and don't appear to have permission to change it. @ahmetalpbalkan?

**Comment by ahmetalpbalkan** [comment]
@naveensrinivasan @glennc  that's just some Docker Hub issue, who knows why... Unfortunately, especially after the new Docker Hub rollout on June 2015, it has just gotten a lot worse and unfortunately getting better very, very slowly. I have a lot of issues reported at https://github.com/docker/hub-beta-feedback/, please feel free to move this over there.

We have references to the Dockerfiles in README (just like official docker images), so closing this.
