### ISSUE TITLE
rc1 image directory naming issues

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#109]
README is currently symlinked to a nonexistent dir:

![image](https://cloud.githubusercontent.com/assets/159209/11254595/fc69a394-8e41-11e5-889a-68ae0059e182.png)

also:

![image](https://cloud.githubusercontent.com/assets/159209/11254588/f2c63186-8e41-11e5-8a4d-02146cb6ae6a.png)

why `-final` @glennc?

**Comment by glennc** [comment]
My PR fixes this, the team decided to add -final to all of the version numbers. The symmetry between the actual DNX version and the tag of the Docker image seemed worthwhile.

**Comment by glennc** [comment]
Fixed in https://github.com/aspnet/aspnet-docker/pull/110
