### ISSUE TITLE
Dockerfile for 1.0.0-rc1-final based on mono:4.0.1 which is not supported

### ISSUE THREAD

**Issue by StefanSchoof** [aspnet/aspnet-docker#111]
The Dockerfile for 1.0.0-rc1-final is based on the [mono:4.0.1](https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-rc1-final/Dockerfile#L1) image. On the [Dockerhub page](https://hub.docker.com/_/mono/) of mono are the supported version listed:

> Supported tags and respective Dockerfile links
>
>    3.10.0, 3.10 (3.10.0/Dockerfile)
>    3.10.0-onbuild, 3.10-onbuild (3.10.0/onbuild/Dockerfile)
>    3.12.1, 3.12.0, 3.12 (3.12.1/Dockerfile)
>    3.12.1-onbuild, 3.12.0-onbuild, 3.12-onbuild (3.12.1/onbuild/Dockerfile)
>    3.8.0, 3.8 (3.8.0/Dockerfile)
>    3.8.0-onbuild, 3.8-onbuild (3.8.0/onbuild/Dockerfile)
>    4.0.5.1, 4.0.5, 4.0 (4.0.5.1/Dockerfile)
>    4.0.5.1-onbuild, 4.0.5-onbuild, 4.0-onbuild (4.0.5.1/onbuild/Dockerfile)
>    4.2.1.102, 4.2.1, 4.2, latest (4.2.1.102/Dockerfile)
>    4.2.1.102-onbuild, 4.2.1-onbuild, 4.2-onbuild, onbuild (4.2.1.102/onbuild/Dockerfile)

4.0.1 is not one of them. The [github project for mono docker](https://github.com/mono/docker) does no longer contain a folder for 4.0.1.

**Comment by ahmetalpbalkan** [comment]
@StefanSchoof thanks for noticing. It looks like we can go back to `4.0`, but if 4.2 is supported, we shall switch to that. cc: @glennc wdyt?

**Comment by dougbu** [comment]
Recommend Mono `4.0.5.1`. Various systems in the DNX ecosystem are incompatible or unstable with more recent Mono (pre)releases.

**Comment by glennc** [comment]
This is somewhat awkward. 4.0.5.1 has issues that stop `dnu restore` from working. The newer supported versions don't have that issue but they have other issues that make some DNX stuff not work.

I don't like depending on an unsupported version so we need to do something but I am not exactly clear what that should be at the moment. @BrennanConroy Is your fix for restore going to make it into the 4.0 train as well as 4.2?

**Comment by akoeplinger** [comment]
@glennc if you're talking about https://github.com/mono/mono/pull/2154, that's scheduled for service release 1 of Mono 4.2. I don't remember you having major problems with 4.0.5.1 ?

**Comment by dougbu** [comment]
@akoeplinger, as @glennc mentioned, we have significant problems when using Mono 4.2.x and need to stick with 4.0.x. E.g. action selection in MVC stops working correctly. Once the mono/mono#2154 fix hits the 4.2.x line, we could retry scenarios using that new rev. But it's not clear that will unblock us.

**Comment by akoeplinger** [comment]
@dougbu please file bugs for everything that stopped working in 4.2 :) The only thing I'm aware of is the intermittent nuget issue that is tracked by https://bugzilla.xamarin.com/show_bug.cgi?id=35947

**Comment by dougbu** [comment]
@akoeplinger we know ` mono .nuget/nuget.exe install` commands often fail and about the action selection issue. But we haven't had time to narrow down things even to know what the mono/mono#2154 fix resolves. As I said, we can look once that fit hits the 4.2.x line.

**Comment by muratg** [comment]
When a newer supported Mono version that works with our stuff, we'll revisit this.  Putting it in 1.0.0 backlog for now.
