### ISSUE TITLE
Add a way to toggle restart/rebuild when files change

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/aspnet-docker#113]
I'm looking to set up a workflow where my aspnet container has the project bind-mounted to `/app` from my development machine.  From there, it hosts out the files.

Unfortunately, it seems like the only way for me to get the server to pick up my changes is to bring down the whole container and then bring it back up.

It would be nice if I could supply an environment variable to the container when running that would have it wrapped by whatever is needed to restart the `dnx` process or whatever flag is needed for `dnx` to rebuild on file change.

**Comment by glennc** [comment]
@atrauzzi this is the same thing that dnx-watch gives you that we talked about in #116?

**Comment by atrauzzi** [comment]
This one is project files, other one is `project.json` (dependencies).  So I think this one is satisfied by `dnx-watch`.

**Comment by glennc** [comment]
Closing since dnx-watch does the job for this one :)
