### ISSUE TITLE
RC1 Can't access the published port. Connection reset by peer.

### ISSUE THREAD

**Issue by sonotude** [aspnet/aspnet-docker#114]
Hi there!

I am having an issue with accessing an asp.net webapi from my docker host box even when I have exposed/published the correct port. The project I am running works fine on my windows box running from Visual Studio. The app is very similar to the standard webapi template in visual studio. My dockerfile: (modified from https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-rc1-final-coreclr/Dockerfile)

```
FROM debian:jessie

ENV DNX_VERSION 1.0.0-rc1-final
ENV DNX_USER_HOME /opt/DNX_BRANCH
#Currently the CLR packages don't have runtime ids to handle debian:jessie but
#we are making sure that the dependencies are the right versions and are opting for
#the smaller base image. So we use this variable to overwrite the default detection.
ENV DNX_RUNTIME_ID ubuntu.14.04-x64

RUN apt-get -qq update && apt-get -qqy install unzip curl libicu-dev libunwind8 gettext libssl-dev libcurl3-gnutls zlib1g && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
	&& dnvm install $DNX_VERSION -alias default -r coreclr \
	&& dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"

# Install libuv for Kestrel from source code (binary is not in wheezy and one in jessie is still too old)
# Combining this with the uninstall and purge will save us the space of the build tools in the image
RUN LIBUV_VERSION=1.4.2 \
	&& apt-get -qq update \
	&& apt-get -qqy install autoconf automake build-essential libtool \
	&& curl -sSL https://github.com/libuv/libuv/archive/v${LIBUV_VERSION}.tar.gz | tar zxfv - -C /usr/local/src \
	&& cd /usr/local/src/libuv-$LIBUV_VERSION \
	&& sh autogen.sh && ./configure && make && make install \
	&& rm -rf /usr/local/src/libuv-$LIBUV_VERSION \
	&& ldconfig \
	&& apt-get -y purge autoconf automake build-essential libtool \
	&& apt-get -y autoremove \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/*

ENV PATH $PATH:$DNX_USER_HOME/runtimes/default/bin

COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5000

ENTRYPOINT ["dnx", "-p", "project.json", "web"]
```

My build command:
```
docker build -t myapp .
```

My run command:
```
docker run -t -d -p 5001:5000 myapp
```

Now if I attach to the container and then run:
```
docker exec curl 127.0.0.1:5000/api/values
```
I can see request being received and responded to correctly. However If I run:
```
curl 127.0.0.1:5001/api/values 
```
from the host machine I get a connection reset by peer message. Sorry if this is something I have done obviously wrong, but I am really not sure what I am doing.

**Comment by sonotude** [comment]
I just tried simplifying my dockerfile by using the image on docker hub and still get the same issue. New dockerfile 
```
FROM microsoft/aspnet:1.0.0-rc1-final-coreclr
COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5000

ENTRYPOINT ["dnx", "-p", "project.json", "web"]
```

**Comment by sonotude** [comment]
Woops my bad! It was a problem with my project.json. The commands sections should have looked like this:
```
"commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://*:5000"
  },
```
The problem was that it defaults binding(?) to localhost which isn't accessible from outside the container.

I can't wait until the documentation around asp 5 is a little better. I seem to be making stupid mistakes all the time. Oh well, at least I am learning!

**Comment by friism** [comment]
@sonotude don't feel bad - other people stumpling on these problems will find these issues you create that has solutions, and they can quickly move on.
