### ISSUE TITLE
Visual Studio 2015 Publish to CustomDockerHost not working

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/aspnet-docker#115]
Hi 

I am trying VS2015 to publish docker image to my docker host on local machine. It is not able to create default docker file for the project and fails with

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(386,5): Error : Cannot find path 'C:\Users\shrivastavar\*****\Dockerfile' because it does not exist.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(386,5): Error : An error occured during publish.
You cannot call a method on a null-valued expression.
Please visit http://go.microsoft.com/fwlink/?LinkID=529706 for troubleshooting guide.

Can anyone help me?

**Comment by muratg** [comment]
@glennc Could you ping docker tooling team about this?

**Comment by glennc** [comment]
cc: @stevelasker @PeterJausovec

**Comment by PeterJausovec** [comment]
@rohitshrivastava04 can you check if you have the latest docker tools for VS installed? (0.9.1)

**Comment by SteveLasker** [comment]
Thanks folks. We did discover a few problems with custom host that we're fixing. We're working on a 0.9.2 release that will address it. Please watch for a release this week. 
Steve

**Comment by muratg** [comment]
Closing this one, please open a new one and ping @SteveLasker if the new release next week doesn't solve this issue.
