### ISSUE TITLE
Provide a way for dependencies to be reloaded when project.json changes

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/aspnet-docker#116]
Another dev-time suggestion similar to #113...

The container obviously keeps its own copy of project dependencies separate to my development machine.  When I use the container as a development server though, any changes to my `project.json` have to be updated manually.

It would be nice if `dnu restore` could be set to run automatically whenever `project.json` changes.  This ensures that dependencies in the container are updated as development progresses.

**Comment by AlexChesser** [comment]
Hey @atrauzzi - this doesn't precisely answer your problem, but my latest commit on the aspnet-generator (PR pending) https://github.com/AlexChesser/generator-aspnet/commit/ba739ffcd2e2c64252feec97d7985707e292c02b has re-ordered the operations on the docker image such that rebuilding your project is much quicker (and uses far less bandwidth) UNLESS the project.json changes. 

That might help with your situation - as it takes a lot of the pain out of writing an application in development.

**Comment by atrauzzi** [comment]
Are you intending to re-build the container every time files change?

**Comment by glennc** [comment]
@atrauzzi The way you would achieve what you are after is to mount your application code, and optionally packages directory, when running your image. You would then run dnx-watch inside the container instead of just dnx. IIRC you need to set the environment variable to have mono use the managed file watcher for dnx-watch to work. Core CLR I think just worked. If you then run your container you can see the output of dnx-watch scroll and it will restart whenever you make changes to your application.

If you don't want to do that then yes, you need to build the whole image again. Whether or not these are enough for you really depends on what you are trying to achieve. Are you trying to run your app inside a container while deving so you can prove it works on Linux, which is your production environment, or is it more about having the exact same thing running on your dev machine that will run in prod? or something else?

**Comment by atrauzzi** [comment]
@glennc - Wouldn't it be a bad idea to mount the system-specific packages directory from the docker host as they are totally different environments?
Perhaps I'm running on Windows with Microsoft's .NET, but my container runs coreclr on linux.  When dnu/dotnet tries to perform package operations, it will be dealing with a directory that is physically on a Windows, but executing on a Linux VM with a vboxsf bridge.  Or the opposite, when the Windows tooling goes to do things, it's affecting a directory that's being run from Linux.

The idea of using `dnx-watch` sounds good to me though, I didn't know that existed.  Am I wrong in thinking that there is possibly outdated documentation out there saying that the server has to be restarted and that some kind of tooling needs to be used to watch for code changes?
Overall though, rebuilding the image during development is not the right solution here.  I should only need to rebuild the image when I want to master a new one.

For your last question: I want to develop with Linux as my environment because it will be my production environment.  Ideally the container when built will be what I ship.  And when I want to develop, I should just be able to flip a switch (docker-compose) and have the code I'm editing be what's running inside the container.

**Comment by AlexChesser** [comment]
@glennc sorry to be a pain, but perhaps you could give some clarification around what's missing here? 

```
FROM microsoft/aspnet
# add sqlite3 to ensure database crash doesn't happen
RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
RUN apt-get -qq update && apt-get install -qqy sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /code
# install DNX watcher and add to PATH
RUN dnu commands install Microsoft.Dnx.Watcher
ENV PATH $PATH:/root/.dnx/bin

# ensure packages are installed on server before code is build to speed reload times
COPY ./WebApplication/project.json /code/project.json
RUN ["dnu","restore"]
# add the rest of the code - lightning fast rebuilds if dependencies are unchanged.
COPY ./WebApplication /code

EXPOSE 5000
### All of the following fail:
# ENTRYPOINT ["dnx-watch" ]
# ENTRYPOINT ["dnx-watch", "web" ]
# ENTRYPOINT ["dnx-watch", "web", "-p", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json", "web", "-p", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json" ]
# ENTRYPOINT ["dnx-watch", "--project", "project.json", "web" ]
### this one DOES work:
ENTRYPOINT ["dnx", "web" ]
```

Note that the code in "WebApplication" is based on the default yeoman generator for an ASPNET project with logins.

**Comment by atrauzzi** [comment]
@AlexChesser - That's unrelated to this ticket, might be worth opening a new one...

**Comment by AlexChesser** [comment]
Fair point, maybe it belongs over in dnu-watch. I'll open an issue there.

**Comment by glennc** [comment]
@atrauzzi That is theoretically a problem, but in practice I haven't seen it cause any problems. Of course I am not really using it in anger. However, mounting the packages is not a mandatory part of this it just speeds up the first build as a bunch of packages are already there.

Restarting the server has always been the way that ASP.NET 5 has achieved this kind of thing, even in Visual Studio on Windows.

So you are ok with using dnx-watch inside the container to solve this problem? Is there more issues you have that I haven't talked about? In general I agree with your statement that you should be able to develop inside a container and not rebuild the container every time you make a change, which dnx-watch gives you.

**Comment by glennc** [comment]
I just realized that I totally conflated this issue and #113. dnx-watch will take care of all the code changes and such. But it will not run restore, it will just sit there until you run restore after you add a dependency to your project.json.

The current state of the world is use dnx-watch for all changes outside of dependency changes in project.json. When you add a dependency you need to `ctrl + c` then re-run dnx-watch. Dnx-watch is meant to be run interactively so you would be running the container and then manually running dnx-watch inside the container.

**Comment by atrauzzi** [comment]
So I guess the problem here is that if I'm developing on a local filesystem and I'm running in a container, sure enough I can watch for changes in my local filesystem.  But the tooling would also have to spit commands into the container as well.  Alternatively, maybe dnx-watch could be made to optionally watch project.json as well?

Big if, I know.

**Comment by glennc** [comment]
yeah, theoretically dnx-watch could watch the project.json/project.lock.json and you would get more of the experience you want. But we should talk about it in the dnx-watch repo :). https://github.com/aspnet/dnx-watch/issues

dnx-watch, or somethign like it, is the way to achieve this there isn't anything docker specific that I think would help.

**Comment by atrauzzi** [comment]
:(
