### ISSUE TITLE
Docker can't restore packages

### ISSUE THREAD

**Issue by ohoncharuk** [aspnet/aspnet-docker#118]
Hello,

I'm using this article to run my hello world asp.net application with linux:
http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx

I use ubuntu 15.
If I run:
dnu restore
on my local machinle inside app follder - it works fine.

But if I run it as:
docker build -t myapp .

it shows namy wornings/errors like:
Warning: FindPackagesById: EntityFramework.SqlServer
  Error: NameResolutionFailure
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='EntityFramework.SqlServer'
Warning: FindPackagesById: EntityFramework.Commands
  Error: NameResolutionFailure
  GET https://api.nuget.org/v3/index.jsonFindPackagesById()?id='EntityFramework.Commands'

and so on........

I use dockerfile exact like in an article.

**Comment by ahmetalpbalkan** [comment]
@ohoncharuk can you please share your Dockerfile and project.json?

**Comment by ohoncharuk** [comment]
Here you go:

﻿{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-RunOnLinux1-ff4e2212-7a38-4a8e-bcbc-4b4ea38939b8",
  "version": "1.0.0-*",

  "dependencies": {
    "EntityFramework.SqlServer": "7.0.0-beta5",
    "EntityFramework.Commands": "7.0.0-beta5",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Google": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta5",
    "Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta5",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta5",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta5",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta5",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta5",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
    "Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta5",
    "Microsoft.Framework.Logging": "1.0.0-beta5",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta5",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta5"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}

**Comment by ohoncharuk** [comment]
Never mind. I've updated docker to the latest version and I able now to restore packages.
However, I can't run an application. I see:
"aspnet50" is an unsupported framework.
"aspnetcore50" is an unsupported framework.

I changed it to be 
"frameworks": {
    "dnx451": { },
    "dnxcore50": { }

exactky as VS default template does, but run into another error:
Error: Unable to load application or execute command 'Microsoft.AspNet.Hosting'. Available commands: web, kestrel.

 I guess that an article http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx is rather outdated. Is there any other resource with a working step by step instruction?

**Comment by muratg** [comment]
@ohoncharuk Yeah, that blog is outdated.  Please refer to https://docs.asp.net/en/latest/getting-started/installing-on-linux.html#using-docker and let me know if you still have issues.

**Comment by muratg** [comment]
@ohoncharuk Also I'd recommend porting your app to RC1 :)

**Comment by ahmetalpbalkan** [comment]
@muratg Hmm I was trying to keep that blog up to date. Can you please send a PR to fix it in README.md of this repo? I'll update the blog post.

**Comment by muratg** [comment]
@glennc Could you look into updating the README.md here?

**Comment by glennc** [comment]
I'm not sure what I would update in the README of this repo, all it does is link to the blog post.

**Comment by ahmetalpbalkan** [comment]
@glennc I think we should update readme to point to https://docs.asp.net/en/latest/getting-started/installing-on-linux.html#using-docker
