### ISSUE TITLE
Visual Studio Docker deployment behind proxy

### ISSUE THREAD

**Issue by senj** [aspnet/aspnet-docker#119]
If i try to deploy a docker package to my linux machine in Visual Studio 2015 I have to set the proxy but where can i do this? The docker tools don't use WebDeploy but only the powershell script?

This is my build command

docker -H tcp://myServer:2376 build -t microsoft/aspnet:1.0.0-rc1-final-coreclr -f "...\Dockerfile" "..\PublishTemp\Project"

**Comment by muratg** [comment]
@glennc Could you ping internal docker tooling team?

**Comment by ahmetalpbalkan** [comment]
cc: @stevelasker @PeterJausovec

**Comment by PeterJausovec** [comment]
@senj  check out this thread: https://github.com/docker/docker/issues/14634

**Comment by muratg** [comment]
@senj https://github.com/docker/docker/issues/14634#issuecomment-155572446 should solve your problem. If not, please feel free to reopen or file another one.
