### ISSUE TITLE
SqlLite3 is out of date - EF crashes generated containers

### ISSUE THREAD

**Issue by AlexChesser** [aspnet/aspnet-docker#121]
As enumerated in this open issue on the generator:

https://github.com/OmniSharp/generator-aspnet/issues/525

The ASPNET docker image cannot successfully run the ASPNET generator as created by the YEOMAN generator.

Pull request incoming. Please feel free to let me know if you'd like it to be backported to prior releases (eg: beta8,7,... etc..)

**Comment by peterblazejewicz** [comment]
@glennc @ahmetalpbalkan 
Can you discuss if there is a possibility of incorporating sqlite3 as dependency to Ubuntu 14.04 based docker image for x-platform EntityFramework?
People are starting using a content promoted via `generator-aspnet` and the EntityFramework needs that  package by default.
Thanks!

**Comment by AlexChesser** [comment]
Hey @peterblazejewicz I think we'd find that this violates the intended purpose of the aspnet-docker image  https://github.com/aspnet/aspnet-docker/issues/123#issuecomment-162256478 which I'm told is "to be as bare bones as possible" (sic)

Adding slqite3 would violate "bare bones" in the case where databases are not needed or perhaps (in future) on the day where EF-x-platform gains connectors for other databases (mysql, postgres, vitesse) OR mssqlserver gets properly "containerized"

While users who are running generators likely want sqllite3, and the added cost of upgrading sqllite3 in the scope of omnisharp projects that don't need it may be minimal.

Or (as it seems you've already mentioned here: https://github.com/OmniSharp/generator-aspnet/pull/526) someone could try to figure out how to if-else the inclusion of the update.

**Comment by glennc** [comment]
Can we split this into 2 PRs I'd like to talk about the two thing separately, pre-installing packages and SQLLite. The pre-installing packages can just be another file that inherits from the microsoft/aspnet right?

**Comment by ahmetalpbalkan** [comment]
@glennc I believe we eliminated the need to pre-instal things with a tip I provided in #123 if I recall correctly.

**Comment by AlexChesser** [comment]
@glennc - the SQLLITE3 update is the only functionality in Pull request https://github.com/aspnet/aspnet-docker/pull/122 I *think* I now have this in a condition that is acceptable to merge please let me know if you need any more cleanup or if you've got tips for "next time" 

@ahmetalpbalkan - that's the "pre-cache dependencies" ticket - it seems the team over at omnisharp feel the sqllite3 update belongs over here.

**Comment by ahmetalpbalkan** [comment]
Agreed.

**Comment by ahmetalpbalkan** [comment]
The change is LGTM. @natemcmaster brought up this before as well (#85). @glennc/@natemcmaster can you please take a look and approve as well?

**Comment by muratg** [comment]
Looks like this is done?

**Comment by AlexChesser** [comment]
Yup - done. Thanks @muratg!

**Comment by muratg** [comment]
Thanks @AlexChesser for the contribution!

**Comment by tinchou** [comment]
Library is now at version `3.8.7.1`: [https://packages.debian.org/jessie/libsqlite3-dev](https://packages.debian.org/jessie/libsqlite3-dev). Should be OK to remove https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-rc1-update1-coreclr/Dockerfile#L15

(see  https://github.com/aspnet/EntityFramework/issues/3089#issuecomment-220219512)
