### ISSUE TITLE
Use git tags

### ISSUE THREAD

**Issue by coding2012** [aspnet/aspnet-docker#125]
The project as it stands right now is creating separate folders for "releases". Most git workflows use git branches and tags for releasing work.

**Comment by ahmetalpbalkan** [comment]
@coding2012 this project follows official Docker image conventions: https://github.com/docker-library/

In most pull requests, we address issues in multiple Dockerfiles at once. Sending a PR to multiple tags/branches is not feasible. In addition to that, this format offers ease of discovery as well. Branches are not very obvious on GitHub and this lays out an easy interface.

**Comment by friism** [comment]
@ahmetalpbalkan I don't have a problem with the current layout, but with the new hub build system, it could probably be branch-based with less work: https://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/
