### ISSUE TITLE
 "dnvm": executable file not found in $PATH

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/aspnet-docker#126]
I am trying to build aspnet 5 app which interacts to SQL server 2014. While deploying the application on docker using microsoft/aspnet:1.0.0-rc1-update1-coreclr.

I have reference to "System.Data.SqlClient": "4.0.0-rc2-23614", to fix the issues in RC1, I have to upgrade it to rc2. 
Now to resolve this dependency, https://www.myget.org/F/aspnetvnext/api/v2 nuget feed should be used, to make use of this I am using -s switch and passing this source url.

Next, dependency is getting resulved properly but I get these errors

    Microsoft.Data.Entity.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-obsolete-l1-2-0.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
         at System.Data.LocaleInterop.LCIDToLocaleName(UInt32 Locale, StringBuilder lpName, Int32 cchName, Int32 dwFlags)
         at System.Data.LocaleInterop.LcidToLocaleNameInternal(Int32 lcid)
in error chain next error is 
    Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
      System.IO.FileNotFoundException: Could not load the specified file.
      File name: 'EntityFramework.Core.resources'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
         at System.Data.LocaleInterop.LCIDToLocaleName(UInt32 Locale, StringBuilder lpName, Int32 cchName, Int32 dwFlags)

Comments on this issue https://github.com/dotnet/corefx/issues/4593, suggests me to upgrade the runtime with rc2 which is unstable at the moment. As I want to upgrade the runtime on docker image, and I cant find a docker image which is built with rc2 runtime, my choice is limited to upgrade the runtime within docker container using dnvm upgrade -unstable.

However when I use dnvm, I get  unrecognized as its not found in $PATH.

Any suggestion? My docker file is as below.

    FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

    ADD . /app

    WORKDIR /app/approot

    RUN ["dnvm", "upgrade", "-unstable", "-r",  "coreclr", "--default"]

    RUN ["dnvm", "use", "default", "-p"]

    RUN [ "dnu", "restore", "--runtime", "ubuntu.14.04-x64", "--source", "https://www.myget.org/F/aspnetvnext/api/v2", "--fallbacksource", "https://www.nuget.org/api/v2"]

    EXPOSE 7600

    ENTRYPOINT ["./web"]

**Comment by rohitshrivastava04** [comment]
Can anyone tell me how to create docker image for RC2 (latest dev build)?

**Comment by glennc** [comment]
RC2 is a bit difficult as it is in the process of transitioning away form DNX and onto the dotnet cli, there are no instructions to help you at the moment. They should be coming soon, but aren't there yet.

**Comment by rohitshrivastava04** [comment]
Could you please tell expected timeline for this?

**Comment by barriestewart** [comment]
@rohitshrivastava04 in case you didn't get this, I think this should probably work at the top of your dockerfile (this is for coreclr so just remove the `-r coreclr` part if you are just using the standard clr)

    FROM microsoft/aspnet:1.0.0-rc1-final-coreclr
    
    # Ensure we have updated to the latest unstable RC2 builds. We need to remove the existing $DNX_USER_HOME/runtimes/default symlink
    # adding a replacement which points to the unstable builds (passing -f to ln didn't work).
    RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
        && dnvm upgrade -u -alias default -r coreclr \
        && dnvm alias default \
        && rm -f $DNX_USER_HOME/runtimes/default \
        && dnvm alias default | xargs -i ln -f -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"

**Comment by rohitshrivastava04** [comment]
Thanks tried it and logged dnx hangs issue. 
https://github.com/dotnet/coreclr/issues/2466

Closing this one now.
