### ISSUE TITLE
Visual Studio 2015 Publish to CustomDockerHost "Custom" was not found Error

### ISSUE THREAD

**Issue by dqywill** [aspnet/aspnet-docker#128]
Hi All, I am trying to publish my asp.net 5 web app to my docker host, but it's not working. The error message like this:

Publishing with publish method [Custom]
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(386,5): Error : An error occurred during publish.
AspnetPublishHandler with name "Custom" was not found

I use vs 2015 with update 1 and Tools for Docker 0.9.2.
I  have repair the tools and vs, but it still not work.
Wish someone can help me, thanks.

**Comment by ahmetalpbalkan** [comment]
@dqywill can you please open an issue at https://github.com/Microsoft/DockerTools ? Your problem does not seem related to the Docker image.

**Comment by dqywill** [comment]
@ahmetalpbalkan thanks a lot. I will close this issue.
