### ISSUE TITLE
Support for dnx452

### ISSUE THREAD

**Issue by promontis** [aspnet/aspnet-docker#129]
Beginning January 12, 2016 only .NET Framework 4.5.2 will continue receiving technical support and security updates. So, I tried running an aspnet5 app on the 1.0.0-rc1-update1 (mono) image using dnx452 instead of dnx451, by specifying it in the project.json file under "frameworks.". However, when I try to run the docker image I get the following error:

```
System.InvalidOperationException: The current runtime target framework is not compatible with 'app'.
Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-rc1-16231
 Type:         Mono
 Architecture: x64
 OS Name:      Linux
 OS Version:   debian 8
 Runtime Id:   debian.8-x64

Please make sure the runtime matches a framework specified in project.json
```

Is dnx452 not supported on mono (I've read that dnx46 is not yet supported)? Or can I somehow set the runtime target framework for the docker image to dnx452?

**Comment by muratg** [comment]
Yeah, AFAIK, dnx452/dnx46 are not supported on Mono.  I think they're working on .NET 4.5.2 compat though I'm not sure what the status is.  

cc @migueldeicaza
