### ISSUE TITLE
Docker Helper

### ISSUE THREAD

**Issue by kscott5** [aspnet/aspnet-docker#132]
Here's my Dockerfile!

```
FROM microsoft/aspnet:1.0.0-rc1-final

COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5000/tcp
ENTRYPOINT ["dnx", "-p", "project.json", "web"]
```

I executed the following command from Docker QuickStart Terminal on Windows using the info above.

docker build -t 'reponame/appname:1.0.0' .

![capture](https://cloud.githubusercontent.com/assets/132991/12799890/14e6fd36-ca97-11e5-89f1-2dc04247f7b9.PNG)

It run successfully. Then I execute the following command

docker run -it 'reponame/appname:1.0.0' 

It displays the message Kestrel is running on http://localhost:5000 then disappears. 
When I try to access the site from browser the server could not be found.

What am I missing or doing wrong?

**Comment by muratg** [comment]
Does the app run without docker, i.e. on the host directly?

**Comment by kscott5** [comment]
Yes. I changed the hosting.json to use 0.0.0.0:6001 based on another post. It didn't work either.


Sent from my T-Mobile 4G LTE Device


-------- Original message --------
From: Murat Girgin
Date:02/04/2016 11:24 AM (GMT-06:00)
To: aspnet/aspnet-docker
Cc: Karega Scott
Subject: Re: [aspnet-docker] Docker Helper (#132)


Does the app run without docker, i.e. on the host directly?

-

**Comment by muratg** [comment]
@kscott5 were you able to resolve the issue?  BTW, in RC2 we'll be retiring DNX based images (as well as DNX tooling) and move to use dotnet CLI for the dev workflow. Hence the docker images will also be dotnet CLI based.
