### ISSUE TITLE
Updated version of mono

### ISSUE THREAD

**Issue by aplogicdlamb** [aspnet/aspnet-docker#133]
The Dockerfile results in using mono 4.0.4 instead of 4.2.2. 4.0.4 does not properly write DBNull.Value to nullable Integer or DateTimeOffset fields in an MSSQL Server database (or at least Amazon AWS RDS). To get 4.2.2, the Dockerfile should include the directives described at http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives.

```
FROM microsoft/aspnet
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list \
	&& apt-get update \
	&& apt-get install mono-complete -y
```

**Comment by muratg** [comment]
In RC2 we'll be retiring DNX based images (as well as DNX tooling) and move to use dotnet CLI for the dev workflow. Hence the docker images will also be dotnet CLI based.
