### ISSUE TITLE
 dnu restore failed on latest coreclr image

### ISSUE THREAD

**Issue by ArkadyB** [aspnet/aspnet-docker#134]
Hi,

Recently tried to check the latest coreclr image with my project and found i cant run it anymore:

> dnu restore
> failed to locate libcoreclr with error /opt/DNX_BRANCH/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-update1/bin/libcoreclr.so: cannot restore segment prot after reloc: Permission denied

Please suggest... Whats wrong with it? dnx command also does not work.

dnvm list:
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-update1    coreclr x64          linux           default

**Comment by muratg** [comment]
@ahmetalpbalkan Any idea why this may be?

@ArkadyB BTW, in RC2 we'll be retiring DNX based images (as well as DNX tooling) and move to use dotnet CLI for the dev workflow. Hence the docker images will also be dotnet CLI based.

**Comment by ahmetalpbalkan** [comment]
@muratg I haven't been following the image or aspnet/dotnet core lately. I think it is time for somebody better than me should take over this project to take a look at the issues and address them appropriately.
