### ISSUE TITLE
Is Sqlite necessary if not using EF, Identity, etc?

### ISSUE THREAD

**Issue by markrendle** [aspnet/aspnet-docker#135]
The coreclr image installs sqlite3 and libsqlite3-dev. Are these actually necessary for the CoreCLR runtime, or are they just being installed for applications that use Entity Framework and ASP.NET Identity?

**Comment by friism** [comment]
Yeah, it's required to get EF stuff working: https://github.com/aspnet/aspnet-docker/pull/122
