### ISSUE TITLE
Error pulling microsoft/aspnet

### ISSUE THREAD

**Issue by tonysneed** [aspnet/aspnet-docker#138]
I'm currently unable to pull the aspnet docker images.  I get the following error:

```shell
084abb20fe07: Error pulling image (latest) from microsoft/aspnet, endpoint: http084abb20fe07:
Error pulling image (latest) from microsoft/aspnet, Server error: Status 0 while fetching image layer (3d23db4843323b3dd62608a6a3ea6a0cc6fc2e1f88a
Error pulling image (latest) from microsoft/aspnet, Server error: Status 0 while fetching image layer (3d23db4843323b3dd62608a6a3ea6a0cc6fc2e1f88a1b270b57dbe4860994886)
```

Any help would be appreciated.

**Comment by friism** [comment]
@tonysneed this is unlikely to be a problem with this repo. Can you pull other image, eg. `docker pull  alpine`?

If you're having problems using Toolbox, you can ask for help on the forums or on the Toolbox GitHub repo:

 * https://forums.docker.com/c/open-source-projects/docker-toolbox
 * https://github.com/docker/toolbox/

**Comment by tonysneed** [comment]
You're right - I tried it from a different network and I was able to pull microsoft/aspnet.  I was using a hotel wifi, and there must have been connectivity issues. :)
