### ISSUE TITLE
exec: "dnu": executable file not found in $PATH in 1.0.0-beta6

### ISSUE THREAD

**Issue by zhshqzyc** [aspnet/aspnet-docker#140]
I am using [microsoft/aspnet:1.0.0-beta6](https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta6/HelloMvc) model in my own project. It seems that the image is broken.

The Dockerfile is
```
FROM microsoft/aspnet:1.0.0-beta6
COPY project.json /app/
WORKDIR /app
RUN ["dnu", "restore"]
COPY . /app
EXPOSE 5005
ENTRYPOINT ["dnx", "project.json", "kestrel"]
```

See the picture below.
![dnu](https://cloud.githubusercontent.com/assets/7240266/14562723/5b17026e-02ec-11e6-81e3-e1e878a4545d.PNG)

**Comment by BrennanConroy** [comment]
Why beta6? That is really old, we have RC1 dockerfiles https://github.com/aspnet/aspnet-docker/tree/master/1.0.0-rc1-update1

**Comment by zhshqzyc** [comment]
I know. But we have application running with beta6. We will upgrade it in the future. But for the time being, it is beta6.

**Comment by BrennanConroy** [comment]
Ok, well you should probably install dnx in your dockerfile. Take a look at https://github.com/aspnet/aspnet-docker/blob/master/1.0.0-beta6/Dockerfile

**Comment by zhshqzyc** [comment]
Do you mean my Dockfile should be
```
FROM mono:4.0.1

ENV DNX_VERSION 1.0.0-beta6
ENV DNX_USER_HOME /opt/dnx

RUN apt-get -qq update && apt-get -qqy install unzip

RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
	&& dnvm install $DNX_VERSION -alias default \
	&& dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"

# Install libuv for Kestrel from source code (binary is not in wheezy and one in jessie is still too old)
RUN apt-get -qqy install \
	autoconf \
	automake \
	build-essential \
	libtool
RUN LIBUV_VERSION=1.4.2 \
	&& curl -sSL https://github.com/libuv/libuv/archive/v${LIBUV_VERSION}.tar.gz | tar zxfv - -C /usr/local/src \
	&& cd /usr/local/src/libuv-$LIBUV_VERSION \
	&& sh autogen.sh && ./configure && make && make install \
	&& rm -rf /usr/local/src/libuv-$LIBUV_VERSION \
	&& ldconfig

ENV PATH $PATH:$DNX_USER_HOME/runtimes/default/bin

# Prevent `dnu restore` from stalling (gh#63, gh#80)
ENV MONO_THREADS_PER_CPU 2000

COPY project.json /app/
WORKDIR /app
RUN ["dnu", "restore"]
COPY . /app

EXPOSE 5005
ENTRYPOINT ["dnx", "project.json", "kestrel"]
```
Visual Studio warns me 

> unknown instruction autoconf

**Comment by BrennanConroy** [comment]
I was just pointing it out for reference.
Specifically you need at least something similar to:
```
ENV DNX_VERSION 1.0.0-beta6
ENV DNX_USER_HOME /opt/dnx
RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
    && dnvm install $DNX_VERSION -alias default \
    && dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{} $DNX_USER_HOME/runtimes/default"
```

**Comment by zhshqzyc** [comment]
@BrennanConroy 

Need help because I am not strong on dnvm. It warns me 

> dnvm needs unzip to proced.

![demo](https://cloud.githubusercontent.com/assets/7240266/14569798/ded65132-030e-11e6-88e5-ed770240734f.PNG)

**Comment by BrennanConroy** [comment]
Add `RUN apt-get -qq update && apt-get -qqy install unzip`

**Comment by zhshqzyc** [comment]
@BrennanConroy 

I added it. Now my Dockerfile is
```
FROM mono:4.0.1
ENV DNX_VERSION 1.0.0-beta6
ENV DNX_USER_HOME /opt/dnx
RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_USER_HOME=$DNX_USER_HOME DNX_BRANCH=v$DNX_VERSION sh
RUN apt-get -qq update && apt-get -qqy install unzip
RUN bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
    && dnvm install $DNX_VERSION -alias default \
    && dnvm alias default | xargs -i ln -s $DNX_USER_HOME/runtimes/{}    $DNX_USER_HOME/runtimes/default"
COPY project.json /app/
COPY . /app/
WORKDIR /app
RUN ["dnu", "restore"]


ENTRYPOINT ["dnx", "-p", "project.json", "web"]
```
But at the last step. I still get the error
`exec: "dnu": executable file not found in $PATH`

**Comment by BrennanConroy** [comment]
Ok, so now you need to add the installed dnx to your path `ENV PATH $PATH:$DNX_USER_HOME/runtimes/default/bin`

**Comment by zhshqzyc** [comment]
@BrennanConroy .

It is downloading but the yellow warning about Timeout. Finally the task was canceled. 

![1](https://cloud.githubusercontent.com/assets/7240266/14571005/0c434278-0315-11e6-8016-94b83f7bce16.PNG)

**Comment by BrennanConroy** [comment]
I don't know what to do about that

**Comment by zhshqzyc** [comment]
Add this one resolved it. [mono super slow](https://github.com/aspnet/dnx/issues/1590)
```
# Prevent `dnu restore` from stalling (gh#63, gh#80)
ENV MONO_THREADS_PER_CPU 2000
```
