### ISSUE TITLE
Repository description

### ISSUE THREAD

**Issue by Hammerstad** [aspnet/aspnet-docker#145]
Hey.

I read on [hanselman.com](http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx) that  ASP.NET 5 is now ASP.NET Core 1.0.

If this is not the case, then please close this issue.
 
Else, you might want to change the description of the repository from `Docker image for ASP.NET 5` to `Docker image for ASP.NET Core 1.0`

**Comment by muratg** [comment]
Updated the title to reflect the current situation
