### ISSUE TITLE
GETTING ERROR WHILE PULLING 

### ISSUE THREAD

**Issue by ravindravv** [aspnet/aspnet-docker#146]
I tried to pull the imag by using docker pull Microsoft/aspnet . getting the below error . please look into this and do the need.

docker : failed to register layer: re-exec error: exit status 1: output: open \\?\C:\ProgramData\docker\windowsfilter\5b580d0b0638dc43a4d74
bf0e05ab3e83736c60c2641146788453c15e4ec6503\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label 
syntax is incorrect.
At line:1 char:1
+ docker pull microsoft/aspnet
 + CategoryInfo          : NotSpecified: (failed to regis...x is incorrect.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by muratg** [comment]
The current image is not supported.  Since ASP.NET Core and .NET Core RTM'd, I recommend using microsoft/dotnet image and using RTM bit.
