### ISSUE TITLE
Any plans about mono-based ASP.NET Core image?

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#153]
Ported from https://github.com/dotnet/dotnet-docker/issues/45 as this is an ASP.NET specific question.

**Comment by muratg** [comment]
@MichaelSimons asp.net image is [based on](https://github.com/aspnet/aspnet-docker/blob/master/1.0.1/jessie/build/Dockerfile#L2) dotnet image.

AFAIK, there're no plans to create a supported Mono based image from either team.
