### ISSUE TITLE
Cant run asp.net core full framework app on Windowsservercore Docker'

### ISSUE THREAD

**Issue by douglaswaights** [aspnet/aspnet-docker#155]
Hi,

I'm not sure where to be posting some of these issues... here or Docker for windows github or docker forums.

I'm trying to run a full framework asp.net core app on the lastest windowsservercore docker image on windows 10. I'm on the latest bits at the time of writing. I've attached an image showing the error and that the full framework is in fact installed

The error when doing dotnet run (after dotnet restore) is
The current project is not valid because of the following errors:
C:\dockerweb\project.json(21,15): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6.1 in

<img width="1479" alt="docker_for_windows" src="https://cloud.githubusercontent.com/assets/5701083/19156014/b5afdfa2-8be0-11e6-9e32-c7c04e89814c.png">

The Dockerfile looks like this
FROM microsoft/windowsservercore:latest

#add iis
RUN powershell -Command Add-WindowsFeature Web-Server

#add full framework
RUN powershell -Command Add-WindowsFeature NET-Framework-45-ASPNET
RUN powershell -Command Add-WindowsFeature Web-Asp-Net45

# Install .NET Core SDK
ENV DOTNET_SDK_VERSION 1.0.0-preview2-003131
ENV DOTNET_SDK_DOWNLOAD_URL https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$DOTNET_SDK_VERSION/dotnet-dev-win-x64.$DOTNET_SDK_VERSION.zip

RUN powershell -NoProfile -Command \
        $ErrorActionPreference = 'Stop'; \
        Invoke-WebRequest %DOTNET_SDK_DOWNLOAD_URL% -OutFile dotnet.zip; \
        Expand-Archive dotnet.zip -DestinationPath '%ProgramFiles%\dotnet'; \
        Remove-Item -Force dotnet.zip

RUN setx /M PATH "%PATH%;%ProgramFiles%\dotnet"

# Trigger the population of the local package cache
ENV NUGET_XMLDOC_MODE skip
RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rmdir /q/s warmup

I'm then mounting a local volume for my test app (runs on full framework 4.6.1 web api sample out of the box) to test out dotnet restore (which works) and dotnet run which fails...

Could anyone explain what i'm doing wrong here?

Thanks
Doug

**Comment by friism** [comment]
Can you post the framework part of your project.json?

**Comment by douglaswaights** [comment]
yep sure

{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  **"frameworks": {
    "net461": { }
  },**

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by troydai** [comment]
Hi @douglaswaights,

Thanks for reporting the issue. 

Since your intention is to run a full framework ASP.NET, whether or not .NET Core Runtime is installed is not related. 

In your first screen shot it seems that the framework you installed is .NET 4.6 instead of 4.6.1. I can't deterministically tell if they're equivalent but base on the name it seems that the installed framework is one minor version behind. @glennc can you tell if the .NET 461 feature should be independently installed?

Regards,
Troy

**Comment by shirhatti** [comment]
Adding @staceyhaffner in case she knows what's going on

**Comment by douglaswaights** [comment]
Hi,

My initial intention is to use the container as a build agent / environment to build asp.net core /dotnet core apps that run on the full framework.

I've also tried setting the framework version to net451 in the project.json and the result is the same. 

46 should be backwards compatible to 45.

Its like the dotnet cli sdk doesnt recognise the full framework is installed. Is this because its not really the full framework that's is installed.... rather its the .net framework runtime that comes with windows server 2016?

I've been trying to install the full framework from an offline package (to test the theory) inside the container but i cant seem to get this to work.

I've also installed ANCM inside a running container but that makes no difference...

Doug

**Comment by douglaswaights** [comment]
Hi,

This can be closed!

I needed to install the .net sdk dev pack in addition.

NDP461-DevPack-KB3105179-ENU.exe /q inside the running container was what was required.

Thanks
Doug

**Comment by glennc** [comment]
@richlander @shirhatti This is not the only person I have seen try to do this. How big is the DevPack? Should we install it in the image or create a `-build` variation the same as the aspnetcore image?

**Comment by shirhatti** [comment]
From what @douglaswaights reported, It isn't evident if this issue repros when trying to run a published app as opposed to running from source. I'd definitely like to verify that isn't the case.

**Comment by douglaswaights** [comment]
If the app was already published then this was not an issue. Only an issue for building and running from source.

To my mind it makes sense for a 46 and 45 sdks to be provided in an image or images...i guess quite few people may need this....

The 46 dev pack download itself is 90 Mb. Haven't compared docker image size before and after the new layer yet.

Doug

**Comment by willseward** [comment]
I agree. We are using the full .Net 462 in a project with core as well. What will it take to get a 462 base image setup?
