### ISSUE TITLE
Create a Nano image

### ISSUE THREAD

**Issue by glennc** [aspnet/aspnet-docker#158]
We need a Nano based image for aspnetcore and probably aspnetcore-build as well.

**Comment by muratg** [comment]
cc @natemcmaster

**Comment by natemcmaster** [comment]
Should we do this on https://github.com/aspnet/aspnet-win-docker?

**Comment by muratg** [comment]
@natemcmaster Yeah, I think so.

**Comment by aL3891** [comment]
Any update on this? would love to see a nano image :)

**Comment by glennc** [comment]
It is on our list to do, but with all our recent releases it hasn't hit the top of the list yet. The `dotnet` image has Nano versions. So for the short term you would have to use that.

**Comment by kendrahavens** [comment]
I'll add having a nano server image for aspnetcore would make the documentation I'm working on more cohesive.

**Comment by kwaazaar** [comment]
I'm currently trying to create powershell scripts and Dockerfiles for building and running my .NET core solution on Windows containers, where I already had everything running on Linux containers. I expect the windows equivalent versions of all containers to 1) exist, 2) have a consistent naming convention, so I only need to add a tag, whatever. Both 1 and 2 are not (fully) in place.

I'm searching all over the place trying to find what I need. Why isn't there any more documentation? This repo doesn't even have a readme.md...

**Comment by glennc** [comment]
This repo has several readmes, but they are all in the directories for the specific images they document rather than the top level. We could put one of those at the root, but it wouldn't really help, and I think that adding one not specific to one of the images we build would not work well with the docker build system that is linked to the repo. You're right that it is confusing, but we didn't leave it out without a reason when we created the repo.

What specifically are you having trouble with? If you are building .NET Core applications then the Microsoft/dotnet repo on DockerHub should contain all the Windows images you would need. They will not be as optimized for web scenarios as the aspnetcore one will be once we produce it, but they will work for ASP.NET Core as well as any other .NET Core console application. Is it because you are trying to share Dockerfiles and do token replacements or something and consistency in naming is inconvenient or discoverability of what images you actually need for your scenario?

**Comment by glennc** [comment]
@natemcmaster Can you look at making the Dockerfiles? @MichaelSimons will take care of making sure they are being built and pushed.

**Comment by natemcmaster** [comment]
Should we put these Dockerfiles here or https://github.com/aspnet/aspnet-win-docker?

**Comment by MichaelSimons** [comment]
@natemcmaster, IMO they should be next to the Debian variants (e.g. in the same repo).  This will make it much easier to support the Docker multi-arch functionality (e.g. use a common tag between the Debian and Nano images)

**Comment by MichaelSimons** [comment]
@natemcmaster, I see you recently added the `working` label.  Just so I can plan my work accordingly, do you have a rough idea on when the Dockerfiles will be available?

**Comment by natemcmaster** [comment]
I should have an initial draft ready later today. Testing and verification should be done this week.

**Comment by natemcmaster** [comment]
Adding @MichaelSimons as an assignee (along with myself). 

Remaining work:

- [x] Create dockerfiles (done in #216)
- [ ] Setup CI infrastructure to build + test + push (@MichaelSimons)
- [ ] Update README with nanoserver tags (@natemcmaster)

**Comment by MichaelSimons** [comment]
@natemcmaster - I hooked CI for build + test + push.  Are you going to hookup Travis CI for PRs?  Is there support for this scenario in Travis?

**Comment by natemcmaster** [comment]
Travis can only build Debian-based images. We might be able to use AppVeyor to build PRs to the Nano Serve image, but I'm not sure if their agents use Linux or Windows containers.

**Comment by kwaazaar** [comment]
Their new VS 2017 agent runs on Windows Server 2016 and supports Docker.
That should do, right?

Op do 6 apr. 2017 19:01 schreef Nate McMaster <notifications@github.com>:

**Comment by natemcmaster** [comment]
Not necessarily. "Docker for Windows" can be configured to run Linux or Windows containers, but not both. I would guess it's the latter as Linux containers are more popular.

**Comment by kwaazaar** [comment]
https://www.appveyor.com/docs/build-environment/#docker

For Windows it is.

Op do 6 apr. 2017 19:17 schreef Nate McMaster <notifications@github.com>:

**Comment by natemcmaster** [comment]
👏 adding that page to my bookmarks. Thanks @kwaazaar. I'll look into enabling AppVeyor for PRs
