### ISSUE TITLE
Verify package cache actually improves startup perf

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#165]
We've received some feedback that startup time in Linux docker images is not improved by the presence of the optimized package cache. We should investigate: 

- Crossgen on Linux doesn’t work. The generated assemblies don’t save JIT time.
- .NET core host (dotnet.exe) doesn’t pick up package cache correctly.
- The approach in which we generate the packages cache is wrong. 

cc @BrennanConroy @shhsu

**Comment by BrennanConroy** [comment]
The package cache on Linux didn't work before because we created the cache with lower case naming when preview 2 CLI was expecting original casing, after changing the cache to original casing I saw ~33% increase in startup time and first request time

**Comment by natemcmaster** [comment]
The 1.0.1 docker images have original casing. So, is this issue fixed then?

**Comment by BrennanConroy** [comment]
Looks like it is good now.
