### ISSUE TITLE
Keeps asking for SDK

### ISSUE THREAD

**Issue by mjdavies** [aspnet/aspnet-docker#175]
Hello everyone

I've followed the instructions on the docker hub page and created my own dll, but I can't seem to get my container to run, it keeps asking for the SDK?

Here's what I'm trying to achieve

https://hub.docker.com/r/microsoft/aspnetcore/

Anyone got any ideas?

Keeps saying this on docker run

Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by natemcmaster** [comment]
Can you share your docker file or exactly what steps you are taking? You should be able to execute `dotnet MyApp.dll` in this image.

On the otherhand, if you are trying to run `dotnet restore` or `dotnet build`, you need the https://hub.docker.com/r/microsoft/aspnetcore-build/ image instead.

**Comment by mjdavies** [comment]
Hi @natemcmaster , thanks for getting back.

I'm actually asking for someone else, so they'll be able to give you some more info about what's going on here.

Kwe, this gent may be able to help you.

@kwe

**Comment by mktitan** [comment]
@natemcmaster I'm having the same issue. My Dockerfile:

```
FROM microsoft/aspnetcore
WORKDIR \RecensysCoreWebAPI\bin\Release\netcoreapp1.0
COPY . .
ENTRYPOINT ["dotnet", "RecensysCoreWebAPI.dll"]
```
gives

```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by natemcmaster** [comment]
> WORKDIR \RecensysCoreWebAPI\bin\Release\netcoreapp1.0

Docker is Linux based. Use forward slashes. Also, [WORKDIR](https://docs.docker.com/engine/reference/builder/#/workdir) is a path within the container, and is not relative to your project.

> COPY . .

Which folder is the Dockerfile in relative to your source code? If is next to your project.json/csproj file, my guess is RecensysCoreWebAPI.dll isn't in the entry folder. Run `docker run --rm -it --entrypoint=/bin/bash $your_image_id` to figure out what files are in your container.

**Comment by mktitan** [comment]
@natemcmaster Thank you for the feedback. I wasn't getting the dlls into the container, but that works now.

dotnet will give the message that we got whenever an unrecognized parameter is provided. In our case it couldn't find the dll file. Notice that the name is case-sensitive.

@mjdavies I think this issue can be closed.

**Comment by mjdavies** [comment]
@mktitan I believe you are correct
