### ISSUE TITLE
Images are not identical for equivalent tags

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#177]
**Repo Steps**
1. Pull the 1.0.1 and lts tags.
2. Run `Docker Inspect` on these tags and inspect the layers, the image shas and the repo tags sections.

**Expected Results:**
The images should be identical and have all of the same layers

**Actual Results**
The images are not identical

1.0.1 - sha256:a6243daeaf8a87804c9134690e6b0d7b0e219b5211d90258910e9548bb61d73c
lts - sha256:0ff2fd6ffd3910fccb9c0598d91ccf339fd51acf3993ae61a8d51dd178adf6f3

This issue also applies to the 1.1.0 and latest images.  Please also verify that the build images do not have the same problem.

I speculate this is caused by how the images are getting built.  You can't use the Docker Hub autobuild infrastructure with multiple build settings.  You need to use build hooks if you want to use DockerHub autobuilds or you can use the Docker Cloud infra which has built-in support for multi-tagging.

**Comment by natemcmaster** [comment]
Thanks for sharing. I noticed the same thing and was just reading up on the post_push hooks yesterday. Will get a fix soon.
