### ISSUE TITLE
port binding not working

### ISSUE THREAD

**Issue by paddyfay** [aspnet/aspnet-docker#179]
I am trying to bind ports between my docker host and aspnet container. The container is created from the latest aspnet image. The following run command successfully starts the container however the aspnet site is only reachable from the private IP address of the container. 

docker run -d -p 80:80 --name=test-site asp-site

The relating entry in docker hub states that reaching the container using localhost from the host is not supported in the current release. Does this mean that using the private IP address of the host is also not supported?

**Comment by natemcmaster** [comment]
This issue was moved to Microsoft/aspnet-docker#13

**Comment by natemcmaster** [comment]
@paddyfay I've moved your issue to the appropriate repo. We're aware Docker Hub pointed you here. We have not yet been able to update that link to point to the microsoft/aspnet images's new GitHub home. (cref https://github.com/Microsoft/aspnet-docker/issues/2)
