### ISSUE TITLE
Error - "executable file not found in $PATH" when running dockerfile

### ISSUE THREAD

**Issue by arthur-peka** [aspnet/aspnet-docker#18]
As I didn't find any instruction, I assumed that container should be run as a daemon. So, having pulled microsoft/aspnet container I ran `sudo docker run microsoft/aspnet -d` only to get `executable file not found in $PATH` error.

Are there any specific parameters that need to be passed?

**Comment by ahmetalpbalkan** [comment]
@arthur-peka can you please follow the tutorial here and see if the issue still exists? http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx If not, please consider closing.

**Comment by arthur-peka** [comment]
Thanks, just checked. Tutorial is detailed and everything is running fine.

**Comment by willemKing** [comment]
Errors in /app/project.json
    "aspnet50" is an unsupported framework.
    "aspnetcore50" is an unsupported framework.
