### ISSUE TITLE
Included files/folders in publishOptions are ignored on linux/docker

### ISSUE THREAD

**Issue by DMWOO7** [aspnet/aspnet-docker#180]
I followed [this Article](https://blogs.msdn.microsoft.com/stevelasker/2016/09/29/building-optimized-docker-images-with-asp-net-core/) for setting up a docker container that build and publish an ASP.NET Core 1.0.1 application. But on linux, any included files and folders like the views are missing. I already posted it in SO [here](http://stackoverflow.com/questions/41306314/the-directory-name-app-views-is-invalid-on-asp-net-core-deployment-using-doc). I did some testing and it seems more and more that this is a bug. 

**The following is not working:** 
Create a new ASP.NET Core app using `dotnet new -t web` on Windows 10. Or alternatively use Visual Studio, which will not work too. Now move the entire folder to a linux machine (debian in my case) in a  docker container using the [ASP.NET Core Build-Image](https://hub.docker.com/r/microsoft/aspnetcore-build/). I did it like recommend in [this article](https://blogs.msdn.microsoft.com/stevelasker/2016/09/29/building-optimized-docker-images-with-asp-net-core/): One container for building the app with the **aspnetcore-build** image, and another one including only the smaller **aspnetcore** runtime docker-image. 

I used the following dockerfile 

```
FROM microsoft/aspnetcore-build:1.0.1
WORKDIR /app
COPY . .

RUN echo '{ "allow_root": true }' > /root/.bowerrc

RUN dotnet restore
RUN dotnet publish --output /output/.
RUN ls -lh /output | grep View
```

Now build the container using

`docker build -t x -f Dockerfile.build`

In the last step, you will see all files/folders in the output folder which contains the term _Views_:

```
Step 7 : RUN ls -lh /output | grep View
 ---> Running in d6d204d602af
-rwxr--r-- 1 root root 237K Aug 31 17:26 Microsoft.AspNetCore.Mvc.ViewFeatures.dll
```

You see, the `Views` and `wwwroot` folders are missing - although they're included in the `buildOptions` section. This will naturally break the entire web application, since the views are not precompiled in a dll file like [RazorGenerator](https://github.com/RazorGenerator/RazorGenerator) would do it for old ASP.NET 4.x applications. 

When you do a restore and publish on a Windows machine (so without any docker container), its working as expected: 

```
C:\test>dir | findstr View
31.08.2016  16:26           242.168 Microsoft.AspNetCore.Mvc.ViewFeatures.dll
23.12.2016  20:00    <DIR>          Views
```

```
C:\test>dir | findstr www
23.12.2016  20:00    <DIR>          wwwroot
```

I'm not sure if this is a bug of the .NET Core CLI or your docker images. But I tried a lot of things. For me it seems that there exists an issue on linux for projects which are created on Windows. Only folders from `publishOptions` are affected.

**Comment by DMWOO7** [comment]
The problem is a mistake in the [documentation](https://hub.docker.com/r/microsoft/aspnetcore-build/). At the end, here is written for the dockerfile 

`RUN dotnet publish --output /out/. --configuration Release`

which is not correct, there is a space between the output folder and the dot missing. It should be

`RUN dotnet publish --output /out/. --configuration Release`

But the dotnet CI doesn't throw an error here. I think it should when the current folder is missing. Or use the path from the CI was started when no path is passed.

**Comment by natemcmaster** [comment]
> The problem is a mistake in the documentation. 

Suggested resolution: we fix the README.md. Also, this is likely mitigated by migration to MSBuild. 

@glennc, we should review the examples in README.md to make sure they work with MSBuild CLI

**Comment by natemcmaster** [comment]
README updated in https://github.com/aspnet/aspnet-docker/commit/194aaeece56dc32a20c442377e69cb2a8a798c32
