### ISSUE TITLE
Rebuild 3.5 tag on new windowsservercore base image version

### ISSUE THREAD

**Issue by git-jiby-me** [aspnet/aspnet-docker#181]
It seems the version of base image windowsservercore was updated (latest one is 10.0.14393.576), however it seems the 3.5 tag is not rebuild using the new base image, can you guys do that, so that we end up reusing the base image used by other images, and end up using the latest base image ?

**Comment by natemcmaster** [comment]
This issue was moved to Microsoft/aspnet-docker#15
