### ISSUE TITLE
Update NodeJs version

### ISSUE THREAD

**Issue by ClaytonHunt** [aspnet/aspnet-docker#182]
The Node version is currently 4.5.0
The current LTS for node is 6.9.2
The current available version for node is 7.3.0

Can this be updated? I'm happy to submit a pull request for it.

**Comment by natemcmaster** [comment]
Seems reasonable, as long as @glennc is on board too.

**Comment by glennc** [comment]
Seems reasonable to me, if you submit a PR I would accept it.

**Comment by glennc** [comment]
I am thinking the current node LTS is what we should stick with. Agreed?

**Comment by ClaytonHunt** [comment]
Awesome, thanks for the replies. I will assume LTS unless more discussion around which node version occurs and I will submit a PR sometime this weekend.

**Comment by natemcmaster** [comment]
Looking forward to it. You can tag me as the reviewer and I'll help get this merged.

**Comment by natemcmaster** [comment]
Resolved in https://github.com/aspnet/aspnet-docker/pull/185
