### ISSUE TITLE
[Question] Debugging containerized ASP.NET Core application from VS Code

### ISSUE THREAD

**Issue by matjazmav** [aspnet/aspnet-docker#186]
I don't know where to ask. Is it possible to run and debug ASP.NET Core application that run inside container from Visual Studio Code? Can you provide tutorial how to do so?

**Comment by natemcmaster** [comment]
cc @stevelasker

**Comment by tanaka-takayoshi** [comment]
I confirmed it. You may have to run Visual Studio Code on the same machine as a docker host and to install and run ``clrdbg`` in the docker container. If you use kubernetes, OpenShift and like other technologies, you can remote debug from Visual Studio code to ASP.NET Core container.
I blogged [this theme in Japanese](http://tech.tanaka733.net/entry/remote-debug-aspnetcore-on-docker-from-visual-studio-code). If you need, I will blog it in English. Or write a document in GitHub if someone points a more suitable place.

**Comment by SteveLasker** [comment]
You can do this with the Visual Studio Code extension: http://aka.ms/DockerToolsForVSCode

**Comment by natemcmaster** [comment]
Closing as it appears this question has been answered. Feel free to continue discussion.
