### ISSUE TITLE
Proposal: ONBUILD image

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#19]
For those who are not familiar, Dockerfiles can have an instruction called [ONBUILD](http://docs.docker.com/reference/builder/#onbuild) which invokes the preceding command when the image is used *as a base image* for building another image (typically app image).

Right now simplest ASP.NET **application image** would look like this:

```
FROM microsoft/aspnet
COPY . /app
WORKDIR /app
RUN kpm restore
CMD ["k", "kestrel"]
```

With the help of ONBUILD directives, we can simplify this Dockerfile as short as this:

```
FROM microsoft/aspnet:onbuild
```

and that would be the only Dockerfile to build an ASP.NET app image and ship it to the Docker host. Relevant work is suggested by @friism (#11) and @vlesierse (#7) in the pull requests. Therefore I am starting a discussion about possible risks and implementation details.

### Risks of breaking users

The dockerfile written above is almost the same for all web applications. 

1. It copies app to `/app` (or `/usr/src/app` open to debase, but ok)
2. Goes to `/app` and runs `kpm restore` (always needed?)
3. Runs `k` executable with `kestrel` parameter.

Since onbuild image will bring quite some easiness, if we happen to change the path (i.e. `/app`) and people take dependency on that, we will be breaking the apps built with the -onbuild image.

Also, if `kpm restore` takes any parameter (e.g. feed), unfortunately we won't be able to pass that to the `ONBUILD RUN kpm restore`. So it will stay as bare `kpm restore`. Does this handle the 90% use case?

It's ok to break users now since this image is still in preview, however in the long term this will not be feasible, therefore we should be coming up with a solution that can stabilize and get adopted by the community over time.

## Maintenance

Along with any version (e.g. `1.0.0-beta1`) we need to maintain an -onbuild Dockerfile equivalent as well (e.g. `1.0.0-beta1-onbuild`). That's not a big cost, I have no concerns in this area. ([example](https://github.com/aspnet/aspnet-docker/pull/7/files))
## Entrypoint

Right now it appears like `k kestrel` is the de facto entrypoint for the web server containers. However I do not want to leave the `k run` (command line app) use case out of the onbuild images. The both entrypoint common in all use cases is `k` itself and the rest can be changed.

So in the onbuild image, if we specify the entrypoint as:

    ENTRYPOINT ["k"]
    CMD ["kestrel"]
*  In the simplest Dockerfile (just contains `FROM ....` above the entrypoint will be `k kestrel`.

*  If users need to override the `k` parameter in their app image, they can use: 
    FROM microsoft/aspnet
    CMD ["run"]
and the entrypoint will be overriden as `k run`.

* If users need to override the entrypoint entirely, they can use `ENTRYPOINT` directive in their app's Dockerfile.

* Passing parameters: by overriding the CMD I can pass extra parameters to the k command (e.g.`k run --param foo`) in Docker cli from an onbuild image like:

    docker run -i -t myapp run --param foo

This will result in a cmd like `["k", "run", "--param", "foo"]` which is valid.

## Tagging onbuild images

An onbuild image for a normal image will just have `-onbuild` suffix in the Docker image tag. (e.g. `microsoft/aspnet:1.0.0` will have corresponding `microsoft/aspnet:1.0.0-onbuild` image).

An ONBUILD dockerfile for a version should be stored at `version/onbuild/Dockerfile` (e.g. onbuild Dockerfile for `1.0.0/Dockerfile` should be at `1.0.0/onbuild/Dockerfile`). This will keep things organized at the root level view on the repo.

This also appears to be [the convention](https://github.com/docker-library/official-images/blob/master/library/golang).

The ONBUILD image  for `latest` image will just be tagged as `onbuild` and will be referenced as `microsoft/aspnet:onbuild`.

## Release steps

Once the PR is merged, we'll push the onbuild image for latest(`=1.0.0-beta1`) immediately and for the next version releases, ONBUILD image has to be included as a part of the version update PR. The README.md should also be updated to reflect the changes in the tags.

Once changes are merged administrators must update the automated build configuration to point `latest`/`onbuild` tags to the correct version.

## Going forward 

@vlesierse's PR #7 uses `ENTRYPOINT` and `CMD` separately, which makes sense in the description above. 

I really appreciate input from you guys on going forward. Do you see any problems with the proposal above or do you see additional issues/concerns we should be aware of? At this point iterating on @vlesierse's PR #7 looks like a better choice for me.

/cc: @davidfowl @johngossman

**Comment by friism** [comment]
@ahmetalpbalkan have you considered the topic of `project.lock.json`? Should `onbuild` one to present, or not? I don't know if the semantics are the same, but the Rails image requires one: https://registry.hub.docker.com/_/rails/

**Comment by ahmetalpbalkan** [comment]
@friism hmm no idea what that is, I couldn't figure out by looking at the rails image. What does that do?

**Comment by ahmetalpbalkan** [comment]
hmm found this https://github.com/aspnet/Home/wiki/Lock-file but I'm trying to find an example.

**Comment by friism** [comment]
@ahmetalpbalkan There's one in musicstore: https://github.com/aspnet/MusicStore/tree/master/src/MusicStore

My current thinking is that onbuild should copy it in with project.json, eg:

```
FROM aspnet:latest
ENV SRC_DIR /src
RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR
ONBUILD ADD NuGet.Config $SRC_DIR/
ONBUILD ADD project*.json $SRC_DIR/
ONBUILD RUN dnu restore
ONBUILD ADD . $SRC_DIR/
```

**Comment by ahmetalpbalkan** [comment]
@friism sounds about right.

**Comment by Eilon** [comment]
@davidfowl re: lock files

I *do* think that the lock file should be copied - the runtime uses that file to determine the exact versions of packages to load. I think it'll work without it, but you might get unexpected results. It also serves as an optimization because the entire package graph is already resolved. But Fowler will have ton confirm.

**Comment by friism** [comment]
@ahmetalpbalkan what about multiple `project.json` files? I think that one would ideally like to glob in all of them (eg. `ADD **/project*.json /src`) and then run `dnu restore`, but I don't think that's possible with Dockerfile. Maybe just limit to one project.json at a time?

**Comment by ahmetalpbalkan** [comment]
@friism you're making an assumption like I'm using ASP.NET, on the contrary I don't know much about ASP.NET at this point, so I don't know what multiple projects mean.

If it means multiple applications, then they probably should go into separate images.

If it means an executable entrypoint and bunch of other projects providing DLLs the entrypoint project depends on, then it should be a single image, however I'm not sure how a single onbuild image can handle this. 

My plan was to run PartsUnlimited sample application with this onbuild image but last time I tried it was not working on Mono for some reason (I think the feed was messed up somehow and I was getting version-related errors in restore). If you can get it working (I believe it has multiple projects, too) we can iterate on that.

Just a reminder, with this ONBUILD image, we're aiming to handle the 90% of the use cases (i.e. common case) and if it's possible at all, I would love to move further on this proposal.

**Comment by muratg** [comment]
Putting this in RC2 for now and assigning to @glennc make a decision/talk to @ahmetalpbalkan etc.
