### ISSUE TITLE
Failed to run a container from a custom docker image for ASPNET Core app

### ISSUE THREAD

**Issue by stanuku** [aspnet/aspnet-docker#192]
I generated the application with yeoman and then added a plain vanilla docker file.

```
FROM microsoft/aspnetcore
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]
EXPOSE 5000
ENTRYPOINT ["dotnet", "run"]
```
The image gets created fine on docker build, but when I run it the container exits and I see the below message on the console. 
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```
I think microsoft/aspnetcore only brings in the runtime and not the SDK ??

**However if I change the FROM to microsoft/dotnet, then the container runs fine.**

**Comment by natemcmaster** [comment]
Use `FROM microsoft/aspnetcore-build` instead. `microsoft/aspnetcore` is a runtime-only image.
