### ISSUE TITLE
App is named to app.dll instead of ${ProjectName} after publishing on Kubuntu 

### ISSUE THREAD

**Issue by DMWOO7** [aspnet/aspnet-docker#197]
I'm publishing an ASP.NET Core 1.1 application using Docker on a Kubuntu 16.04 host, which is based on the same version of the Ubuntu LTS version. Normally, when I ran `dotnet publish`, a DLL is created, which has the same name of the project. So when the project is called _MyProject_, I can start the published app using `dotnet MyApp.dll`. 

But that's not working. I found out that a DLL is created which is called `app.dll` instead of `MyProject.dll`, which I never saw before. [The yo generator-aspnetcore-spa](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/) was used to generate the project. 

When I ran `dotnet publish` on the host system without docker, its worked like expected. In both cases, I have ASP.NET Core 1.1.0 with 1.0.0-preview2-1-003177 .NET Core Shared Framework. 

## Dockerfile

```
FROM netcore-nodejs:0.1
WORKDIR /app

COPY project.json .
RUN dotnet restore
COPY . /app

RUN dotnet publish --output /app/published
WORKDIR /app/published
RUN ls -lh

ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000/tcp
CMD dotnet app.dll
```

## Dockerfile from netcore-nodejs

```
FROM microsoft/aspnetcore-build:1.1.0-projectjson

RUN apt-get update
RUN wget -qO - https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y build-essential nodejs
```

## Host
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

```
$ docker --version
Docker version 1.13.0, build 49bf474
```

**Comment by natemcmaster** [comment]
By default, project.json names your assembly after the folder name containing project.json, which in your case is "app". You can change this by setting "buildOptions > outputName". cref https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#buildoptions

**Comment by DMWOO7** [comment]
Thanks, that explains the situation. Since I normally had the application in a folder called like the project, I thought .NET Core is using the name of the project. I think that would be a better idea, especially since ASP.NET Core is docker-compatible. There it's common to deploy to a general folder like `/app`, where this behaviour can cause confusion. 

But since this isn't a real bug, I close the issue.
