### ISSUE TITLE
Drop support for the project.json images

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#200]
At some point in the near future, we will stop supporting the project.json images. When we do that, we can remove Dockerfiles and simplify test code.

cref #199

**Comment by glennc** [comment]
Seems reasonable to throw this into the 2.0 milestone and do it when it makes sense.

**Comment by natemcmaster** [comment]
Along with this, we can drop the '-msbuild' suffix from our tags.

**Comment by natemcmaster** [comment]
👀  https://github.com/dotnet/dotnet-docker/issues/204
