### ISSUE TITLE
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:

### ISSUE THREAD

**Issue by ferpegaplain** [aspnet/aspnet-docker#201]
Hello,

Why nobody is answering here: 
https://hub.docker.com/r/microsoft/aspnetcore/

about the problem when you try to run (externally -command line-) a newly created ASPNET.Core application (with visual studio) and added Docker support to it?

When you try to run it:
`docker run xxxx/myapp`

it shows this error and stop: 
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Regards.

**Comment by natemcmaster** [comment]
@ferpegaplain Docker Hub doesn't provide notifications to us when people make comments. Fortunately, you've arrived at the right place to ask questions. Sorry for any delay.

As explained in the description, the `microsoft/aspnetcore` image only contains the runtime, not the SDK. Use the [`microsoft/aspnetcore-build` image](https://hub.docker.com/r/microsoft/aspnetcore-build/) instead if you want to build inside your container.

**Comment by ferpegaplain** [comment]
Thanks @natemcmaster for your answer.

I was only looking for execute a simply 'aspnetcore' app but outside Visual Studio and with usual docker commands.  And also build & release this same container inside Visual Studio Online (VSO) with docker plugin installed.

But I have not had luck for the moment.

**Comment by natemcmaster** [comment]
I'm not familiar with VSO's docker plugin, but here are examples of how to use these images. Feel free to continue discussion if you have more questions.

[Example usage of microsoft/aspnetcore-build](https://github.com/aspnet/aspnet-docker/blob/708206d68ffa1b67e4a1fe329de42c72fd8b0b0a/1.1/jessie/build-msbuild/README.md#example-usage)
[Example usage of microsoft/aspnetcore](https://github.com/aspnet/aspnet-docker/blob/708206d68ffa1b67e4a1fe329de42c72fd8b0b0a/1.1/jessie/runtime/README.md#how-to-use-this-image)

**Comment by ferpegaplain** [comment]
Ok @natemcmaster with the 'microsoft/aspnetcore-build'  image I am trying to execute (run) a new/unmodified AspNetCore project from outside Visual Studio (I have forgot the VSO stuff for the moment).

I am using:
Windows 10 + **Mintt/bash** (from last Git for Windows installation)

After a lot of tries  looking for translate pure bash commands to mintt a finish with this command line:

Take a look at the double slash at starts of every path:
` winpty docker run -it -v //$(PWD)/src/DockerAspnetApp1:/app --workdir //app microsoft/aspnetcore-build bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
`

Ok, but when I try to execute this (all files are copied to /app folder inside the container), but dotnet commands gives me this error:

> /app/DockerAspNetApp1.xproj(8,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists
>  on disk.

Anyway, if somebody  think this is not the place to solve this kind of problems, please let me know.

Thanks.

**Comment by natemcmaster** [comment]
It looks like you are trying to build a project.json project. When you pull `microsoft/aspnetcore-build` it will give you the "latest" tag which only supports the new MSBuild SDK for .NET Core. To build project.json, specify `microsoft/aspnetcore-build:1.1.0-projectjson` instead. See https://github.com/aspnet/Announcements/issues/219.
