### ISSUE TITLE
Create tag-details.md to describe in more depth the various tags

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#204]
## Benefits of adding tag-details.md
•	Help provide more info on the breakdown of what is in each Docker image
•	Help explain the naming conventions behind tag schema
•	Other repos use this solution to help new users understand their repo

Related to https://github.com/dotnet/dotnet-docker/issues/212

**Comment by natemcmaster** [comment]
I'm assuming this file would look like https://github.com/docker-library/repo-info/blob/master/repos/debian/tag-details.md, right? How do you plan to generate these files for microsoft/dotnet?

**Comment by natemcmaster** [comment]
@MichaelSimons is this something we would do for 1.x and 2.0 images once https://github.com/dotnet/dotnet-docker/issues/212 is resolved?

**Comment by MichaelSimons** [comment]
Yes it is.  My goal is for it to be very little work to enable it once the ImageBuilder tool has support.

**Comment by natemcmaster** [comment]
Closing as this is appears to be low priority and we have no plans to implement this at the time.
