### ISSUE TITLE
Latest 1.1 image: appsettings environment files casing issue

### ISSUE THREAD

**Issue by billpratt** [aspnet/aspnet-docker#208]
Dev app settings file: appsettings.development.json
ASPNETCORE_ENVIRONMENT=Development

Locally on both Windows and macOS, the casing between the environment specific appsettings filename, ie appsettings.development.json, and the environment variable ASPNETCORE_ENVIRONMENT was case-insensitive. This was also true to prior versions of the 1.1 image. With the latest 1.1 image, if ASPNETCORE_ENVIRONMENT=Development and the appsettings file has a lowercase 'development', dotnet does not use the Development environment appsettings. If I change the file to appsettings.Development.json, then the image works as expected.

Was this intentional? I believe that the case insensitivity should match both local and in the docker images. Please let me know if you need more info. I can share a sample project showing this if you need.

**Comment by natemcmaster** [comment]
Our images never set ASPNETCORE_ENVIRONMENT. Can you share a dockerfile or docker-compose.yml file?

cc @Tratcher - I don't believe ASP.NET Core hosting has ever attempted to auto-correct case differences in env and file names.

**Comment by Tratcher** [comment]
Case sensitivity is a feature of the underlying file systems and ASP.NET does not attempt to second-guess / compensate for it. E.g. File names are case insensitive on Windows and case sensitive on Mac/Linux.

**Comment by billpratt** [comment]
That makes sense. I wasn't implying that the images set the environment but rather the case sensitivity differences I was seeing when setting the environment variable. I'll close this ticket.
