### ISSUE TITLE
how to update node to current version base this image

### ISSUE THREAD

**Issue by geminiyellow** [aspnet/aspnet-docker#210]
this image use the LTS node version, that is good. 
but i want to use the newest node version. 
anybody can tell me how to use it?

**Comment by natemcmaster** [comment]
Are you asking how to use node 7.7 in the image?

**Comment by geminiyellow** [comment]
yep, current version is `7.7.2`

**Comment by natemcmaster** [comment]
As you already noticed, our images have Node LTS in them. You can always build your own image by copying our Dockerfile and updating it to Node 7. 

Unless we have a compelling reason to change this, we plan keep using LTS in our images.

That said, are there features of Node 7 that you require for building ASP.NET Core apps?

**Comment by geminiyellow** [comment]
@natemcmaster ok, thank you, got it.

> That said, are there features of Node 7 that you require for building ASP.NET Core apps?

no, just want to use the nightly build.
