### ISSUE TITLE
asp.net core project fails to build

### ISSUE THREAD

**Issue by opencloudcode** [aspnet/aspnet-docker#212]
Can someone help on what going on here?  

The project is on my github page 
https://github.com/opencloudcode/aspnetcoreangular2docker

My goal is just to have the application running on a container. I just want to have a way where I can just do a:
"docker run -d -p 8000:80  shahel/aspnetcoreangular2docker"

I did a "docker run -it shahel/aspnetcoreangular2docker" and then "dotnet restore" and got this error:

 root@79cf79199676:/app# dotnet restore
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

## Steps to reproduce the issue
FROM microsoft/aspnetcore-build
 WORKDIR /app

 COPY *.csproj .
 RUN dotnet restore

 COPY . .
RUN dotnet publish /app/aspnetcoreangular2.csproj

## Expected behavior
I want it to build without having to create a local dockerfile in my side

## Actual behavior
docker build -t shahel/aspnetcoreangular2docker -f Dockerfile.build
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by natemcmaster** [comment]
You will need to add file name to any dotnet args. e.g. `dotnet restore aspnetcoreangular2.csproj`. When a file is not specified, MSBuild looks for anything that matches \*.sln or \*.\*proj. MSBuild is finding both your .csproj and .dcproj file.

I'm closing as there is nothing the docker image can change to fix this. MSBuild has behaved this way for about 10 years and is very unlikely that will change. I realize that the .dcproj extension is the default used by VS Docker tooling. I've emailed internally about changing the file extension to avoid this common error. cc @dazhao-msft @stevelasker @glennc

**Comment by debCode** [comment]
Download And Install Microsoft Build Tools with your required version and close your CLI PowerShell.
Then again rerun the PowerShell and try dotnet build.
https://www.microsoft.com/en-us/download/details.aspx?id=48159
that contains Microsoft Build Tools
