### ISSUE TITLE
Creating a Debug image

### ISSUE THREAD

**Issue by herecydev** [aspnet/aspnet-docker#214]
Finding information on vsdbg is very difficult but I believe it's the correct tool for debugging remote .NET core code. In my situation I'm running a .NET core app in a docker container which I would then like to attach to. My dockerfile looks like this:

```
FROM microsoft/aspnetcore:1.1.1

WORKDIR /vsdbg
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        unzip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app
// More normal stuff here
```

It would great to have an official image that includes debugging support as this currently massively inflates the build times.

**Comment by natemcmaster** [comment]
@herecydev did you try this? https://docs.microsoft.com/en-us/dotnet/core/docker/visual-studio-tools-for-docker#debugging

**Comment by tanaka-takayoshi** [comment]
+1 for @herecydev 
@herecydev can I confirm Visual Studio docker support is only available for not "remote debugging" but "debugging"? I mean it only supports debugging docker image running on the same Windows machine where Visual Studio is running. It doesn't support remote debugging to docker running on the remote host.

I prefer more general remote debugging support for docker image. Once official docker image has unzip command, we can follow [this intruction](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio).

**Comment by s130059660** [comment]
@natemcmaster:
In the documentation, Microsoft calls SDK images debug images. Yet, these images lack the debugging binaries "vsdbg ".

The SDK image is already big and adding the debugging binaries will just add few megs to it.

Please consider a debugging image. Or even better, make the SDK images debug-able.

**Comment by natemcmaster** [comment]
We discussed as a team. We don't have any plans to do this. We don't want to add additional bloat to the docker containers as the vsdbg binaries are not something we would expect to be used in a production environment. And as pointed out above, users can add this to their image with just a few lines in the Dockerfile.

However, debugging is an important scenario, so we plan to add instructions on setting up vsdbg to samples in our documentation. See https://github.com/aspnet/Docs/issues/5450

**Comment by tanaka-takayoshi** [comment]
I understand the production Docker image should not have extra tools like vsdbg. However, it's not so good updating Dockerfile is required to install vsdbg. It means some libraries dependencies in the Docker image could change between the production image and the debug image. It's desirable we can add vsdbg without changing Docker image.

**Comment by natemcmaster** [comment]
Sorry, this isn't something we want to support. If you really need to ensure vsdbg is always in your image, I'd recommend creating your own. With a little bit of dockerfile and Docker Hub automated builds, it shouldn't be too hard to maintain this on your own.

**Comment by tanaka-takayoshi** [comment]
I appreciate your explanation. Now I feel worthy enough to create my own image. Thanks!
