### ISSUE TITLE
Use xplat powershell

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#218]
We can use xplat powershell to avoid maintaining two identical scripts in bash and powershell.

**Comment by natemcmaster** [comment]
Looks like https://github.com/aspnet/aspnet-docker/pull/240 will resolve this, right @MichaelSimons ?

**Comment by MichaelSimons** [comment]
@natemcmaster, #240 solves half of the problem - the test script.  I am not consolidating the CI build scripts at this time mainly because I have some other work I need to get done.  The driving force behind #240 is to address #236 and I took the opportunity to consolidate the test scripts.

**Comment by natemcmaster** [comment]
Ok, thanks

**Comment by natemcmaster** [comment]
Fixed in #252.
