### ISSUE TITLE
Add image to allow building against a full .NET framework

### ISSUE THREAD

**Issue by dealdiane** [aspnet/aspnet-docker#227]
Are there plans to add an image for aspnetcore-build that's based on the full framework?

**Comment by natemcmaster** [comment]
An image already exists, but it's Windows-only. Use `microsoft/aspnet`. See https://github.com/microsoft/aspnet-docker and https://hub.docker.com/r/microsoft/aspnet/ for more details.

**Comment by dealdiane** [comment]
Correct me if I'm wrong but that image is for running a website not for when you want to build an aspnet core app against a full framework.

**Comment by natemcmaster** [comment]
You're correct, it is for running on .NET Framework, not building. We do not have plans to support building for .NET Framework in a container. If you really need this, please open the issue on https://github.com/microsoft/aspnet-docker. This repo is dedicated to .NET Core-only images.
