### ISSUE TITLE
unable to pull the image from ps

### ISSUE THREAD

**Issue by SrivatsaMarichi** [aspnet/aspnet-docker#228]
Hi, 

I am building aspnet webapp with docker using VS 2017 RTM. I did a "docker pull microsoft/aspnet". The docker tried to pull the image, but it restarted  to download again and again of the size 4gigs. Can anyone help me out here?

![2017-04-25_1827](https://cloud.githubusercontent.com/assets/13433045/25386477/222336f0-29e5-11e7-8f13-f78db76453a6.png)

Thanks,
Srivatsa

**Comment by natemcmaster** [comment]
Are you trying to build an ASP.NET **Core** app? If so, use `microsoft/aspnetcore` or `microsoft/aspnetcore-build`.

**Comment by SrivatsaMarichi** [comment]
No I'm trying to build aspnet. Not the .Netcore.

**Comment by natemcmaster** [comment]
Ok. You'll have to go to https://github.com/microsoft/aspnet-docker then for help with  `microsoft/aspnet`. Sorry to bounce you to a new GitHub repository. We're aware that Docker Hub says to go here. Unfortunately, we don't have a good way to update the link there. See https://github.com/Microsoft/aspnet-docker/issues/2

**Comment by muratg** [comment]
No action on this repo, so closing.
