### ISSUE TITLE
Proposal: CI for ASP.NET Docker image builds

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#23]
Every now and then, we worry if the image produced by the merged Dockerfile works correctly or not. For now, the verification is done manually. It is tedious, error-prone and it goes as far as running the sample HelloWeb/HelloMvc apps inside the container, then heading over browser to see if it works.

I hereby propose **using CircleCI** to test these Dockerfiles. Actually **I have prototyped this** and can show what it will look like. (Head over to https://github.com/ahmetalpbalkan/aspnet-docker-integration-tests to see).

With this, we can have a nice [![Build Status](https://travis-ci.org/ahmetalpbalkan/aspnet-docker-integration-tests.svg?branch=master)](https://travis-ci.org/ahmetalpbalkan/aspnet-docker-integration-tests) icon for the repo as well as the PRs sent without manually testing the Dockerfile locally. :bowtie: 

### Docker host setup

1. We need some Docker host to run the tests on.
     * Travis machines cannot run a docker daemon (linux <2.6, required: >3.8).
     * We can have a dedicated VM on Azure as a docker host. (that's what I did) In order to secure the instance, we need to use some auth mechanism.
         * For now I can hide the docker host's URL in a secret environment variable DOCKER_HOST, however a simple pull request that executes `env` in the CI code will reveal that.
         * There's no way to auth to docker with ENV vars or something like that as of now. The only auth mechanism is to have 3 certs placed on the CI machine.
         * For now I'm using a Docker instance (auth disabled) to run the tests. If some attacker scans Azure IP ranges and ports for Docker endpoints, they can easily find ours. There's no harm except they can use our instance to run their unwanted workloads. :smile:
         * Upcoming docker version with SSH key authentication may address this because travis tests have support for assigned ssh keys by default.
2. This docker host must be up all the time. Where to host is still a question. I am volunteering to manage it, using my team's subscription.

### Repo setup

1. This repo should host the CI scripts (one or two files, will go under `ci/`, or something like that) and `.travis.yml` file (has to be on the project root).
2. Somebody with admin permissions on this repo will need to go to travis-ci.org to set up the CI for this repo and trigger a build to see if it works. I can provide hands on help offline.
3. If everything goes well, we can add a '_build:passing_' badge to the repo and all the PRs will get automatically built and verified.

### Execution

As you can see in the [.travis.yml prototype](https://github.com/ahmetalpbalkan/aspnet-docker-integration-tests/blob/master/.travis.yml) we will run tests for HelloWeb, HelloMvc in parallel.

On each Travis box, docker client will be downloaded, then [ci/run-sample-kestrel.sh](https://github.com/ahmetalpbalkan/aspnet-docker-integration-tests/blob/96795f681186c4240ddafc787c6bd929cd6b7010/ci/run-sample-kestrel.sh) will be executed.

This script essentially clones the @aspnet/aspnet-Home repo, injects a Dockerfile to the sample app, builds app image, creates the Docker container with the image, verifies connectivity over `curl` and cleans up resources (container+image).

You can see a sample successful test pass here: https://travis-ci.org/ahmetalpbalkan/aspnet-docker-integration-tests ([job 1 for `HelloWeb`](https://travis-ci.org/ahmetalpbalkan/aspnet-docker-integration-tests/jobs/45884626) and [job 2 for `HelloMvc`](https://travis-ci.org/ahmetalpbalkan/aspnet-docker-integration-tests/jobs/45884627)).

Cleanup is always done (best effort guaranteed by Travis) on the instance, so I don't expect usage on the dedicated Docker Host accumulate over time and run out of disk etc.

### Considerations

* For now, the tests just use `FROM microsoft/aspnet`. Since CI triggers when commit or PR occurs, that image won't be ready for another 3-10 (or more) minutes. So we should be cloning this (aspnet-docker) repo and build that image in the CI script as well. That'll more than double the test execution time.
* We should find a better way to authenticate to Docker instance. An insecured (auth-lesss) Docker instance won't last long. :confused:
* Sending a HTTP request to HelloWeb/HelloMvc doesn't exactly test everything (it helps, though). We should find a better way to run some extensive test suite on the Docker image.
* **Race conditions will exist** in this one dedicated VM setup. If you look at the prototype, HelloWeb always runs on port 80 of the VM. If we randomly assign some port (e.g. using $RANDOM), then we need to open up that port on Azure VM as well and this cannot be done on the fly and takes quite some time, and guess what, can fail :weary:). If we can assume CI tests will finish before another git push (to the repo or to the same PR) comes, it's safe. But I'm pretty sure we'll run into this issue very quickly. Not sure how to solve this problem. If we could run docker daemon in travis box, that wouldn't be a concern.
* ASP.NET project is open source and Travis CI is free for open source projects. I don't think there would be any legal issues.

### Conclusion

This will obviously help to accelerate the process. If we sort out the logistics (e.g. Docker host and its authentication problem on Travis, race conditions), this may come really handy while signing off on PRs. **Ideas?**

/cc: @Eilon @muojp @vlesierse @friism @paulmey @davidfowl @danroth27

**Comment by friism** [comment]
Travis is awesome, but have you looked at CircleCI? I think they have [native Docker support](https://circleci.com/docs/docker).

**Comment by ahmetalpbalkan** [comment]
@friism, great suggestion. :pray:   I will take a look and see if it can do everything we need. This pretty much addresses all the problems I currently have.

**Comment by vlesierse** [comment]
Great idea! This could really help for stable releases of Docker images.

**Comment by ahmetalpbalkan** [comment]
@friism okay, good news and bad news. https://github.com/ahmetalpbalkan/aspnet-docker-integration-tests-circleci

**Good news:** code is complete! CircleCI solves all our problems above. :clap:  [[link]](https://circleci.com/gh/ahmetalpbalkan/aspnet-docker-integration-tests-circleci) I wrote scripts to build all tags and run all apps on it! 

We can do all that serially using 1 worker instance (free) or we can wrote some code to parallelize. (circleci has no easy parallelization as travis has).

**Bad news:** curl cannot connect to the container to verify the app, it gets "Recv failure: Connection reset by peer". I chatted with CircleCI support (@gordonsyme) and he helped me a great deal. The problem is, sometimes `k kestrel` starts but it does not listen the port... This problem is happening silently. If I manually run `k kestrel` by entering the container with lxc-attach, server just works fine.

So it is time to fix the keyboard/TTY dependency from kestrel (or Microsoft.Framework.ApplicationHost, wherever that is). Currently, asp.net self-hosting servers listen to Ctrl+C to terminate. It should not be like that. This caused us trouble in the past (i.e. if you execute `docker run` without `-t` (attach pseudo-tty) switch, server process dies after a minute or so).

I ran the server manually with `strace` and I still have no idea why this happens. ([output](https://gist.github.com/ahmetalpbalkan/081948c84ec06ea66477)). I will try running the ENTRYPOINT with `strace k kestrel` and see what's going on regarding the port listen... 

Meanwhile, we should definitely fix that server and have something like rest of the world has (e.g. python [`httpd.serve_forever`](https://docs.python.org/2/library/basehttpserver.html) that doesn't use Console.Read :smile: ) I appreciate any help doing that!

**Comment by ahmetalpbalkan** [comment]
Okay, found the evil line: https://github.com/aspnet/Hosting/blob/d9237b3a08033aa00f049645ea2f6a3bfcd91fd8/src/Microsoft.AspNet.Hosting/Program.cs#L79

```cs
    [Microsoft.AspNet.Hosting/Program.cs]
    [...]
    var ignored = Task.Run(() =>
    {
        Console.WriteLine("Started");
        Console.ReadLine();
        appShutdownService.RequestShutdown();
    });
```

This should be changed, but I'm not sure how .NET app can handle SIGTERM here and request the shutdown. We need to find something else to block on and yet still supports Ctrl+C. Any ideas? @Tratcher @davidfowl @Eilon

**Comment by friism** [comment]
@ahmetalpbalkan yeah, that problem is super annoying - @davidfowl says it's getting fixed.

In the Heroku buildpack, I do `sleep 100d | start Kestrel`: https://github.com/friism/heroku-buildpack-mono/blob/aspnet-vnext/bin/compile#L111

Piping output of sleep means that the runner doesn't fall over.

In the past, I also used other hacks like starting the thing inside a detached screen session: https://github.com/friism/Home/blob/master/Dockerfile#L7

... but I don't really recommend that.

**Comment by friism** [comment]
@ahmetalpbalkan also, to debug problems like this I recommend starting with `KRE_TRACE=1`, then you can see the runner getting "Shutdown requested" and whatnot.

**Comment by ahmetalpbalkan** [comment]
@friism thanks for help, I used the `sleep` piping hack and KRE_TRACE=1 now and fixed the build!  https://circleci.com/gh/ahmetalpbalkan/aspnet-docker-integration-tests-circleci/34

I guess we can start integrating this and connect to CircleCI. I'm not really good at bash scripting, so I'll start with sending a PR with these and we can move from there I guess.

**Comment by ahmetalpbalkan** [comment]
moving on at #24.
