### ISSUE TITLE
decimal ToString("C") output difference when running on aspnet core Docker images

### ISSUE THREAD

**Issue by billpratt** [aspnet/aspnet-docker#232]
I have an app that uses the decimal ToString(String, IFormatProvider) method to get currency formatted string for a specific culture ie $7.99 for en-US. I have noticed a slight difference for the culture "da-dk" on what is returned when running on the microsoft/aspnetcore and microsoft/aspnetcore-build Docker images. I originally submitted this [issue on the dotnet/corefx repo](https://github.com/dotnet/corefx/issues/19318) but they said they "depend on the OS for the underlying globalization data". 

Sample code:
```
Console.WriteLine(9.99m.ToString("C", new CultureInfo("da-dk")));
```

On Windows and OSX, the output is: **9,99 kr.**

On aspnet Docker images, the output is missing the period: **9,99 kr**

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
Run this line in a console app on OSX, Windows and the Docker images
```
Console.WriteLine(9.99m.ToString("C", new CultureInfo("da-dk")));
```

## Expected behavior
Output should be correct currency format

## Actual behavior
Linux platform has incorrect globalization for currency DKK (da-dk)

## Additional information (e.g. issue happens only occasionally)
Happens consistently

## Output of `dotnet --info`

OSX:
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.3
```

Windows:
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

**Comment by natemcmaster** [comment]
@billpratt  try setting the locale inside the docker image. Here's a good post on that. http://jaredmarkell.com/docker-and-locales/

Here's the output of `locale` inside the `microsoft/aspnetcore` in Docker.
```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by billpratt** [comment]
@natemcmaster Im not sure that will work for my case. My app must support currency formatting for multiple cultures. It takes in a culture code like "en-US", "da-DK", "es-ES", etc and returns the formatted currency for that culture.

**Comment by billpratt** [comment]
When I run similar tests using the Docker image ubuntu:16.04 I am getting more accurate results. I will continue to investigate with the above suggestion.

**Comment by natemcmaster** [comment]
@billpratt where you able to figure out the cause of the issue?

**Comment by billpratt** [comment]
I was not able to and it wasn't a huge concern for our needs so I moved on. I'll close the issue
