### ISSUE TITLE
dotnet publish fails when building in container

### ISSUE THREAD

**Issue by carsten-j** [aspnet/aspnet-docker#237]
For a out of the box created ASP core 2.0 web api I cannot build the app in the aspnetcore-build container. I get the following error message:
```
Step 8/8 : RUN dotnet publish --output /out --configuration Release
 ---> Running in 513b448306ea
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/2.0.0-preview1-005977/Microsoft.Common.CurrentVersion.targets(2867,5): error MSB3552: Resource file "**/*.resx" cannot be found. [/myApp.csproj]
The command '/bin/sh -c dotnet publish --output /out --configuration Release' returned a non-zero code: 1
```

## Steps to reproduce the issue
1. Clone the repository https://github.com/carsten-j/myApp
2. Run docker build -t myapp ,

## Expected behavior
No error message from dotnet publish

## Actual behavior
The error listed above

## Additional information (e.g. issue happens only occasionally)
This does not happen on my local machine.

## Output of `dotnet --info`

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by natemcmaster** [comment]
We've had some weird errors like this one caused by working from `/`. Can you try adding this as the second-line in your Dockerfile?

```Dockerfile
WORKDIR /app
```

**Comment by carsten-j** [comment]
That solved the problem. Thanks.

**Comment by natemcmaster** [comment]
👍  I'm going to add this to our docs and readme to make this more clear.
