### ISSUE TITLE
Remove node from aspnetcore-build images

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#239]
[Multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) -- new feature coming in Docker 17.05 (currently Edge) -- should make it easier for users to compose a build from multiple images in a single dockerfile. We suspect this will make it possible for users to easily compose together `microsoft/aspnetcore-build` and `node` images to build web apps.

Some areas of work to make this smooth:

 - timeline. When will edge become stable? Will it land before 2.0.0 release. We will likely keep node in the 1.x versions to preserve compatibility, but if the feature lands in 2.0.0 we may want to add this before we ship the RTM images.
 - `dotnet new web` and VS templates. Which of these rely on Node to build?
 - VS Docker Tooling
 - docs. Lots of updates required to make this work well.

Thoughts? @MichaelSimons @glennc

**Comment by g0t4** [comment]
I see at least two use cases:
- *proj (MSBuild) files that just use the .NET Core SDK
- *proj files that also shell out to other tools, i.e. [SpaTemplates](https://github.com/aspnet/JavaScriptServices/blob/dev/templates/VueSpa/VueSpa.csproj#L31-L33 )

## *proj only uses .NET Core SDK

Here a multi-stage build would be the most flexible and sane approach to have tight control over each build tool and version. There's no need for simultaneously using different build tools. 

One can use `microsoft/dotnet:2-sdk` for multi-stage builds but it probably makes sense to have `microsoft/aspnetcore:2-sdk` for ASP.NET Core SDK optimizations like [warmup for the NuGet package cache](https://github.com/aspnet/aspnet-docker/blob/master/2.0/jessie/sdk/Dockerfile#L42-L45). Future optimizations for development could be put into this `2-sdk` image. 

If there is going to be an optimized ASP.NET Core SDK image, I would prefer `microsoft/aspnetcore:2-sdk` to mirror the tag conventions in `microsoft/dotnet` so we'd have `2-runtime` and `2-sdk` in both repositories. Tagging consistency would markedly simplify image discovery. App-model alone would dictate which repository to use. Then it's a matter of component (runtime/sdk), runtime version and OS all within a single repository. And if we can align SDK and runtime versions well that's one less complication.

Also, perhaps multi-stage builds can obviate the need for `aspnetcore-build CI builds` that contain multiple runtimes. Just swap in different SDK images with each runtime needed?

## *proj shells out to other tools 

In this case I could see an argument to keep the monolithic `aspnetcore-build` image with reasonable default versions of common tools. Or at least leave some guidance for how people can build their own monolithic image. 

If the multi-tool image idea is going away, I would like to see this repo deprecated beyond 1.x and not try to use this repo for say an optimized ASP.NET Core SDK image. 

I could also see supporting both multi-stage builds and multi-tool images, maybe just for 2.x to give people time to transition. And, we could keep the guidance/documentation indefinitely.

## Nighty images

Whatever is decided here, it would be nice to synchronize with `-nightly` repositories. Right now we don't have `aspnetcore-nightly` but we do have `aspnetcore-build-nightly` and `dotnet-nightly`. Or, I wouldn't mind seeing nightly tags in the `dotnet` and `aspnetcore` repos for 2.x+.

**Comment by natemcmaster** [comment]
Closing for now as we have no plans to remove Node from current images. This would be a major breaking change.
