### ISSUE TITLE
Move image to debian stretch.

### ISSUE THREAD

**Issue by aensidhe** [aspnet/aspnet-docker#246]
Debian stretch will be [released at June, 17](https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html). I would suggest to move aspnetcore images to debian stretch, because it has newer (and safer) packages like graphicsmagick 1.3.25, not 1.3.20, etc.

Also, it would be new LTS release of Debian.

**Comment by natemcmaster** [comment]
The aspnetcore images use `microsoft/dotnet` images as their base. I'd suggest opening this request on https://github.com/dotnet/dotnet-docker.

**Comment by aensidhe** [comment]
[Done](https://github.com/dotnet/dotnet-docker/issues/250), thank you.
