### ISSUE TITLE
Windows legs of the official builds are timing out occassionally

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#259]
https://devdiv.visualstudio.com/DevDiv/_build?tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiI1ODI2NCIsIlNUeXBlIjoiUEVSIiwiUmVjaXAiOjEsIl94Y2kiOnsiTklEIjoxMzE2NTAwNCwiTVJlY2lwIjoibTA9MSAiLCJBY3QiOiI4ODVjYzBiMy1kMmQ3LTRiODYtODQ0Ny0zY2JiYzlkN2VmYTQiLCJmZiI6IkNHRCJ9fQ%3D%3D&buildId=833547

These builds are horrifically slow!  The timeout is already set to 90 minutes.

Recommended actions
- [ ] increase timeout immediately as a temporary workaround
- [x] contact DDIT about performance of the lab machines
- [ ] break apart the Windows build leg.  We could potentially have a leg for each version (e.g. 1.0, 1.1, and 2.0).

**Comment by natemcmaster** [comment]
What would be the best way to split the Windows build in pipebuild? I've already split the build in AppVeyor.yml because the nanoserver runs so slow

**Comment by MichaelSimons** [comment]
1. Fix https://github.com/dotnet/docker-tools/issues/24 so that image-builder can build a subset of the images (e.g just the 1.0 Dockerfiles).
2. Parameterize the Windows build definition to take in the folder to build.  Then pass the parameter to image-builder.
3. Modify the https://github.com/aspnet/aspnet-docker/blob/master/build-pipeline/pipeline.json to invoke the windows build definition once for each of the folders to build (e.g. 1.0, 1.1, and 2.0)

**Comment by MichaelSimons** [comment]
I did discover Windows Defender wasn't configured optimally.  I got DDIT to make a tweak to the machine configuration therefore I am going to hold off on merging #260 for the time being.  I am still recommending that the Windows build gets broken into smaller legs.
