### ISSUE TITLE
Create 2.0.0 docker images

### ISSUE THREAD

**Issue by muratg** [aspnet/aspnet-docker#262]
This is in 2.0.0 milestone, but it'll be done after everything else.

**Comment by natemcmaster** [comment]
Nightly builds are in sync with the latest dotnet-CLI. As they update, we'll rev the dev branch until we have final builds of the runtime.

**Comment by natemcmaster** [comment]
Blocked on https://github.com/Microsoft/msbuild/issues/2273

**Comment by natemcmaster** [comment]
https://github.com/aspnet/aspnet-docker/pull/278 and https://github.com/aspnet/aspnet-docker/pull/277
