### ISSUE TITLE
Container is killed after a few minutes with traps: dotnet[25812] general protection ip:7fd856cd9532 sp:7fd8514761e0 error:0 in libc-2.19.so[7fd856ca3000+1a1000]

### ISSUE THREAD

**Issue by kalib** [aspnet/aspnet-docker#263]
I can build and create my docker image using `FROM microsoft/aspnetcore:1.1` as a base image.
I can then transfer my image to AWS ECR when I create a new linux instance (CentOS 7) and install docker, I can pull my image from ECR and start my container on this instance. My dotnet application works fine for a few minutes (around 40) and gets terminated. On the instance (host), I can check dmesg and I always find the following error after my container is killed:

traps: dotnet[25812] general protection ip:7fd856cd9532 sp:7fd8514761e0 error:0 in libc-2.19.so[7fd856ca3000+1a1000]

So I start again my container with: docker run -d -p 80:80 148355502729.dkr.ecr.us-west-2.amazonaws.com/myapplication

But, again, after a few minutes, it dies and I receive that error on dmesg.

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1. My Dockerfile:
FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-./obj/Docker/publish} .
ENTRYPOINT ["dotnet", "MyApplication.dll"]

## Expected behavior
The container should stay alive, until I decide to stop it.. but it runs for a few minutes and it dies.

## Additional information (e.g. issue happens only occasionally)
I tried this with Centos 7 host, also with Amazon Linux host.
Docker version 17.06.0-ce, build 02c1d87
Base image: microsoft/aspnetcore:1.1 (got it a few days ago)

## Output of `dotnet --info`

I don't have dotnet installed on the host. I believe I don't need it, right?! Since the dotnet application is running inside the container itself, which uses microsoft/aspnetcore:1.1 image.

## Output of `docker info`

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.2MiB
Name: ip-10-11-11-251
ID: TKRR:JTP5:S53Q:X42L:PHZT:QKL5:X5ZJ:II33:GJ73:QF5N:LTWV:DQUN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

## More logs that I get with `dmesg` on the host:

```
[  107.753490] device vethf415942 entered promiscuous mode
[  107.757527] IPv6: ADDRCONF(NETDEV_UP): vethf415942: link is not ready
[  107.760175] docker0: port 1(vethf415942) entered forwarding state
[  107.762818] docker0: port 1(vethf415942) entered forwarding state
[  107.765885] docker0: port 1(vethf415942) entered disabled state
[  107.888069] IPv6: ADDRCONF(NETDEV_CHANGE): vethf415942: link becomes ready
[  107.891247] docker0: port 1(vethf415942) entered forwarding state
[  107.894000] docker0: port 1(vethf415942) entered forwarding state
[  107.900414] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[  122.912117] docker0: port 1(vethf415942) entered forwarding state
[ 2939.616974] traps: dotnet[9520] general protection ip:7efe99b6b532 sp:7efe858ac1e0 error:0 in libc-2.19.so[7efe99b35000+1a1000]
[ 2941.707184] docker0: port 1(vethf415942) entered disabled state
[ 2941.716226] docker0: port 1(vethf415942) entered disabled state
[ 2941.719670] device vethf415942 left promiscuous mode
[ 2941.722311] docker0: port 1(vethf415942) entered disabled state
[ 3986.036898] device veth00ed0fe entered promiscuous mode
[ 3986.044711] IPv6: ADDRCONF(NETDEV_UP): veth00ed0fe: link is not ready
[ 3986.047400] docker0: port 1(veth00ed0fe) entered forwarding state
[ 3986.049892] docker0: port 1(veth00ed0fe) entered forwarding state
[ 3986.053078] docker0: port 1(veth00ed0fe) entered disabled state
[ 3986.159166] IPv6: ADDRCONF(NETDEV_CHANGE): veth00ed0fe: link becomes ready
[ 3986.162458] docker0: port 1(veth00ed0fe) entered forwarding state
[ 3986.165276] docker0: port 1(veth00ed0fe) entered forwarding state
[ 4001.184055] docker0: port 1(veth00ed0fe) entered forwarding state
[ 6820.396659] traps: dotnet[25812] general protection ip:7fd856cd9532 sp:7fd8514761e0 error:0 in libc-2.19.so[7fd856ca3000+1a1000]
[ 6821.539112] docker0: port 1(veth00ed0fe) entered disabled state
[ 6821.547815] docker0: port 1(veth00ed0fe) entered disabled state
[ 6821.551567] device veth00ed0fe left promiscuous mode
[ 6821.554161] docker0: port 1(veth00ed0fe) entered disabled state
[ 8058.851469] device vethb587fca entered promiscuous mode
[ 8058.859582] IPv6: ADDRCONF(NETDEV_UP): vethb587fca: link is not ready
[ 8058.864357] docker0: port 1(vethb587fca) entered forwarding state
[ 8058.869542] docker0: port 1(vethb587fca) entered forwarding state
[ 8058.874272] docker0: port 1(vethb587fca) entered disabled state
[ 8058.993120] IPv6: ADDRCONF(NETDEV_CHANGE): vethb587fca: link becomes ready
[ 8058.999397] docker0: port 1(vethb587fca) entered forwarding state
[ 8059.003427] docker0: port 1(vethb587fca) entered forwarding state
[ 8074.016083] docker0: port 1(vethb587fca) entered forwarding state
[ 9404.317629] device veth4f47afc entered promiscuous mode
[ 9404.326586] IPv6: ADDRCONF(NETDEV_UP): veth4f47afc: link is not ready
[ 9404.332139] docker0: port 2(veth4f47afc) entered forwarding state
[ 9404.337334] docker0: port 2(veth4f47afc) entered forwarding state
[ 9404.343158] docker0: port 2(veth4f47afc) entered disabled state
[ 9404.372252] docker0: port 2(veth4f47afc) entered disabled state
[ 9404.377589] device veth4f47afc left promiscuous mode
[ 9404.382031] docker0: port 2(veth4f47afc) entered disabled state
[ 9433.386522] device vethc981e8c entered promiscuous mode
[ 9433.393219] IPv6: ADDRCONF(NETDEV_UP): vethc981e8c: link is not ready
[ 9433.397476] docker0: port 2(vethc981e8c) entered forwarding state
[ 9433.401460] docker0: port 2(vethc981e8c) entered forwarding state
[ 9433.406194] docker0: port 2(vethc981e8c) entered disabled state
[ 9433.507171] IPv6: ADDRCONF(NETDEV_CHANGE): vethc981e8c: link becomes ready
[ 9433.511926] docker0: port 2(vethc981e8c) entered forwarding state
[ 9433.516162] docker0: port 2(vethc981e8c) entered forwarding state
[ 9448.544121] docker0: port 2(vethc981e8c) entered forwarding state
[ 9453.225365] docker0: port 2(vethc981e8c) entered disabled state
[ 9453.234362] docker0: port 2(vethc981e8c) entered disabled state
[ 9453.238255] device vethc981e8c left promiscuous mode
[ 9453.241367] docker0: port 2(vethc981e8c) entered disabled state
[ 9463.772035] device vethfb8919a entered promiscuous mode
[ 9463.776170] IPv6: ADDRCONF(NETDEV_UP): vethfb8919a: link is not ready
[ 9463.780263] docker0: port 2(vethfb8919a) entered forwarding state
[ 9463.784430] docker0: port 2(vethfb8919a) entered forwarding state
[ 9463.788904] docker0: port 2(vethfb8919a) entered disabled state
[ 9463.875118] IPv6: ADDRCONF(NETDEV_CHANGE): vethfb8919a: link becomes ready
[ 9463.879698] docker0: port 2(vethfb8919a) entered forwarding state
[ 9463.883585] docker0: port 2(vethfb8919a) entered forwarding state
[ 9478.912100] docker0: port 2(vethfb8919a) entered forwarding state
[ 9479.681022] docker0: port 2(vethfb8919a) entered disabled state
[ 9479.689989] docker0: port 2(vethfb8919a) entered disabled state
[ 9479.695242] device vethfb8919a left promiscuous mode
[ 9479.699623] docker0: port 2(vethfb8919a) entered disabled state
[ 9512.441421] device veth93130f5 entered promiscuous mode
[ 9512.447628] IPv6: ADDRCONF(NETDEV_UP): veth93130f5: link is not ready
[ 9512.451345] docker0: port 2(veth93130f5) entered forwarding state
[ 9512.455103] docker0: port 2(veth93130f5) entered forwarding state
[ 9512.459195] docker0: port 2(veth93130f5) entered disabled state
[ 9512.537031] IPv6: ADDRCONF(NETDEV_CHANGE): veth93130f5: link becomes ready
[ 9512.541136] docker0: port 2(veth93130f5) entered forwarding state
[ 9512.545294] docker0: port 2(veth93130f5) entered forwarding state
[ 9518.480307] docker0: port 2(veth93130f5) entered disabled state
[ 9518.488688] docker0: port 2(veth93130f5) entered disabled state
[ 9518.492795] device veth93130f5 left promiscuous mode
[ 9518.496075] docker0: port 2(veth93130f5) entered disabled state
[ 9527.473512] device veth0e63364 entered promiscuous mode
[ 9527.479398] IPv6: ADDRCONF(NETDEV_UP): veth0e63364: link is not ready
[ 9527.483773] docker0: port 2(veth0e63364) entered forwarding state
[ 9527.487894] docker0: port 2(veth0e63364) entered forwarding state
[ 9527.492279] docker0: port 2(veth0e63364) entered disabled state
[ 9527.575093] IPv6: ADDRCONF(NETDEV_CHANGE): veth0e63364: link becomes ready
[ 9527.579581] docker0: port 2(veth0e63364) entered forwarding state
[ 9527.583901] docker0: port 2(veth0e63364) entered forwarding state
[ 9532.723996] docker0: port 2(veth0e63364) entered disabled state
[ 9532.733411] docker0: port 2(veth0e63364) entered disabled state
[ 9532.738439] device veth0e63364 left promiscuous mode
[ 9532.742686] docker0: port 2(veth0e63364) entered disabled state

```

**Comment by natemcmaster** [comment]
@kalib can you also share the application's logs? It would be good to know if the container is being killed externally, or if something in your application is causing the app to crash (and the container to naturally exit).

**Comment by kalib** [comment]
Unfortunately the developer is not here today, but with your request, I decided to run `docker logs -f MYCONTAINER-ID` and got this when the application/container died:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AWS.Logger.Core.AWSLoggerCore.Finalize()

I can't check the logs for the application, because it's a new application and I am not sure where is he writing the logs. Need to wait for him.

**Comment by natemcmaster** [comment]
The logger error may be a red-herring, but still might we worth opening an issue on https://github.com/aws/aws-logging-dotnet.

Would be good to get the rest of the logs. If there aren't any, I recommend adding a file logger such as Serilog so you can get more details about what is killing the app.

**Comment by guyspygit** [comment]
Still, when you asked about the logs for the application I found that information that gave me more clues about what coudl be wrong.. seem to be with the logging to aws. Will talk to our developer, disable that logging for a few hours and see if the container will die again and also ask him for the application logs. Will be back here telling the results soon.
Thanks for the very quick support.

**Comment by kalib** [comment]
Still, when you asked about the logs for the application I found that information that gave me more clues about what could be wrong.. seem to be with the logging to aws. Will talk to our developer, disable that logging for a few hours and see if the container will die again and also ask him for the application logs. Will be back here telling the results soon.
Thanks for the very quick support.

**Comment by kalib** [comment]
Well, after disabling the nlog configuration (that was trying to send the logs to aws), the container is up and running for the last 3 hours so I guess that was the problem. Will better check that issue. Thanks again.

**Comment by natemcmaster** [comment]
Ok, let's close this for now as external to ASP.NET Core. Happy to re-open for more investigation if you find something wrong in ASP.NET Core that we can help fix.

**Comment by kalib** [comment]
Sure thing, thanks.

**Comment by mries** [comment]
I have been receiving a very similar issue on kubernetes running a dotnet application. In dmesg that comes with the core right before the containers crash this is this in the logs:

[11085.488191] traps: dotnet[25507] general protection ip:7ff4fbdf7529 sp:7fffc1dcec30 error:0 in libc-2.24.so[7ff4fbdc3000+195000]
[11089.047591] traps: dotnet[25686] general protection ip:7f9b2abd5529 sp:7ffcd05dad50 error:0 in libc-2.24.so[7f9b2aba1000+195000]
[11105.793408] traps: dotnet[25968] general protection ip:7fba1b462529 sp:7ffedfa79d00 error:0 in libc-2.24.so[7fba1b42e000+195000]
[11135.857805] traps: dotnet[26332] general protection ip:7fb697600529 sp:7ffe3f358aa0 error:0 in libc-2.24.so[7fb6975cc000+195000]
[11192.790916] traps: dotnet[27056] general protection ip:7f7bcf300529 sp:7ffe9ebc2f60 error:0 in libc-2.24.so[7f7bcf2cc000+195000]
[11286.072392] traps: dotnet[28148] general protection ip:7ffa5585a529 sp:7fffe0022ba0 error:0 in libc-2.24.so[7ffa55826000+195000]
[11410.006211] cbr0: port 16(vethd38bbb18) entered disabled state
[11410.015121] device vethd38bbb18 left promiscuous mode
[11410.015126] cbr0: port 16(vethd38bbb18) entered disabled state
[11449.848218] traps: dotnet[29897] general protection ip:7fedffa3a529 sp:7ffc68eb8690 error:0 in libc-2.24.so[7fedffa06000+195000]
[11765.713298] traps: dotnet[677] general protection ip:7f4e1d45d529 sp:7ffcc67081c0 erro


[292414.521699] dotnet          D    0 15114  32343 0x00000000
[292414.521703] Call Trace:
[292414.521713]  __schedule+0x3d6/0x8b0
[292414.521716]  schedule+0x36/0x80
[292414.521718]  rwsem_down_read_failed+0x10a/0x170
[292414.521722]  ? __handle_mm_fault+0xd3c/0x11e0
[292414.521724]  call_rwsem_down_read_failed+0x18/0x30
[292414.521726]  ? call_rwsem_down_read_failed+0x18/0x30
[292414.521727]  down_read+0x20/0x40
[292414.521731]  __do_page_fault+0x465/0x500
[292414.521734]  ? SyS_futex+0x7f/0x180
[292414.521736]  do_page_fault+0x2e/0xf0
[292414.521738]  ? page_fault+0x2f/0x50
[292414.521740]  page_fault+0x45/0x50
[292414.521742] RIP: 0033:0x7fecd51f8485
[292414.521743] RSP: 002b:00007fecd31b84c0 EFLAGS: 00010206
[292414.521745] RAX: 00007fec439d20f8 RBX: 0000000000000001 RCX: 00007fec439d20c8
[292414.521745] RDX: 0000000000000010 RSI: 0000000000000020 RDI: 00007fecd31b8580
[292414.521746] RBP: 00007fecd31b8600 R08: 0000000000000000 R09: 00007fecd31b9400
[292414.521747] R10: 00007fec5bf0d168 R11: 000000000000000d R12: 0000000000000002
[292414.521748] R13: 00007fec5b7ae750 R14: 00007fec5ce4f160 R15: 0000000000000000
[292414.521750] NMI backtrace for cpu 0
[292414.521753] CPU: 0 PID: 17 Comm: khungtaskd Not tainted 4.15.0-1025-azure #26~16.04.1-Ubuntu
[292414.521754] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
[292414.521754] Call Trace:
[292414.521759]  dump_stack+0x63/0x82
[292414.521761]  nmi_cpu_backtrace+0xcb/0xd0
[292414.521765]  ? irq_force_complete_move+0x90/0x90
[292414.521767]  nmi_trigger_cpumask_backtrace+0xef/0x140
[292414.521769]  arch_trigger_cpumask_backtrace+0x19/0x20
[292414.521771]  watchdog+0x2bf/0x340
[292414.521776]  kthread+0x105/0x140
[292414.521778]  ? reset_hung_task_detector+0x20/0x20
[292414.521780]  ? kthread_destroy_worker+0x50/0x50
[292414.521781]  ret_from_fork+0x35/0x40
[292414.521784] Kernel panic - not syncing: hung_task: blocked tasks
[292414.525625] CPU: 0 PID: 17 Comm: khungtaskd Not tainted 4.15.0-1025-azure #26~16.04.1-Ubuntu

the version of libc is 2.24.  Would this be more related to code or a problem with libc?

**Comment by ctaggart** [comment]
@mries me too. Is the docker image Alpine Linux with dotnet 2.1.6?
```
/ # dotnet --info

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
