### ISSUE TITLE
invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by SimonVuong** [aspnet/aspnet-docker#275]
## Steps to reproduce the issue
1. create the project
```
mkdir pic
cd pic
dotnet new webapi
```
2. follow the steps here https://medium.com/@levifuller/building-an-angular-application-with-asp-net-core-in-visual-studio-2017-visualized-f4b163830eaa
3. follow steps 1-3 here https://github.com/aspnet/aspnet-docker/blob/master/README.aspnetcore-build.md
4. `docker build -t pic .`

## Expected behavior

builds the docker image

## Actual behavior

i get the error

> Sending build context to Docker daemon  194.2MB
> Step 1/10 : FROM microsoft/aspnetcore-build AS builder
> **invalid reference format: repository name must be lowercase**

## Output of `dotnet --info`

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

## Output of `docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 104
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 71
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: 
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: dev
ID: W6F3:ASCX:37LF:XA5I:JIHP:5G3L:HNXA:BFEH:JT5D:GEL4:47SA:KUJA
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 22
 System Time: 2017-08-08T14:47:31.380371744Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 <our registry>.com
 <our registry>.com
Live Restore Enabled: false
```

**Comment by natemcmaster** [comment]
It looks like you're using Docker 17.04.0-ce. As the readme mentions, Docker 17.05 or newer is required. If you're unable to upgrade, here is [an old version of the instructions.](https://github.com/aspnet/aspnet-docker/blob/87ffb5a2d3f20610ccc48a2f4eb9d4896b9a49b2/README.aspnetcore-build.md#example-usage)

See also https://github.com/dotnet/announcements/issues/18.

**Comment by Simon-Vuong** [comment]
fixed. thanks.

quick word for those seeing this issue... it's important to have the docker **server** updated to the correct version. if you created a machine with an older docker client version, then that machine will still have the same older version when you update the client. you need to recreate the machine so that it has a newer version
