### ISSUE TITLE
Begin producing 2.1 nightly images

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#279]
Depends on microsoft/dotnet-nightly to begin consuming 2.1 daily builds of .NET Core.

cc @MichaelSimons

**Comment by MichaelSimons** [comment]
Depends on https://github.com/dotnet/dotnet-docker-nightly/issues/398

**Comment by dls314** [comment]
Are 2.1 preview nightly images likely to be available soon?

**Comment by natemcmaster** [comment]
`microsoft/dotnet-nightly` has them already. I'll merge #280 later today to begin making 2.1 images of `microsoft/aspnetcore-nightly` and `microsoft/aspnetcore-build-nightly`.

That said, those images won't actually have the 2.1 runtime, only the 2.1 SDK. A bunch of people are on summer break and we have no schedule yet for when that will be fixed.

**Comment by cwardcode** [comment]
@natemcmaster Is there any update on the ETA for runtime images being produced?

**Comment by natemcmaster** [comment]
Hopefully a week or two, but I can't promise anything. We're blocked on internal infrastructure changes required to retarget aspnetcore to netcoreapp2.1.

**Comment by natemcmaster** [comment]
That took longer than expected, but this is done now. Nightly images are up.
