### ISSUE TITLE
React to changes in docker build tools

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#285]
Manifest.json schema changed slightly. We need to update build scripts, pipeline configuration, and README tags.

cref https://github.com/dotnet/dotnet-docker-nightly/commit/a1dcba51294abadf17a07c353e3586c464984143#diff-4b1eb3dc48c4e16d49db5b42298fe654L24

cc @MichaelSimons

**Comment by MichaelSimons** [comment]
Also the --command parameter was replaced by proper commands as indicated below.

```
usage: Microsoft.DotNet.ImageBuilder <command> [<args>]

    build                              Builds and Tests Dockerfiles
    generateTagsReadme   Generate the tags section of the readme
    publishManifest            Creates and publishes the manifest to the Docker Registry
    updateReadme             Updates the readme on the Docker Registries
    updateVersions            Updates the version information for the dependent images
```

**Comment by MichaelSimons** [comment]
There is also this change - https://github.com/dotnet/dotnet-docker-nightly/commit/3b046ad7d9c3e155be3724ef7e1e9fcad7921775#diff-4b1eb3dc48c4e16d49db5b42298fe654L20

The readme order property is not necessary for the aspnet-docker repos.  It was needed to control the runtime-deps image order in the readme which is different than the build order.

**Comment by MichaelSimons** [comment]
@natemcmaster, Not sure if you started working on this or not.  I took a few minutes to upgrade the manifest and build defs.   https://github.com/aspnet/aspnet-docker/compare/master...MichaelSimons:latest-image-builder?expand=1

The build and test scripts still needs changes to handle the manifest schema change.

**Comment by natemcmaster** [comment]
Nope, I haven't started yet. If you want to do the upgrades, it's all yours.
________________________________
