### ISSUE TITLE
SDK Version

### ISSUE THREAD

**Issue by brentarias** [aspnet/aspnet-docker#290]
This is a documentation issue.  How can I tell which SDK version is supported / targeted with this docker file?

    https://github.com/aspnet/aspnet-docker/blob/master/1.0/nanoserver/sdk/Dockerfile

I am not yet ready to upgrade to the csproj format, so I need a docker file / image that uses an older SDK.  I think the `RC3 build 4530` SDK is the last one that still uses project.json.

I am guessing that if the dockerfile offers 1.0.5, then it is also offering SDK 1.0.4 (which requires msbuild / csproj files)...but I can't tell.

**Comment by natemcmaster** [comment]
The `microsoft/aspnetcore` and `microsoft/aspnetcore-build` images are based on a `microsoft/dotnet` image.

https://github.com/aspnet/aspnet-docker/blob/03260d72778f0127e954110e422fccfab081d04c/1.0/nanoserver/sdk/Dockerfile#L2

You can determine which SDK is installed by looking at the `microsoft/dotnet` definition.

https://github.com/dotnet/dotnet-docker/blob/9a4902275098fa1bfa659cd57f65470c30cf6a6b/1.0/sdk/nanoserver/Dockerfile#L5-L7
