### ISSUE TITLE
Version(s) are Missing

### ISSUE THREAD

**Issue by brentarias** [aspnet/aspnet-docker#291]
The [Dockerhub image for aspnetcore-build](https://hub.docker.com/r/microsoft/aspnetcore-build/) does not contain the ASP.NET Core 1.0 image that it claims to contain.  The "tags" page indicates that "1.0" is allegedly one of the tags, but it isn't available.

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1.  On Windows 10 Professional, invoke "docker pull microsoft/aspnetcore-build:1.0"
2.  Then run "docker container run -it microsoft/aspnetcore-build:1.0 powershell"
3.  In the container's terminal window, type "dotnet --version" or "dotnet --info"

## Expected behavior
"dotnet --version" should output "1.0", or at least a "1.0.x" version.

## Actual behavior
"dotnet --version" outputs "1.1.0"

## Additional information (e.g. issue happens only occasionally)
I have Docker configured for Windows containers.  Allegedly the docker hub image has a aspnet.core 1.0 image, as represented in the following dockerfile:
`https://github.com/aspnet/aspnet-docker/blob/master/1.0/nanoserver/sdk/Dockerfile`

## Output of `dotnet --info`
When executed directly on my laptop (not within a continer), then 'dotnet --info" outputs:
```
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

## Output of `docker info`

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 17.06.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.916GiB
Name: DESKTOP-057K4L5
ID: VRHC:PY7B:3WNS:FDPL:PHX7:4LQ5:GVMZ:JIE7:K6GJ:VWAC:GYYZ:ZCV4
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 20
 System Time: 2017-09-06T12:25:34.9849615-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Comment by natemcmaster** [comment]
The `microsoft/aspnetcore-build` image gets its SDK from `microsoft/dotnet`. 

https://github.com/aspnet/aspnet-docker/blob/03260d72778f0127e954110e422fccfab081d04c/1.0/nanoserver/sdk/Dockerfile#L2

I'm moving this issue to the repo for this image so they can comment on or resolve this discrepancy.

https://github.com/dotnet/dotnet-docker/blob/9a4902275098fa1bfa659cd57f65470c30cf6a6b/1.0/sdk/nanoserver/Dockerfile#L5-L7

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/dotnet-docker#291
