### ISSUE TITLE
Docker container is not starting

### ISSUE THREAD

**Issue by sreekanthmg** [aspnet/aspnet-docker#292]
If you are having an issue with microsoft/aspnet, please open an issue on https://github.com/Microsoft/aspnet-docker.
This repository is for microsoft/aspnetcore and microsoft/aspnetcore-build.

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1. I have created a sample asp.net core web api (asp.net core 1.0.1) and added dockerfile using VS docker plugin
please find my docker file
```
FROM microsoft/aspnetcore:1.0.1
ENTRYPOINT ["dotnet", "testapp.dll"]
ARG source=.
WORKDIR /app
EXPOSE 80
COPY $source .
```
2. Then I have created an image using below command
docker build -t testapp .
It successfully created the image
3. Then I try to create the container by below command
docker run -d -p 8080:80 --name myapp testapp

This time the container created but it is not not running.
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                        PORTS               NAMES
eefb792438f5        testapp             "dotnet testapp.dll"     9 minutes ago        Exited (145) 9 minutes ago                        myapp

It shows the container exited. Also I dont see any port number assigned

## Output of `dotnet --info`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by natemcmaster** [comment]
Can you provide more info? Which version of docker are you using? What error is produced from dotnet? Try running `docker logs` or `docker run -it` to see more info about the error.
