### ISSUE TITLE
September Patch docker images

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/aspnet-docker#293]
Not sure if you have already filed the issue for creating docker images for 1.0.6 and 1.1.3 so feel free to close this if needed.

**Comment by natemcmaster** [comment]
It looks like dotnet-nightly has some of the changes we need to build these as a nightly ourself https://github.com/dotnet/dotnet-docker-nightly/pull/414, but not all: https://github.com/dotnet/dotnet-docker-nightly/pull/416.
