### ISSUE TITLE
Memory usage with ASP.NET Core Docker containers on Ubuntu

### ISSUE THREAD

**Issue by Ettery** [aspnet/aspnet-docker#300]
I am running .NET Core 1.1 containers on Docker/Ubuntu 14.04, hosting Web APIs. The containers are based on `microsoft/aspnetcore:1.1.2` with the binaries published for Ubuntu x64 platform and copied in when the image is built, as simple as it gets.

Our Web APIs are  simple at the moment, at most a handful of controllers pulling data from SQL Server. They do no significant caching or anything unusual, but when running use anywhere from 500-900 Mb of RAM each. This is not due to memory leaks - the memory usage for each container is stable over time, varying up and down by 10-15Mb during usage.

Why so much memory, and what can be done to reduce it? It gets costly running a set of microservices on Azure with this sort of memory requirement, and it should be completely unnecessary.  `debian/jessie` alone uses only a few Mb.

Also, will it adjust automatically?  If memory starts to become constrained as more containers start up, will containers release memory?

And lastly, will it cause problems if I configure Docker to restrict memory - say to 200Mb?

## Steps to reproduce the issue
	FROM docker-registry.public-upstream.gray.net/microsoft/aspnetcore:1.1.2
	MAINTAINER DevCartel team 
	LABEL Name=mercury.docker.core-api Version=1.1.47
	ARG source=./app
	WORKDIR /app
	COPY $source .

	# Install certificate
	RUN curl -ks 'https://server/ssl_certs/AllanGrayEnterpriseRootCA.crt' -o '/usr/local/share/ca-certificates/EnterpriseRootCA.crt' && \
	/usr/sbin/update-ca-certificates

	# Set timezone to SAST
	RUN echo "Africa/Johannesburg" > /etc/timezone
	RUN dpkg-reconfigure -f noninteractive tzdata

	EXPOSE 80
	ENTRYPOINT dotnet core-api.dll

## Expected behavior
Far lower memory usage.  50-100Mb max?

## Actual behavior
Each container uses 500 - 900 Mb mamory

**Comment by natemcmaster** [comment]
I don't really have enough information to give you an answer. Docker allows you to configure resource constraints (https://docs.docker.com/engine/admin/resource_constraints/). But, if you app truly requires this much memory, you'll likely see degraded performance by decreasing constraints.

My guess is that this isn't actually related to Docker, but to confirm, have you compared the memory usage of your application when running on Windows, or on Linux outside of the container? Also, how are you measuring memory usage? 

It's hard to tell you exactly what to do to reduce memory usage without knowing more details. I recommend taking a memory dump to examine the heap. Also, try using other profiling tools to examine allocations, find hot paths, and perhaps fix app code if necessary, or to help us find issues in the framework.

**Comment by Ettery** [comment]
Hi @natemcmaster, thanks for your input, some useful ideas.  I got a response from @janvorli on the CoreCLR team.  It sounds as if this problem is caused by a bug in the .NET Core GC.  It's specific to running in Docker and will be fixed in the upcoming 2.0.2 release.  You can read the detail in [issue 13292](https://github.com/dotnet/coreclr/issues/13292#issuecomment-331201963) on the CoreCLR Github repo.  Meantime setting `<ServerGarbageCollection>false</ServerGarbageCollection>` seems to be working for me, I don't have high concurrency at the moment.

**Comment by natemcmaster** [comment]
Awesome, good to know. I'm going to close this in favor of https://github.com/dotnet/coreclr/issues/13292 then. But we can re-open if you continue to find issues after the 2.0.2 update.
