### ISSUE TITLE
The library 'libhostpolicy.so' required to execute the application was not found

### ISSUE THREAD

**Issue by shirhatti** [aspnet/aspnet-docker#301]
_From @RehanSaeed on September 15, 2017 12:8_

I'm not certain where to post this issue. I get the following error when running one of two docker containers using the ASP.NET Core 2.0 linux image:

```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app'.
```

The container runs fine when being run using Visual Studio's Docker Support project. It only throws the above error when running on Docker for AWS which uses Moby linux for the host OS.

I get no further information than that unfortunately. I'm not sure how to debug it further either. Looking online, I've seen people mention that I need a `runtimeconfig.template.json` file  which already I have.

_Copied from original issue: Microsoft/aspnet-docker#52_

**Comment by natemcmaster** [comment]
@RehanSaeed can you provide repro steps? See [this template](https://github.com/aspnet/aspnet-docker/blob/master/.github/ISSUE_TEMPLATE) for a list of info we typically need to help you diagnose issues.

**Comment by RehanSaeed** [comment]
I'm not certain what caused it but it seems to have gone away. It's probably because I had a case mismatch of `appSettings.json` instead of `appsettings.json` which meant that the file was not being loaded. Terrible error though.

**Comment by natemcmaster** [comment]
Ok. Feel free to reopen if you find out what is wrong.

**Comment by MrM40** [comment]
My solution was include the `YourApplication.runtimeconfig.json` in your installation package

**Comment by alexandrupascanu** [comment]
Hello,
I 've included runtime and deps files into my Asp.net core 1.1 application release but i still have the  :"The library 'libhostpolicy.so' required to execute the application was not found in '/app'.",
I 'm blocked.
Can anyone help me out with this one?
Thank you!
