### ISSUE TITLE
Just trying to build .NET Core 2.0 with EF Core 2.0 to jenkins

### ISSUE THREAD

**Issue by joehoeller** [aspnet/aspnet-docker#305]
What is the correct Docker file to use for building a REST API from .NET Core 2.0 into a Docker Container?

**Comment by natemcmaster** [comment]
`microsoft/aspnetcore-build:2.0`. See https://github.com/aspnet/aspnet-docker/blob/master/README.aspnetcore-build.md#example-usage for more details.

Closing as this is a question, not a bug, but feel free to continue discussion.

**Comment by alexsandro-xpt** [comment]
@natemcmaster Why could not use `microsoft/dotnet:2.0-sdk` image for build?

**Comment by natemcmaster** [comment]
You could do that too. microsoft/aspnetcore-build offers additions to Microsoft/dotnet:2.0-sdk designed for common web-app scenarios. See https://github.com/aspnet/aspnet-docker/blob/master/2.0/stretch/sdk/Dockerfile
