### ISSUE TITLE
Docker Read-Only File System

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/aspnet-docker#331]
I learned that you have the ability to set the file system to [read-only](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only) in docker by setting a simple boolean flag. Any custom volumes you've specified remain unaffected. This seems like a great little flag to turn on for some added security, so I tried it out and got the following error from my ASP.NET Core 2.0 runtime image:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

Does the ASP.NET Core image support this feature and could it even be turned on in the Dockerfile by default for some added security?

**Comment by natemcmaster** [comment]
I looked at the docs you linked to. IIUC it doesn't look this is something we can do anything about. The `--read-only` option only applies when creating a container. It's not a configuration setting the image can control.

> Failed to initialize CoreCLR, HRESULT: 0x80004005

Most likely you'll need to forward this to dotnet/coreclr or dotnet/core-setup, but I would need to see repro steps and more error details before I could tell you which is more appropriate.

**Comment by RehanSaeed** [comment]
Here is a full repro:

https://github.com/RehanSaeed/ReadOnlyDockerTest

**Comment by MorayM** [comment]
I'm seeing this issue as well: https://github.com/MorayM/GlaaCore/tree/read-only

**Comment by natemcmaster** [comment]
Thanks for the repo. It appears to be a bug in CoreCLR that affects microsoft/aspnetcore and microsoft/dotnet images. There doesn't appear to be anything we can do in the aspnetcore image to mitigate this, so closing in favor of https://github.com/dotnet/coreclr/issues/15243.

**Comment by RehanSaeed** [comment]
Just tried to run an ASP.NET Core 2.2 app with `--read-only` and I still get the error below:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

@natemcmaster According to https://github.com/dotnet/coreclr/issues/15243 this issue should have been fixed. Any ideas?

**Comment by natemcmaster** [comment]
Try adding this to your docker definition:

```dockerfile
ENV COMPlus_EnableDiagnostic=0
```

cref https://github.com/dotnet/docs/issues/10217

**Comment by RehanSaeed** [comment]
That doesn't seem to work for me. Full repro updated at https://github.com/RehanSaeed/ReadOnlyDockerTest

**Comment by natemcmaster** [comment]
Sorry, I'm not sure what's wrong.

**Comment by ChrisMcKee** [comment]
> Try adding this to your docker definition:
> 
> ```dockerfile
> ENV COMPlus_EnableDiagnostic=0
> ```
> 
> cref [dotnet/docs#10217](https://github.com/dotnet/docs/issues/10217)

That should be `ENV COMPlus_EnableDiagnostics=0` (plural)

**Comment by RehanSaeed** [comment]
@ChrisMcKee Thanks for your investigation. That typo is not something I'd have spotted.
