### ISSUE TITLE
aspnetcore.runtimestore.tar.gz not a valid tar archive

### ISSUE THREAD

**Issue by voltaire-ilustrisimo-webjet** [aspnet/aspnet-docker#337]
## Steps to reproduce the issue
Run docker build using this Dockerfile in this repo.

## Expected behavior
Docker image for aspnetcore 2.0.3 gets built.

## Actual behavior
runtimestore.tar.gz from https://dist.asp.net/runtimestore/$version/linux-x64/aspnetcore.runtimestore.tar.gz gives an error for version 2.0.0 and 2.0.3.

#####
Step 9/9 : RUN for version in '2.0.0' '2.0.3'; do         curl -o /tmp/runtimestore.tar.gz https://dist.asp.net/runtimestore/$version/linux-x64/aspnetcore.runtimestore.tar.gz  && export DOTNET_HOME=$(dirname $(readlink $(which dotnet)))         && tar -x -C $DOTNET_HOME -f /tmp/runtimestore.tar.gz         && rm /tmp/runtimestore.tar.gz; done
 ---> Running in c9df08453f28
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   223  100   223    0     0    138      0  0:00:01  0:00:01 --:--:--   138
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   223  100   223    0     0     92      0  0:00:02  0:00:02 --:--:--    92
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c for version in '2.0.0' '2.0.3'; do         curl -o /tmp/runtimestore.tar.gz https://dist.asp.net/runtimestore/$version/linux-x64/aspnetcore.runtimestore.tar.gz         && export DOTNET_HOME=$(dirname $(readlink $(which dotnet)))         && tar -x -C $DOTNET_HOME -f /tmp/runtimestore.tar.gz         && rm /tmp/runtimestore.tar.gz; done' returned a non-zero code: 2
#####

## Additional information
Issue happens every local docker build.

## Output of `dotnet --info`
```
NA
```
## Output of `docker info`

```
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-40-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54GiB
Name: webjet
ID: OZWJ:ER3D:TPTS:PDOH:YOBZ:WHYW:3U3A:FIKJ:KKTY:JT3P:GSJL:DG4X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by bittercoder** [comment]
:heavy_plus_sign:  I'm having the same issue when using these docker files as a starting point for building my own runtime images, the runtimestore files do not exist/404.

**Comment by natemcmaster** [comment]
Dist.asp.net went down over the weekend. It should be up again. Sorry about that.

**Comment by voltaire-ilustrisimo-webjet** [comment]
Thanks @natemcmaster!
