### ISSUE TITLE
Wrong Dateformat when running in Docker container

### ISSUE THREAD

**Issue by BickelLukas** [aspnet/aspnet-docker#343]
When running in a Docker container the DateFormat for the German Culture (the only one I tested) is different than when running on Windows.

## Steps to reproduce the issue
1. Call DateTime.Now.ToString("d", new CultureInfo("de"))
2. Run in Container microsoft/aspnetcore:2.0

## Expected behavior
print "dd.MM.yyyy"

## Actual behavior
print "dd.MM.yy"

## Output of `dotnet --info`
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

## Output of `docker info`

Containers: 124
 Running: 1
 Paused: 0
 Stopped: 123
Images: 106
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: moby
ID: 7JIH:HRXP:3ZVN:PHFM:RNPQ:URWM:J7AS:RB6C:6NXQ:SKAH:VNXS:CKDY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 42
 System Time: 2017-12-13T07:59:49.3483431Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by natemcmaster** [comment]
This is due to the differences between Linux and Windows. .NET Core handles globalization according to how the OS specifies its locale formats. See https://github.com/dotnet/corefx/issues/3698.

There isn't much we can do at the Docker layer. If you're still having issues, I recommend moving this to https://github.com/dotnet/corefx
