### ISSUE TITLE
Deprecate microsoft/aspnetcore:1.0-1.1 and microsoft/aspnetcore:1.0-2.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#349]
Discussion item for https://github.com/aspnet/Announcements/issues/292.

------

We will be deprecating the following Docker images

- microsoft/aspnetcore-build:1.0-1.1
- microsoft/aspnetcore-build:1.0-2.0

These were created for Visual Studio tooling. We do not plan to produce a `1.0-2.1` tag as the VS tooling has improvements planned to remove the need to roll all .NET Core versions into one image. Also, multi-stage builds and minor-version rollforward reduces the need for the images.

Deprecation plan:

 - Phase 1: we will remove these tags from the README as "supported tags". 
 - Phase 2: as the runtimes in these images eventually drop out out patching support, stop patching these images.

FYI - we do _not_ plan to delete the tags. They will remain available, but will stop getting patches at some point in the future.

**Comment by muratg** [comment]
@natemcmaster What's the currnet timeline for this?  What milestone should this be tracked at?

**Comment by natemcmaster** [comment]
There really isn't any action item at the moment. We just aren't releasing kitchensink images for 2.1. As 1.0, 1.1, and 2.0 drop out of servicing, we will stop updating these tags. I suppose the only action item is to mark this repo as obsolete in the future once everything has moved to dotnet/dotnet-docker, but that won't happen for a while.

**Comment by temporafugiunt** [comment]
I think it is a great idea what you guys are doing, but I have a problem. I am trying to use the **windows** side for a SPA build using the **microsoft/dotnet:2.1-sdk**. I know, I may be the only one trying to stay on the windows side for an ASP.NET Core Application, but our swarm initially will only have windows servers running in the native OS mode and not Hyper-V mode.

As a consequence, I need to install node.js for windows and I tried:

`RUN msiexec.exe /a https://nodejs.org/dist/v8.11.3/node-v8.11.3-x64.msi /quiet`

but msiexec.exe isn't in the c:\windows\system32 of this image.

**curl** also is not in this image as that is a linux tool

I can't run a powershell invocation of:

`iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

to try to install chocolatey to install node from there as System.New.WebClient is not available in this image.

I guess my question is is there any native way to get this installed from within the container without having to download something outside the container, copying it in, and then executing it potentially. Kinda defeats the purpose of a multistage build if I have to do that. Any advice you can give would be greatly appreciated.

**Comment by natemcmaster** [comment]
@temporafugiunt Instead of using Node's .exe installer, I recommend downloading and extracting their .zip archive. For example, this is how we install Node in the 2.0 images.

https://github.com/aspnet/aspnet-docker/blob/faf84e19ba622822d8afa5f6be7a3df4d935759b/2.0/nanoserver-sac2016/sdk/Dockerfile#L7-L26

Also, how exactly you download and extract the .zip will depend on which version of Windows you are trying to use. If you are using Nano Server 1709, you will need something fairly complicated ([see example](https://github.com/aspnet/aspnet-docker/blob/master/2.0/nanoserver-1709/sdk/Dockerfile)). If you are using nano Server 1803 or newer, you can use tar.exe and curl.exe which were [added as new features of the latest Windows update](https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/).

**Comment by temporafugiunt** [comment]
Here is the issue I am talking about:
https://github.com/dotnet/dotnet-docker/issues/606

**Comment by natemcmaster** [comment]
Closing as these images are deprecated and there is no further action here from the team.
