### ISSUE TITLE
cant run certutil on microsoft/aspnetcore nanoserver

### ISSUE THREAD

**Issue by icenold** [aspnet/aspnet-docker#351]
Im trying to import my certificates .pfx and .cer
Im using windows container by the way

![certutil](https://user-images.githubusercontent.com/16298042/34770864-6b9f29c2-f63d-11e7-9efd-7623249131ec.png)

**Comment by natemcmaster** [comment]
Sorry you hit this. Unfortunately, this is the wrong place for the bug. The aspnetcore images are based on `microsoft/nanoserver` images. We don't have the ability to add certutil into that base image.

For support or help with Nano Server, checkout their [Docker Hub](https://hub.docker.com/r/microsoft/nanoserver/) page or their [forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers). If you're on Windows 10, you can also use the Feedback Hub app.
