### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by eliassal** [aspnet/aspnet-docker#352]
Hi, whenever I try
docker pull microsoft/aspnet, I get 

```
Sending build context to Docker daemon  24.06kB
Step 1/7 : FROM microsoft/aspnet
latest: Pulling from microsoft/aspnet
3889bb8d808b: Downloading [=====>                                             ]    446MB/4.07GB
449343c9d7e2: Downloading [=================>                                 ]  445.9MB/1.304GB
ccd8f322a2de: Download complete
5358f1f8c04f: Download complete
27fb1950158d: Download complete
4447c3ffe068: Download complete
94eeeaf0d3bd: Download complete
fe1d276c8d64: Downloading
25871a4250c9: Waiting
b53cc298d0b7: Waiting
unauthorized: authentication required

```
any help? Opened a thread on docker site, nobody responded. My platform is Docker for windows as follows

> Client:
>  Version:       17.12.0-ce
>  API version:   1.35
>  Go version:    go1.9.2
>  Git commit:    c97c6d6
>  Built: Wed Dec 27 20:05:22 2017
>  OS/Arch:       windows/amd64
> 
> Server:
>  Engine:
>   Version:      17.12.0-ce
>   API version:  1.35 (minimum version 1.24)
>   Go version:   go1.9.2
>   Git commit:   c97c6d6
>   Built:        Wed Dec 27 20:15:52 2017
>   OS/Arch:      windows/amd64
> 

If you are having an issue with microsoft/aspnet, please open an issue on https://github.com/Microsoft/aspnet-docker.
This repository is for microsoft/aspnetcore and microsoft/aspnetcore-build.

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1.
2.
3.

## Output of `dotnet --info`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by eliassal** [comment]
Just to confirm that win 10 firewall is completely desactivated

**Comment by natemcmaster** [comment]
This issue was moved to Microsoft/aspnet-docker#86
