### ISSUE TITLE
Hookup CI for Nano Server 1709 based images

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#355]
CI was never enabled for the Nano Server 1709 based images.  See https://github.com/aspnet/aspnet-docker/blob/master/.appveyor.yml#L7.  This should be enabled.

**Comment by natemcmaster** [comment]
AppVeyor runs Windows Server 2016 LTSC at the moment, so this is blocked by https://github.com/appveyor/ci/issues/1885 unless we explore other CI solutions.

**Comment by MichaelSimons** [comment]
If you decide to explore other CI solutions, you could probably make use of the Jenkins infra .NET Core utilizes.

**Comment by natemcmaster** [comment]
Commonizing public CI infrastructure is something we've considered, but haven't committed to yet. 

cc @shawnro - this would be a good subject to discuss in our next brownbag

cc @muratg for triage

**Comment by muratg** [comment]
@natemcmaster should we file an Universe (or some other) repo bug to track potential infrastructure work?

**Comment by natemcmaster** [comment]
Unless we want to replace Travis/AppVeyor for _all_ aspnet repos, let's just use this to track getting docker PRs building on public CI that supports 1709.

**Comment by muratg** [comment]
Any work left here?  Or should we move out?

**Comment by natemcmaster** [comment]
Just waiting on @Eilon to add PR webhooks so we can ensure #371 works. Once merged, this issue is done.

**Comment by natemcmaster** [comment]
Done in #371
