### ISSUE TITLE
microsoft/aspnetcore:2.0 with angular/npm, missing dependencies?

### ISSUE THREAD

**Issue by Drewster727** [aspnet/aspnet-docker#358]
Hi guys,
So, I have a web project built in asp.net core 2.0. It uses angular 5+ and several npm packages.
I utilized visual studio to "add" docker support, which did the following for me:
- Created docker-compose files at the solution level (parent folder)
- Created Dockerfile in the directory of my web project

That seems to work fine, I can spin up the container and it works. Now, my company utilizes Octopus deploy to push code/files out to our various severs. So, I needed to avoid the docker-compose stuff and just use the dockerfile at the web project level. Therefore, I had to remove any of the *.sln references in said dockerfile. I'm running into issues when building the docker container via dockerfile.

I used this link as an example:
https://docs.docker.com/engine/examples/dotnetcore/#introduction
However, that does not consider npm dependencies.

## Steps to reproduce the issue
```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY package.json ./
RUN curl -sL https://deb.nodesource.com/setup_8.x |  bash -
RUN apt-get install -y build-essential nodejs
RUN npm install -g @angular/cli@1.6.3
RUN npm install
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "XYZ.Web.dll"]
```

## Expected behavior
The docker container properly spins up, angular/npm dependencies get loaded as expected.

## Actual behavior
I get the following errors when dotnet publish runs:
```
Step 12/17 : RUN dotnet publish --output /app/ --configuration Release
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  npm ERR! Linux 4.9.60-linuxkit-aufs
  npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
  npm ERR! node v6.12.3
  npm ERR! npm  v3.10.10
  npm ERR! path /app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug
  npm ERR! code ENOENT
  npm ERR! errno -2
  npm ERR! syscall rename

  npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug' -> '/app/node_modules/babel-traverse/node_modules/debug'
  npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug' -> '/app/node_modules/babel-traverse/node_modules/debug'
  npm ERR! enoent This is most likely not a problem with npm itself
  npm ERR! enoent and is related to npm not being able to find a file.
  npm ERR! enoent

  npm ERR! Please include the following file with any support request:
  npm ERR!     /app/npm-debug.log
/app/SMG.HealthCheck.Web.csproj(108,5): error MSB3073: The command "npm install" exited with code 254.
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

## Additional information (e.g. issue happens only occasionally)
I have changed around my dockerfile multiple times and still can't figure out why this is happening. It appears it cannot find the modules it needs.

## Output of `dotnet --info`
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

## Output of `docker info`
```
Containers: 29
 Running: 0
 Paused: 0
 Stopped: 29
Images: 101
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155dbd1809
ID: 3XU7:A6N6:ZIJM:SG5W:5QOX:WLSQ:H55C:TDOX:MAYH:F3OP:GX7C:4NXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 60
 System Time: 2018-01-25T19:19:38.1260434Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by natemcmaster** [comment]
This appears to be unrelated to docker or aspnetcore. You've installed Node6 and npm3 into your image, which I believe have issues with angular CLI. Try upgrading to node 8 instead.

**Comment by Drewster727** [comment]
@natemcmaster  I suspected that might be the case. I assumed setup_8.x was installing node 8? Do you have a suggestion for getting the latest? apt-get might be outdated.

**Comment by natemcmaster** [comment]
I'd recommend copying this into your docker file. Update to to the version you want. You can find shasums on https://nodejs.org/dist/
https://github.com/aspnet/aspnet-docker/blob/f85c35c8d2be2170fe727cf65c139e7b41226f7d/2.0/jessie/sdk/Dockerfile#L8-L16

**Comment by Drewster727** [comment]
@natemcmaster  thanks man, I'm very close now. I appear to be having a permission issue inside the container now:
```
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.4
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.4
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.4"
```

**Comment by Drewster727** [comment]
OK, I esolved that last issue by adding --unsafe to my global installs. However, I still get the same @angular/cli complaints. @natemcmaster 

```
root@8895d7d6094b:/app# node -v
v8.9.4
root@8895d7d6094b:/app# npm -v
5.6.0
```

**Comment by natemcmaster** [comment]
Sorry @Drewster727, not sure how to solve this, but it sounds like an issue with Angular. You might have better luck opening an issue on their project.

I'm going to close this out as this appears to be a NodeJS/Angular issue, not ASP.NET Core. Feel free to continue discussion. You can use #334 to track the discussion on putting node 8 into our images. cc @glennc @muratg
