### ISSUE TITLE
Update to Node 6.13.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#364]
Currently we're on 6.12.3.

https://nodejs.org/en/blog/release/v6.13.0/

**Comment by gertjvr** [comment]
Why not upgrade to the latest lts 8.9.4 https://github.com/nodejs/Release#release-schedule we can get speed benefits of npm 5 and its lock file controlling dependencies.

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/aspnet-docker/issues/334#issuecomment-366297373

**Comment by natemcmaster** [comment]
Fixed in #376
