### ISSUE TITLE
Add DOTNET_USE_POLLING_FILE_WATCHER env var for sdk images

### ISSUE THREAD

**Issue by danroth27** [aspnet/aspnet-docker#366]
When doing development in Docker I believe it's best practice to set the `DOTNET_USE_POLLING_FILE_WATCHER` to enable the polling file watcher (see https://github.com/aspnet/Announcements/issues/186). I think we should do this in our SDK images.

**Comment by MichaelSimons** [comment]
The plan is to add this to the microsoft/dotnet:sdk images which are the base image for the microsoft/aspnetcore-build images.  see https://github.com/dotnet/dotnet-docker/issues/426

**Comment by natemcmaster** [comment]
👍 closing in favor of https://github.com/dotnet/dotnet-docker/issues/426.

**Comment by samfullman** [comment]
Hey, as this URI comes up high in searching for "DOTNET_USE_POLLING_FILE_WATCHER", could you mention (as I'm searching) where this value is set and any other related information?  I have a MacOS also
