### ISSUE TITLE
Upgrading to 2.1.101 SDK causes restore to fail with error MSB3202

### ISSUE THREAD

**Issue by WolfspiritM** [aspnet/aspnet-docker#388]
## Steps to reproduce the issue
Since the new image for 2.0.6 has been pushed to the docker registry the build has been broken for us.
Error: ```/usr/share/dotnet/sdk/2.1.101/NuGet.targets(229,5): error MSB3202: The project file "/src/docker-compose.dcproj" was not found. [/src/Solution.sln]```

When I fix the version to 2.0.5-2.1.4 it works without issues again.

I wondered if using aspnetcore:2.0.5 as base might have caused the issue but as the problem happens within the build stage I doubt that.

The Solution contains the docker-compose project:
```
Project("{E53339B2-1760-4266-BCC7-CA923CBCF16C}") = "docker-compose", "docker-compose.dcproj", "{695B1C67-0788-473E-9B72-A4AA9DD21B29}"
```
And that file is obviously there.
docker-compose.dcproj:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" Sdk="Microsoft.Docker.Sdk">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|AnyCPU">
      <Configuration>Debug</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|AnyCPU">
      <Configuration>Release</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Test|AnyCPU">
      <Configuration>Test</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectVersion>2.1</ProjectVersion>
    <DockerTargetOS>Linux</DockerTargetOS>
    <ProjectGuid>615b1c67-0712-212e-1a31-c2ee9dd21b29</ProjectGuid>
    <DockerLaunchBrowser>True</DockerLaunchBrowser>
    <DockerServiceUrl>http://localhost:{ServicePort}</DockerServiceUrl>
    <DockerServiceName>app</DockerServiceName>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".dockerignore" />
    <None Include="docker-compose.ci.build.yml" />
    <None Include="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.yml" />
  </ItemGroup>
</Project>
```

Dockerfile:
```Dockerfile
FROM microsoft/aspnetcore:2.0.5 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore -nowarn:msb3202,nu1503
RUN dotnet build --no-restore -c Release -o /app

FROM build AS publish
RUN npm rebuild node-sass
RUN npm install
RUN npm run build-prod
RUN dotnet publish --no-restore -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Server.dll"]
```

docker-compose.yml
```yml
version: '3.4'

services:
  app:
    image: ${REPOSITORY-local}/app:${TAG}
    build:
      context: .
      dockerfile: src/Server/Dockerfile
```

## Expected behavior
Build without issues...

## Actual behavior
```
Building app
Step 1/20 : FROM microsoft/aspnetcore:2.0.5 AS base
2.0.5: Pulling from microsoft/aspnetcore
Digest: sha256:3dd91dfc75309d7b9b03e7ce2b5537fd0a8a51c74ba5af31f4688a600746be17
Status: Downloaded newer image for microsoft/aspnetcore:2.0.5
 ---> b1a5de255274
Step 2/20 : WORKDIR /app
Removing intermediate container f3bfe126d58b
 ---> 154d716c75c0
Step 3/20 : EXPOSE 80
 ---> Running in e48677799540
Removing intermediate container e48677799540
 ---> 0787550aa0c9

Step 4/20 : FROM microsoft/aspnetcore-build:2.0 AS build
2.0: Pulling from microsoft/aspnetcore-build
Digest: sha256:565ebb615692f07afa181bf9db4891035c14a01030f48de24d01817a93fa4b67
Status: Downloaded newer image for microsoft/aspnetcore-build:2.0
 ---> 203e3169173f
Step 5/20 : WORKDIR /src
Removing intermediate container 243ea94ec0e9
 ---> af5e1127fd08
Step 6/20 : COPY . .
 ---> 0e5985f27a11
Step 7/20 : RUN dotnet restore -nowarn:msb3202,nu1503
 ---> Running in bea2928ab246
/usr/share/dotnet/sdk/2.1.101/NuGet.targets(229,5): error MSB3202: The project file "/src/docker-compose.dcproj" was not found. [/src/Solution.sln]
```

**Comment by WolfspiritM** [comment]
I figured out what the problem seems to be.
I based my solution on the eShopOnContainer and that has excludes dcproj from being send to the docker context:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/.dockerignore

Has there been a change with handling that?

**Comment by matteobortolazzo** [comment]
Same for me, builds start to fail today with the new microsoft/aspnetcore-build image

**Comment by matteobortolazzo** [comment]
@WolfspiritM I can confirm that the problem is with the new 2.0 image. Using the "old" 2.0.5-2.1.4 image everything works.

**Comment by WolfspiritM** [comment]
@matteobortolazzo Thanks for the confirmation.
I assume your .dockerignore file also contains dcproj.
It seems like it's not ignoring the dcproj in the solution anymore as it did before for restore and if it's not there it fails.
I didn't get a chance to test if the new image works when removing docker-compose.dcproj from the .dockerignore

**Comment by WolfspiritM** [comment]
So after investigating a bit further I think the main cause is this:
https://github.com/dotnet/cli/pull/8416

That enables the load of Docker SDK Projects however it now breaks the old workaround that excluded the dcproj file.

**Comment by natemcmaster** [comment]
dotnet/cli#8416 is not in the 2.1.1xx CLI, so this is more likely a change in NuGet, Microsoft.NET.Sdk, or MSBuild itself.

https://github.com/Microsoft/msbuild/compare/v15.5.180.51428...v15.6.82.30579
https://github.com/dotnet/sdk/compare/v2.1.4...release/2.1.1xx
https://github.com/NuGet/NuGet.Client/compare/4.5.0.4685...4.6.0.4954

**Comment by WolfspiritM** [comment]
So the error appears on dotnet restore not dotnet build for me.
Also I'm building with -nowarn:msb3202 which I'm pretty sure was used to hide the warning about missing dcproj in earlier versions. It seems like the msb3202 was changed to be an error instead of a warning now which breaks this "workaround" as without it and with the old CLI I get:

```
 ---> Running in 63ad056c34ec
/usr/share/dotnet/sdk/2.1.4/NuGet.targets(227,5): warning MSB3202: The project file "/src/docker-compose.dcproj" was not found. [/src/eShopOnContainers-ServicesAndWebApps.sln]
/src/docker-compose.dcproj : warning NU1503: Skipping restore for project '/src/docker-compose.dcproj'. The project file may be invalid or missing targets required for restore. [/src/eShopOnContainers-ServicesAndWebApps.sln]
```

Removing the *.dcproj still results in:
```/src/docker-compose.dcproj : error MSB4236: The SDK 'Microsoft.Docker.Sdk' specified could not be found.```

**Comment by natemcmaster** [comment]
> /src/docker-compose.dcproj : error MSB4236: The SDK 'Microsoft.Docker.Sdk' specified could not be found

This is a known issue that should be fixed in the 2.1.300 SDK (See https://github.com/dotnet/cli/pull/8416). I recommend giving `microsoft/aspnetcore-build:2.1.300-preview1` a shot. You don't have to upgrade to netcoreapp2.1 to use it; this SDK can still build netcoreapp2.0/1.1/1.0 projects.

I'm closing at it doesn't appear there is any action item here for the aspnet docker images.

**Comment by WolfspiritM** [comment]
@natemcmaster I don't want to build production applications with preview versions and I know that the Microsoft.Docker.Sdk issue is a known issue and it's not the issue I have right now (so the title change is misleading).

The Microsoft.Docker.Sdk issue has been worked around by excluding it from the docker context altogether and setting -nowarn:msb3202,nu1503. But the new version breaks that workaround, too.

Right now there is **no** way to build Solutions that contain dcproj with the new 2.0 image as with docker-compose.dcproj added the old error reoccursed and without docker-compose.dcproj a new error happens.
See https://github.com/dotnet-architecture/eShopOnContainers/issues/543

The action item I can see here for aspnet docker images is to provide a new working one once that error is fixed in the CLI.

**Comment by natemcmaster** [comment]
> so the title change is misleading

Sorry - was trying to make the title reflect the real issue since the original title was very specific to your project. Feel free to update it to something more appropriate.

> The action item I can see here for aspnet docker images is to provide a new working one once that error is fixed in the CLI.

We can't. There is no version of the SDK we can provide in our images that has this fix. Ultimately this is dotnet/cli#6178 which is not going to be fixed until 2.1.300. The change of MSB3202 from error to warning belongs with the NuGet team: NuGet/Home#6651. Also, presumably, this bug affects those building _outside_ of the Docker container, too, so it's really an SDK bug. Internally, I've pinged the NuGet team on NuGet/Home#6651.

I realize this is frustrating, but we can't produce an SDK image that has known security issues in it (see https://github.com/aspnet/Announcements/issues/295). The SDK bundles our runtime along with MSBuild and NuGet changes. At the top of stack where we construct the docker images, we do not dissect the SDK into individual bits. If you can't use preview bits, then rolling back to `microsoft/aspnetcore:2.05-2.1.4` is the best solution for now.

**Comment by WolfspiritM** [comment]
Sorry if I might have sounded a bit harsh. That wasn't my intention 😄 

I also understand that you can not provide a fixed image for now but do I understand that correctly that you're not going to work on a fix for this error at all for 2.0?

I just wanted to make clear that this is a breaking change and not going to be declared as a "long known bug". I'll just watch the Nuget issue then.

**Comment by natemcmaster** [comment]
> I just wanted to make clear that this is a breaking change

Yeah, it broke a bunch of other people too. This has our attention and we have some threads going on the best solution for it. I think watching this issue may be better: https://github.com/Microsoft/DockerTools/issues/84. We're discussing this with the VS tooling team.

**Comment by natemcmaster** [comment]
Spent the morning meeting with people. Although ultimately this issue is external to aspnetcore, we have decided to add a workaround to aspnetcore-build images in the short term while we seek a better long-term solution for https://github.com/Microsoft/DockerTools/issues/87.

See #389.

**Comment by natemcmaster** [comment]
The workaround should be live now. Try re-pulling the image. Let me know if you have more issues.
