### ISSUE TITLE
Not able to run npm install in /app directory while creating a docker image for asp.net core 2 api application which is using node module

### ISSUE THREAD

**Issue by arupbaroi** [aspnet/aspnet-docker#391]
I need to create a windows docker image which can run on windows container for a asp.net core 2 api application. In my application I am using node js package "jsreport-wkhtmltopdf" to create pdf. But I am not able run npm install in /app directory. I have tried without npm install also. But then node_modules are not available at all and at run time I am getting "The system cannot find the file specified " exception.Can I get any help how can i make available node_modules inside /app directory.

## Steps to reproduce the issue
FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-sac2016 AS build
WORKDIR /src
COPY *.sln ./
COPY HON.SPS.SIOT.CA.REPORT.API/HON.SPS.SIOT.CA.REPORT.API.csproj HON.SPS.SIOT.CA.REPORT.API/
COPY HON.SPS.SIOT.CA.REPORT.Azure.Blob/HON.SPS.SIOT.CA.REPORT.Azure.Blob.csproj HON.SPS.SIOT.CA.REPORT.Azure.Blob/
RUN dotnet restore
COPY . .
WORKDIR /src/HON.SPS.SIOT.CA.REPORT.API
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
RUN npm install
ENTRYPOINT ["dotnet", "HON.SPS.SIOT.CA.REPORT.API.dll"]

## Expected behavior
I am able to run npm install /src directory. So expecting the same with /app directory.

## Actual behavior
npm is not availabe

**Comment by natemcmaster** [comment]
We do not provide NodeJS inside the `microsoft/aspnetcore` image, only the `microsoft/aspnetcore-build` image. You need to install NodeJS yourself, which should just mean copy-pasting this into your dockerfile.

https://github.com/aspnet/aspnet-docker/blob/5a0c97dd61e8ed4e1c8c8e7264b3f17ae87e9866/2.1/nanoserver-sac2016/amd64/sdk/Dockerfile#L7-L21

Closing as we have no plans to add NodeJS to the runtime-only image, but feel free to continue discussion if you need help resolving this.
