### ISSUE TITLE
Infinite recursion during resource lookup

### ISSUE THREAD

**Issue by pmartelletti** [aspnet/aspnet-docker#392]
We've been using the docker image for quite a long now and lately, we introduced i18n package that broke it, and can't see way. The bug is the one mentioned [here](https://github.com/dotnet/corefx/issues/24832) so we thought that we needed to update the docker image version, as that issue mentions that it was fixed in 2.0.3. However, we've changed to 2.0.6 and still we're having the same issue. Even more, we switched to `latest` tags in both aspnetcore and aspnetcore-build (so aspnetcore is on `2.0.6` and aspnetcore-build is in `2.1`) but nothing changed - as soon as we do a request to the APP that needs the i18n package, we get that error and the app terminates.

Any ideas of what could be wrong? We have some Windows Machines and publishing with for Windows seems to be working, but this linux container is not.

## Steps to reproduce the issue
Dockerfile
```
FROM microsoft/aspnetcore-build:latest AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY MembersManagement/MembersManagement/*.csproj .
RUN dotnet restore

# Copy everything else and build
COPY MembersManagement/ ./
RUN dotnet publish -c Release -r linux-x64 -o out

# build runtime image
FROM microsoft/aspnetcore:latest
WORKDIR /app
COPY --from=build-env /app/MembersManagement/out .
ENTRYPOINT ["dotnet", "Vme.MembersManagement.dll"]
```
docker-compose.yml
```
version: '3'
services:
  rest:
    build: .
    ports:
     - "5012:5012"
  eventstore:
    image: "eventstore/eventstore"
    ports:
     - "2113:2113"
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
```

## Output of `dotnet --info`

```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

## Output of `docker info`

```
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 295
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: PC4H:JBNK:DZCM:E72Z:KOCM:4INT:MUTA:FOKK:IQC6:BOU6:GRGV:3U75
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 51
 Goroutines: 79
 System Time: 2018-03-20T18:08:16.960900937Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by natemcmaster** [comment]
@pmartelletti as you mentioned, our Docker images have the latest patches in them, including the 2.0.6 runtime. If you have a minimal repro of the issue, then it's possible https://github.com/dotnet/corefx/issues/24832 was not actually fixed for all cases, but it's hard to say without seeing the C# and .csproj file you used.

**Comment by natemcmaster** [comment]
Closing as we don't have enough info to reproduce this error. If you're still having issues, feel free to add it to this and we can re-open for investigation.
