### ISSUE TITLE
Add Yarn and webpack to aspnet build images

### ISSUE THREAD

**Issue by andrewsayre** [aspnet/aspnet-docker#405]
With the recommendation to move away from bower for new development, the aspnet build images should be enhanced to contain the recommended alternatives (Yarn and webpack).  Both can be installed through npm, but the recommendation is to install Yarn through their package repository.

Sources:
- https://bower.io/blog/2017/how-to-migrate-away-from-bower/
- https://yarnpkg.com/en/docs/install
- https://webpack.js.org/guides/installation/

**Comment by Eilon** [comment]
@DamianEdwards - thoughts on including this in the Docker build images?

**Comment by natemcmaster** [comment]
We could add it to existing 2.0 and 1.x build images, but 2.1 SDK images won't have NodeJS at all in them.

**Comment by Eilon** [comment]
Hmm then I don't think it'd be worthwhile to add to older images and then not have it in the new one...

**Comment by DamianEdwards** [comment]
Yeah we have no desire to continue requiring node in our build images. We do intend to provide guidance to folks to configure and use multi-stage build however in order to use said tools when building ASP.NET Core in containers.

**Comment by andrewsayre** [comment]
Sounds good - certainly can use multi-stage build to achieve this if the long-term strategy is to eliminate node (and other non .NET build tools?) from the build images.
