### ISSUE TITLE
Allowing special characters in request url

### ISSUE THREAD

**Issue by joetherod** [aspnet/aspnet-docker#414]
In MVC 4.5, there are web.config params to allow special characters in the url request.

<httpRuntime targetFramework="4.5" maxUrlLength="1024" maxQueryStringLength="4096" requestPathInvalidCharacters="" relaxedUrlToFileSystemMapping="true" />

Currently, in MVC Core app that runs locally in Linux via Docker for Windows, fails on HTTP 400 when the url contains a accented character. This application was originally written in MVC 4 and was ported to MVC core. So, the request works in MVC 4 on Windows. Now it doesnt locally and when hosted in Linux via Docker.

eg Request: www.contoso.com/search/Paris%2C%20%C3%8Ele-de-France%20Region

Original string was encoded in javascript before sending request, "Paris, Île-de-France Region"

The request doenst even make it to the app or any middleware that I have.
And the application breaks the website, it doenst come up at all. It is like stuck once I request this url.

**Comment by natemcmaster** [comment]
This issue was moved to aspnet/Home#3094
