### ISSUE TITLE
manifest for microsoft/aspnetcore:2.1-nanoserver-1709 not found.

### ISSUE THREAD

**Issue by Mr-Vaelen** [aspnet/aspnet-docker#420]
## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1. Download [the zip from github](https://github.com/dotnet/dotnet-docker/archive/master.zip)
2. Open the solution file in Visual Studio 2017
3. Click Run -> Docker

## Expected behavior
The solution should run as expected.

## Actual behavior
I receive the error in the heading because the image for aspnetcore is not available for download

## Additional information (e.g. issue happens only occasionally)
This error occurs every time I run the app.

## Output of `dotnet --info`

```
(paste your output here)
```

## Output of `docker info`

```
FROM microsoft/aspnetcore:2.1-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.1-nanoserver-1709 AS build
WORKDIR /src
COPY *.sln ./
COPY aspnetapp/aspnetapp.csproj aspnetapp/
RUN dotnet restore
COPY . .
WORKDIR /src/aspnetapp
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```

**Comment by MichaelSimons** [comment]
@Mr-Vaelen, how did you create this Dockerfile?  The 2.1 ASP.NET Core images have migrated to the [microsoft/dotnet repo](microsoft/dotnet repo).  See this [announcement](https://github.com/aspnet/Announcements/issues/298) for details.

**Comment by Mr-Vaelen** [comment]
@MichaelSimons I got it from the link in the original post. I did not create it myself.

I will have a look at the link you put up and try that out.

**Comment by natemcmaster** [comment]
This is expected. As @MichaelSimons said, the images for 2.1 have moved. If you find that tooling such as Visual Studio is generating `microsoft/aspnetcore:2.1-nanoserver-1709` for you, let us know so we can get that tooling to use `microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709` instead.

cref: https://github.com/aspnet/aspnet-docker/blob/master/2.1/README.md

**Comment by Mr-Vaelen** [comment]
The nano server version failed completely: `microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709`
Whether it was the tooling or not, I am unsure. This is my first foray into Docker etc.

However using `microsoft/dotnet:2.1-aspnetcore-runtime` seems to work fine.
Thanks for the assistance.

**Comment by Mr-Vaelen** [comment]
Also please note that the [Visual Studio tools for Docker](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1) page also specifies: `microsoft/aspnetcore`:2.0-nanoserver-1709 AS base

I am not sure where this would go in GitHub and am hoping @MichaelSimons or @natemcmaster know where it should be placed or where I can create the appropriate issue.

**Comment by MichaelSimons** [comment]
@Mr-Vaelen - Could you provide details on 

> The nano server version failed completely: microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709

We would like to ensure this is not a product issue.  Thanks

**Comment by Mr-Vaelen** [comment]
@MichaelSimons - When I changed to `microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709`, it told me that it could not download the image as it does not exist.

When I changed it to `microsoft/dotnet:2.1-aspnetcore-runtime` it built and ran fine.

Unfortunately I can't provide overly much more detail than that.
If I have time to go back and test it I will and will then revert back to you.

**Comment by MichaelSimons** [comment]
@Mr-Vaelen - Can you include the output of running the `dotnet version` and `dotnet info` commands?  Are you able to pull and run the `microsoft/nanoserver:1709` image?
