### ISSUE TITLE
using windows container instead of linux for aspnetcore  

### ISSUE THREAD

**Issue by kharesiddharth** [aspnet/aspnet-docker#424]
Guys ,
following docker file creates a linux container. i want to instead create a windows container .
what should i change for that ? is there a different base image (FROM microsoft/aspnetcore:1.1.2) that i have to start with in dockerfile for that ?

----------------------------------------------------------------
FROM microsoft/aspnetcore:1.1.2
 
COPY dist /app

WORKDIR /app

EXPOSE 80/tcp

ENTRYPOINT ["dotnet", "exampleapp.dll"]
-------------------------------------------------------------

**Comment by natemcmaster** [comment]
> is there a different base image...?

Yes. See the list of tags in the README on this repo and Docker Hub. Also, make sure you have enabled Windows containers on your machine. See https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers.

Closing as I believe this answers your question.
