### ISSUE TITLE
windows containers and registry settings 

### ISSUE THREAD

**Issue by kharesiddharth** [aspnet/aspnet-docker#425]
All,
just like how containers have their own file system , do windows containers have their registry settings too ?
thanks

**Comment by natemcmaster** [comment]
Yes, Windows containers have their own registry settings.

By the way, https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers is a better place to discuss more details on this. I'm happy to answer questions but you may get a better response and more details from the audience in this forum.

**Comment by kharesiddharth** [comment]
thanks
