### ISSUE TITLE
what relationship between  microsoft/aspnetcore-build2.1 and .NET Framework 4.5？？

### ISSUE THREAD

**Issue by iver3on** [aspnet/aspnet-docker#426]
does microsoft/aspnetcore-build2.1 support .NET Framework 4.5's app?

**Comment by natemcmaster** [comment]
These repositories are for .NET Core only. .NET Framework images are found here: https://github.com/Microsoft/dotnet-framework-docker.

Closing as I believe this answers the question, but feel free to continue discussion.
