### ISSUE TITLE
aspnet docker does not contain aspnet in 2.1

### ISSUE THREAD

**Issue by noelmcgrath** [aspnet/aspnet-docker#430]
In 2.0 Dockerfile a csproj was created and a dotnet restore done to bring down packages
See https://github.com/aspnet/aspnet-docker/blob/master/2.0/jessie/sdk/Dockerfile

this is no longer the case with 2.1 as it is "FROM microsoft/dotnet:2.1-sdk" and does not contain any aspnet packages

## Describe the solution you'd like
Just like aspdocker 2.0 Dockerfile include this step in sdk Dockerfile
     # warmup NuGet package cache

## Describe alternatives you've considered
Alternative is to create your own Dockerfile with the step in it

## Additional context
Create your own is a solution, but surely the aspnet docker sdk should come with aspnet in it

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/dotnet-docker#636
