### ISSUE TITLE
Remove `nightly` artifacts

### ISSUE THREAD

**Issue by MichaelSimons** [aspnet/aspnet-docker#437]
I would like to suggest the removal of the `nightly` artifacts in an effort to cleanup.  The nightly images haven't been updated in 9 months now.  Given this ASP.NET Core images have been consolidated with the .NET Core images I don't see any value in keeping this around. 

1. Post a notice on https://hub.docker.com/r/microsoft/aspnetcore-nightly and https://hub.docker.com/r/microsoft/aspnetcore-build-nightly that they are going to be removed at a specified time.  They haven't been touched in 9 months now.
2. Remove the `dev` branch from this repo.
3. Delete the build definition - https://devdiv.visualstudio.com/DevDiv/_build?definitionId=6612

**Comment by natemcmaster** [comment]
cc @Eilon - this is an infrastructure cleanup task we should do. Could be done anytime.

**Comment by natemcmaster** [comment]
Done with parts 2 and 3. For part 1, I think we'll just update the README in Docker Hub to indicate the images are deprecated. Reaching out internally to figure out how to get permissions to do that.
