### ISSUE TITLE
docker-compose up errors

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/aspnet-docker#439]
docker file VisualStudio generated Dockerfile fails when used within a docker.compose.yml build 
(see below)  NOTE: the same Dockerfile work from VisualStudio and this looks to be relating to the docker base image on docker hub

> Step 8/17 : RUN dotnet restore "src/DXC.Platform.LondonMarket.ReferenceDataAPI/DXC.Platform.LondonMarket.ReferenceDataAPI.csproj"
>  ---> Running in 56db23f04679
>   Restoring packages for /src/src/DXC.Platform.LondonMarket.ReferenceDataAPI/DXC.Platform.LondonMarket.ReferenceDataAPI.csproj...
> /usr/share/dotnet/sdk/2.2.104/NuGet.targets(114,5): error : An error occurred while retrieving package metadata for 'System.Threading.Tasks.4.3.0' from source '/usr/share/dotnet/sdk/NuGetFallbackFolder'. [/src/src/DXC.Platform.LondonMarket.ReferenceDataAPI/DXC.Platform.LondonMarket.ReferenceDataAPI.csproj]
> /usr/share/dotnet/sdk/2.2.104/NuGet.targets(114,5): error :   Root element is missing. [/src/src/DXC.Platform.LondonMarket.ReferenceDataAPI/DXC.Platform.LondonMarket.ReferenceDataAPI.csproj]
> ERROR: Service 'reference-data-api' failed to build: The command '/bin/sh -c dotnet restore "src/DXC.Platform.LondonMarket.ReferenceDataAPI/DXC.Platform.LondonMarket.ReferenceDataAPI.csproj"' returned a non-zero code: 1
>

**Comment by natemcmaster** [comment]
This repo is only used for ASP.NET Core Docker images for 1.x. Please use https://github.com/dotnet/dotnet-docker for .NET Core 2+.

**Comment by MichaelSimons** [comment]
For issues related to Visual Studio Tools for docker, please log them at https://github.com/microsoft/DockerTools.
