### ISSUE TITLE
beta4 is out, somebody create an image!

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#50]
Dear contributors, `beta4` is out: https://github.com/aspnet/Home/releases/tag/beta4 and we need a docker image for it.

It contains lots of changes (e.g. new set of commands like `dnx`). Leaving this issue here for a while if somebody wants to pick that up quickly, otherwise I'll try to do this.

**Comment by jsacapdev** [comment]
I have some questions:

1. should new image be using mono 4.1.0?
2. In the repo, there seems to be a aspnet-docker/vs-1.0.0-beta4 Dockerfile - is there something else that needs to be added in the Dockerfile as part of this task?
3. should a new 1.0.0-beta4 sub folder be created in the aspnet-docker repo with the beta4 dockerfile?
4. should a request from the docker registry for microsoft/aspnet pull down the beta4 image once this task is complete?

Apologies in advance for these questions - but I have itching to get involved with the whole community effort and see this as a way of doing so. If its easier for me to get guidance outside of this issue tracker - please let me know how to progress. Thanks.

**Comment by ahmetalpbalkan** [comment]
@jsacapdev thanks for jumping in, these questions are okay!

1. I think this is still the case. But there's no 4.1.0 image for mono yet on docker hub, so we recompile (you can copy mono parts from `vs-1.0.0-beta4/Dockerfile`)
2. I think it'll be a bit different than `vs-*` image, it just uses `dev` branch. Purpose of this image is to fix things to `beta4` packages and thus get reproducible builds.
3. Yes, please create a folder for `1.0.0-beta4`, move README.md in `1.0.0-beta3` to there, add info about `beta4` to the readme, change the README.md symlink in project root from beta3 to beta4.
4. Not really, I need to go and add beta4 manually on Docker Hub once this is merged.

**Comment by vlesierse** [comment]
Got a working image with beta 4 [1.0.0-beta4](https://github.com/vlesierse/aspnet-docker/tree/1.0.0-beta4/1.0.0-beta4).

I see that the CI scripts needs to be adjusted as well because of a change in the aspnet/Home repository on the samples (exists of two folders latest and 1.0.0-beta4).

It's also installing mono 4.0.1 because there is no base image yet.

**Comment by ahmetalpbalkan** [comment]
@vlesierse that looks nice enough. feel free to send a pull request.  AFAIK we need mono **4.1.0** for beta4 to run correctly; not 4.0.1 (coz there's a 4.0.1 image on [Docker Hub](https://registry.hub.docker.com/u/library/mono/)).

I'm ignoring CI scripts for now. They're totally messed up after the dir structure change and will require more version-specific handling. If you want to step up to fix those, we appreciate a lot!

**Comment by vlesierse** [comment]
@ahmetalpbalkan Ok, clear. I'm building the image with mono 4.1.0 locally as we speak. I will send a PR when it passes my tests.

Next week I will have some time to look into fixing up the CI builds.
