### ISSUE TITLE
Attempting to run aspnet samples with vs-1.0.0-beta4 results in error

### ISSUE THREAD

**Issue by govin** [aspnet/aspnet-docker#54]
I was attempting to run aspnet HelloMvc sample with vs-1.0.0-beta4 docker image. This results in "Unable to locate Microsoft.AspNet.Server.WebListener >= 1.0.0-beta4*" error. 

Here is my docker file

```
FROM microsoft/aspnet:vs-1.0.0-beta4

COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]

EXPOSE 5005
ENTRYPOINT ["dnx", ".", "kestrel"]
```

**Comment by ahmetalpbalkan** [comment]
@northtyphoon any ideas why this might be failing?

**Comment by Eilon** [comment]
WebListener is Windows only... not sure if that's directly related. You can use Kestrel as the web server on *nix. I don't think that explains this error though.

**Comment by yanchenw** [comment]
@govin Can you try if you still got this error? 

I just tried with both 
Home / samples / 1.0.0-beta4 / HelloMvc /  
Home / samples / latest / HelloMvc /  
with your Dockerfile, I got no errors.

**Comment by vlesierse** [comment]
There was a problem in the package.json which should be fixed by now in the Home repo.

**Comment by vlesierse** [comment]
https://github.com/aspnet/Home/commit/317f9d8b6238f271a851d764855a0e316f8cac49

**Comment by govin** [comment]
works now, thanks!
