### ISSUE TITLE
Dockerfile caching

### ISSUE THREAD

**Issue by yngndrw** [aspnet/aspnet-docker#59]
It seems that none of the packages are cached between builds when using this setup. I opened this issue with the intention of investigating various caching techniques for the Docker build step.

I will base things around what I believe to be a fairly standard Dockerfile:
```
FROM microsoft/aspnet:1.0.0-beta4

ADD . /app
WORKDIR /app

RUN dnu restore

EXPOSE 5000
ENV DNX_TRACE 1
ENTRYPOINT sleep 1000 | dnx ./src/ASPNetTest kestrel
```

During the build, Docker will cache the result of each command one by one. Sadly as the "ADD . /app" line is before the restore and you will generally be rebuilding the container after making an application change, the results of the restore cannot be cached.

There standard recommendation for this seem to be to use a HTTP proxy outside of the container. I'd like to look into some options without needing to add anything to the outer environment.

So my initial thought would be to do the restore in two steps:
```
FROM microsoft/aspnet:1.0.0-beta4

RUN dnu restore

ADD . /app
WORKDIR /app

RUN dnu restore

EXPOSE 5000
ENV DNX_TRACE 1
ENTRYPOINT sleep 1000 | dnx ./src/ASPNetTest kestrel
```

Now sadly dnu restore does not allow you to request a list of packages by command line arguments, so before the first restore you would need to make a project.json file with a list of common ASP.Net 5 dependencies. This should then be cached as it will be quite constant. (Untested)

This could possibly be taken a step further and added to the microsoft/aspnet container through an ONBUILD step. My understanding of this is that the packages themselves would not be downloaded as part of the microsoft/aspnet container, but the restore step would then automatically be added to the start of the user's Dockerfile.

Any thoughts on this ?

**Comment by ahmetalpbalkan** [comment]
You can 

    COPY project.json /app/
    RUN dnu restore 
    COPY . /app/

and you won't cache miss the docker build step over and over again unless you change project.json.

**Comment by yngndrw** [comment]
Thanks Ahmet, I'll give that a try.

**Comment by yngndrw** [comment]
I ended up with the following Dockerfile:
```dockerfile
FROM microsoft/aspnet:1.0.0-beta4

# Cache NuGet packages separately from the code
COPY ./src/ASPNetTest/project.json /app/
WORKDIR /app
RUN dnu restore
CMD rm /app/project.lock.json
CMD rm /app/project.json

ADD . /app
#WORKDIR /app

RUN dnu restore

EXPOSE 5000
ENV DNX_TRACE 1
ENTRYPOINT sleep 9999999999 | dnx ./src/ASPNetTest kestrel
```

Sadly it didn't seem to work, here's the first build:
```
remote: Step 0 : FROM microsoft/aspnet:1.0.0-beta4
remote:  ---> 87f380d6a8a5
remote: Step 1 : COPY ./src/ASPNetTest/project.json /app/
remote:  ---> 14f45db0eeba
remote: Removing intermediate container c7717234df5a
remote: Step 2 : WORKDIR /app
remote:  ---> Running in e40100e347a9
remote:  ---> 09b0c56b28d5
remote: Removing intermediate container e40100e347a9
remote: Step 3 : RUN dnu restore
remote:  ---> Running in f161996a93cd
remote: Restoring packages for /app/project.json
```

Here's the second build: (I deleted a .deployment file from the root of the solution - Notice that the image ID for step 1 is different)
```
remote: Step 0 : FROM microsoft/aspnet:1.0.0-beta4
remote:  ---> 87f380d6a8a5
remote: Step 1 : COPY ./src/ASPNetTest/project.json /app/
remote:  ---> d2f1e61f403e
remote: Removing intermediate container 0b7330ffc9a1
remote: Step 2 : WORKDIR /app
remote:  ---> Running in 31dc845c0183
remote:  ---> df1301b577d0
remote: Removing intermediate container 31dc845c0183
remote: Step 3 : RUN dnu restore
remote:  ---> Running in bafc7d4eb7b8
remote: Restoring packages for /app/project.json
```

Maybe the cache doesn't work how I thought it did. I expected that as the result of the copy hadn't changed, it would re-use existing image.

**Comment by ahmetalpbalkan** [comment]
You're not supposed to run "dnu restore" twice. It just uses project.json, so you put it there, run "dnu restore", it'll download your dependencies, then you just COPY your app (no need for those rm's) and it should work without second restore.

**Comment by yngndrw** [comment]
Sorry I confused it with the idea of having a pre-set of items and needing to then restore your project's dependencies.

Just doing what you said:
```dockerfile
FROM microsoft/aspnet:1.0.0-beta4

# Cache NuGet packages separately from the code
COPY ./src/ASPNetTest/project.json ./app/
WORKDIR ./app/
RUN dnu restore

COPY . ./app/

EXPOSE 5000
ENV DNX_TRACE 1
ENTRYPOINT sleep 9999999999 | dnx ./src/ASPNetTest kestrel
```

I ended up with the following when the container tried to run:
```
remote: =====> aspnettest container output:
remote:        System.InvalidOperationException: Unable to resolve project 'ASPNetTest' from /app/src/ASPNetTest
remote:          at Microsoft.Framework.Runtime.ApplicationHostContext..ctor (IServiceProvider serviceProvider, System.S
tring projectDirectory, System.String packagesDirectory, System.String configuration, System.Runtime.Versioning.Framewor
kName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCach
eDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation) [0x00000] in <filen
ame unknown>:0
remote:          at Microsoft.Framework.Runtime.DefaultHost.Initialize (Microsoft.Framework.Runtime.DefaultHostOptions o
ptions, IServiceProvider hostServices) [0x00000] in <filename unknown>:0
remote:          at Microsoft.Framework.Runtime.DefaultHost..ctor (Microsoft.Framework.Runtime.DefaultHostOptions option
s, IServiceProvider hostServices) [0x00000] in <filename unknown>:0
remote:          at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unkno
wn>:0
remote:          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMetho
d,object,object[],System.Exception&)
remote:          at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.B
inder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
remote: =====> end aspnettest container output
```

So I thought it might be because the project.json file was ending up in the wrong way with me using the solution setup, so instead I copied both the global.json and the project.json like this:
```dockerfile
FROM microsoft/aspnet:1.0.0-beta4

# Cache NuGet packages separately from the code
COPY ./global.json ./app/
COPY ./src/ASPNetTest/project.json ./app/
WORKDIR /app
RUN dnu restore

COPY . ./app/

EXPOSE 5000
ENV DNX_TRACE 1
ENTRYPOINT sleep 9999999999 | dnx ./src/ASPNetTest kestrel
```

Sadly this resulted in the same error as before during the run stage. (Additionally, when pushing a change up after this, the restore command executed again and re-downloaded / installed the dependencies. Docker has for some reason decided that everything had changed. Could it be the way that the repository files are pushed into the image during build ? (See below) I.e. As the content of the image is changing it can only cache up-to and including the base "microsoft/aspnet:1.0.0-beta4" Docker image ?
```bash
docker build -t "$IMAGE" .
```

**Comment by ahmetalpbalkan** [comment]
@yngndrw it looks like an error like:

```
remote:        System.InvalidOperationException: Unable to resolve project 'ASPNetTest' from /app/src/ASPNetTest
remote:          at Microsoft.Framework.Runtime.ApplicationHostContext..ctor (IServiceProvider serviceProvider, System.S
```

is indicating is something wrong on your usage. Can you please try looking at 

* sample app: https://github.com/aspnet/Home/tree/dev/samples/latest/HelloWeb
* and add this Dockerfile to this project https://github.com/aspnet/aspnet-docker/blob/9fb0f020001b8640ecdcdb4ae77d95fbb4498351/.ci/build-app-image.sh#L21-L26

and run this? Based on this example, you may be able to locate your problem.

**Comment by yngndrw** [comment]
So it looks like the only real difference between that and what I was using is that my initial project had its solution at a different level, as per the current VS2015 templates.

I first tried deploying the HelloWorld sample as you mentioned to Dokku and it worked. Here was the code as deployed:
https://github.com/yngndrw/ASPNetHelloWeb/tree/v1.0

Next I added the caching into the Dockerfile and this also deployed. Here was the code as deployed:
https://github.com/yngndrw/ASPNetHelloWeb/tree/v1.1

It looks like running dnu restore on the json files when global.json is being used doesn't work. Is this a bug with dnu restore ?

I also noticed that when making another code change in order to test the caching, (I.e. project.json didn't change) Docker decided to create a new image for the project.json copy step, therefore resulting in none of the package restoration being cached. I'm thinking it might just be easier to either setup a caching web proxy or attach a volume to use as a cache. Here was the code as deployed:
https://github.com/yngndrw/ASPNetHelloWeb/tree/v1.2

v1.1 Build:
```bash
remote: Step 0 : FROM microsoft/aspnet:1.0.0-beta4
remote:  ---> 87f380d6a8a5
remote: Step 1 : COPY project.json /app/
remote:  ---> f2675baaa1e4
remote: Removing intermediate container cabb4dda1d20
remote: Step 2 : WORKDIR /app
remote:  ---> Running in 4483ad4413ac
remote:  ---> b8f3f31bb496
remote: Removing intermediate container 4483ad4413ac
remote: Step 3 : RUN dnu restore
remote:  ---> Running in 3c76dfc10fc1
remote: Restoring packages for /app/project.json
remote:   GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Kestrel'.
...
```

v1.2 Build:
```bash
remote: Step 0 : FROM microsoft/aspnet:1.0.0-beta4
remote:  ---> 87f380d6a8a5
remote: Step 1 : COPY project.json /app/
remote:  ---> bb88a1c93e7e
remote: Removing intermediate container d25b0c4336d8
remote: Step 2 : WORKDIR /app
remote:  ---> Running in 26f0de6ee09a
remote:  ---> 6aa2dc0cddb4
remote: Removing intermediate container 26f0de6ee09a
remote: Step 3 : RUN dnu restore
remote:  ---> Running in d1d2cd60d5d3
remote: Restoring packages for /app/project.json
remote:   GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Kestrel'.
...
```

**Comment by ahmetalpbalkan** [comment]
> It looks like running dnu restore on the json files when global.json is being used doesn't work. Is this a bug with dnu restore ?

This actually might be an issue. If you can open an issue on https://github.com/aspnet/dnx/issues that would be great.

**Comment by yngndrw** [comment]
I've created a bug report: https://github.com/aspnet/dnx/issues/2065

Regarding the caching issue, I'm wondering if there is an issue in Dokku which is stopping the cache from working correctly. I will have to test it when I get the chance.

**Comment by ahmetalpbalkan** [comment]
@yngndrw hmm shall we close this now?

**Comment by yngndrw** [comment]
@ahmetalpbalkan Sorry I didn't update this issue further. Last time I checked DNU did not seem to work correctly but I haven't tried it with the latest.

I did have issues with the Docker layer caching not behaving as I'd expect so changed tact and tried implementing a cache volume for DNS. Sadly then ran into an issue where I couldn't mount a host volume while building a Docker image and commented in a Docker issue regarding that: https://github.com/docker/docker/issues/14080#issuecomment-119371247

Either way these are not issues within aspnet-docker so yes this can be closed.

**Comment by kcd83** [comment]
This issue still comes up when searching about caching packages so... in short, the answer is yes! 

```
FROM microsoft/aspnet:latest

COPY src/MyProject/project.json /opt/api/project.json

WORKDIR /opt/api

RUN ["dnu","restore"]

COPY src/MyProject/ /opt/api/

EXPOSE 5000

ENTRYPOINT ["dnx","-p","project.json", "web"]
```

This works great, at least with docker 1.7 and rc1

**Comment by friism** [comment]
@kcd83 yes, that's a great approach. The problem is that it's hard to scale for repos with multiple project.json files because of limitations in the docker COPY globbing implementation
