### ISSUE TITLE
commands not found when building/running docker images based on microsoft/aspnet

### ISSUE THREAD

**Issue by chennanfei** [aspnet/aspnet-docker#60]
I followed the article http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx and tried to set up a simple site based on .NET in docker. I created my Dockerfile and made microsoft/aspnet as its base image. I got an error 'kpm: command not found' when running 'docker build'. Finally I realized the 1.0.0-beta4 has changed and I should use 'dnu restore', but no idea how I can start kestrel bcz 'k: command not found' when I ran the container

FROM microsoft/aspnet
COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]
EXPOSE 5004
CMD ["k", "kestrel"]

**Comment by chennanfei** [comment]
well, I changed CMD to 'dnx . kestrel' and got following error:

System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Kestrel 1.0.0-beta3
   Microsoft.AspNet.Diagnostics 1.0.0-beta3
   Microsoft.AspNet.Hosting 1.0.0-beta3
   Microsoft.AspNet.Server.WebListener 1.0.0-beta3
   Microsoft.AspNet.StaticFiles 1.0.0-beta3

Searched Locations:
  /{name}/project.json
  /root/.dnx/packages/{name}/{version}/{name}.nuspec
  /usr/lib/mono/4.5/{name}.dll
  /usr/lib/mono/4.5/Facades/{name}.dll

Try running 'dnu restore'.
  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by vlesierse** [comment]
Try changing the package references to beta4 as well in the project.json.

**Comment by chennanfei** [comment]
finally I got the issue fixed. thanks!
