### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by lavadiablo** [aspnet/aspnet-docker#66]
Git already provides great version control, why specific folder is created for each beta release?
It looks like a old behaviour to have branches in TFS......

**Comment by ahmetalpbalkan** [comment]
@lavadiablo  Short answer: It's not for versioning of the dockerfiles. 

We have Docker images for all the asp.net versions actively maintained. Therefore it makes sense to keep them side by side on one branch...

This a convention followed across many official docker image repositories as well. https://github.com/docker-library/

If we'd maintain them on separate branches, sending pull requests against them would be harder. Browsing and discoverability would be really difficult, too.

**Comment by lavadiablo** [comment]
@ahmetalpbalkan make sense but I guess you will not need maintain those beta versions parallel in future.

**Comment by ahmetalpbalkan** [comment]
@lavadiablo we do actively maintain all the versions listed in the github repo at this point.

For instance if there is a security bug in the mono base image that's being used, we need to update the version accordingly and rebuild all the images.

However, going forward, we probably will have at most 3-5 versions available at any time, for instance if you try using beta1 image now, that might go away a few months from now. The image on Docker Hub and its Dockerfile here would be deleted in that case.
