### ISSUE TITLE
CoreCLR beta6 docker file

### ISSUE THREAD

**Issue by jchannon** [aspnet/aspnet-docker#78]
Any chance of a dockerfile for beta6? I tried locally but it failed for 10444 for some reason.

**Comment by ahmetalpbalkan** [comment]
I think the coreclr is just not ready to be containerized yet. The coreclr image we have was submitted pretty much due to demo purposes.

**Comment by glennc** [comment]
I can take a look, but it will probably not be for beta6. Core CLR will not really be ready for anything until Beta7.

**Comment by jchannon** [comment]
Cool

**Comment by jchannon** [comment]
Closing and using #83 going forward
