### ISSUE TITLE
Upgrade the SQLite version in the image

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/aspnet-docker#85]
The default version of  `libsqlite3-dev`  that can be installed on this image on the is 3.7.13. 
EntityFramework.Sqlite [requires 3.7.15 or newer](https://github.com/aspnet/Microsoft.Data.Sqlite#requirements).

Having a working version of libsqlite3 will make the OOB experience better. See https://github.com/aspnet/EntityFramework/issues/3089

**Comment by ahmetalpbalkan** [comment]
@natemcmaster thanks for reporting. are you using latest (1.0.0-beta7)?

We are relying on `mono:4.0.1` as the base image (https://hub.docker.com/_/mono/) which uses `debian:wheezy` if we need to switch to `debian:jessie` for that we may coordinate with `mono` image owners.

What do you think?

**Comment by natemcmaster** [comment]
Yes, I'm using the latest. Yes, sqlite for jessie should work. https://packages.debian.org/jessie/libsqlite3-dev.

Upgrading mono is an entirely different beast. If you are coordinating with the `mono` image owners, also consider the EF7 works best with Mono 4.2.0 (see https://github.com/aspnet/EntityFramework/issues/2708). It appears there isn't an image for mono 4.2.0 yet (not surprising as it's [still alpha](http://www.mono-project.com/docs/about-mono/releases/4.2.0/)).

**Comment by natemcmaster** [comment]
@ahmetalpbalkan also, if we upgrade mono version, let's avoid mono 4.0.3.x. These versions have regressions in System.Data.

**Comment by ahmetalpbalkan** [comment]
@natemcmaster will keep in mind. Thanks.

If you'd like to propose `mono` folks upgrading to jessie, please open an issue at: https://github.com/mono/docker
