### ISSUE TITLE
Retire beta1..4 images

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#89]
I would like to propose retiring beta1..4 images as they're not part of CI for a while now and we probably shouldn't keep so many versions around. Thoughts?

**Comment by friism** [comment]
+1 - you can probably reach out to the docker registry guys to see if people are still actively pulling those versions.

**Comment by ahmetalpbalkan** [comment]
@friism there might be but we don't have a policy as the image is in preview and aspnet itself even breaks frequently. Normally the way to handle this, from my experience, is to have tags like `python:2` `:2.7` and `:2.7.6` so that removal of specific minor/patch images does not effect user in the long run. But since this is all pre-1.0, I guess we're still good?

**Comment by akoeplinger** [comment]
+1. The whole point about a preview is being able to make changes :smile:

**Comment by muratg** [comment]
Agreed.  Let's nuke them.  I assume the work would be removing them from Docker and deleting the folders in this repo?

**Comment by ahmetalpbalkan** [comment]
True.

**Comment by ahmetalpbalkan** [comment]
Turns out removing them from Docker Hub is not as easy as removing them from the build settings over there... They actually keep the tags around even though you take them out of automated builds and they used to have a UI to delete these tags in the old Docker Hub but they released this new Docker Hub in a hurry and it's still missing a lot of functionality –including removing tags. 

I have an open issue for this https://github.com/docker/hub-feedback/issues/368 some tags like `nightly` we removed 6 months ago are unfortunately still there.

**Comment by glennc** [comment]
That's unfortunate :). So we just leave them here until we can cleanup Dockerhub as well?

**Comment by ahmetalpbalkan** [comment]
I'm retiring these anyway, folks will be pulling down old tags until Docker Support helps us cleaning those up.
