### ISSUE TITLE
docker build fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by davidwincent** [aspnet/aspnet-docker#92]
Following the instructions at https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md does not work.

My working copy of HelloWeb is: https://github.com/aspnet/Home/tree/1d06f1f9352e6ce75f0602f19bbcb04b01dc9ccb/samples/latest/HelloWeb
My docker version is: 1.5.0, build a8a31ef
Dockerfile: https://github.com/aspnet/Home/blob/1d06f1f9352e6ce75f0602f19bbcb04b01dc9ccb/samples/latest/HelloWeb/Dockerfile
```
sudo docker build -t aspnet-home-helloweb .
```
=>
```
Sending build context to Docker daemon   320 kB
Sending build context to Docker daemon 
Step 0 : FROM microsoft/aspnet
Pulling repository microsoft/aspnet
5d7513d98c09: Error pulling image (latest) from microsoft/aspnet, HTTP code 400 
ba249489d0b6: Download complete 
19de96c112fc: Download complete 
b92a854a78d0: Download complete 
63e9265ef57c: Error pulling dependent layers 
INFO[0011] Error pulling image (latest) from microsoft/aspnet, HTTP code 400
```

**Comment by ahmetalpbalkan** [comment]
Your error does not seem related to the aspnet image but Docker Hub in general. Can you pull the base image again and other various images to see if it works.

**Comment by davidwincent** [comment]
Hi.
Other images I have tried seems to work fine. For example:
```
sudo docker pull docker
```
I also tried removing all images and pulling them again. I get the same "Error pulling image (latest) from microsoft/aspnet, HTTP code 400" when issuing this command:
```
sudo docker pull microsoft/aspnet
```

**Comment by ahmetalpbalkan** [comment]
@davidwincent Hmm interesting, I am able to pull using this command just fine on a clean docker engine.

I suggest you to look at your Docker engine logs first about these errors... Those should have more info about HTTP 400s.

As a simple mitigation, please try removing all the images and then pull. I have no idea why this is occurring, still does not seem it is about `microsoft/aspnet` to me. If this doesn't solve your problem we should open an issue at `docker/docker` repo, simply because this shouldn't be happening to any image under normal circumstances.

**Comment by davidwincent** [comment]
Hi @ahmetalpbalkan
I change to docker 1.8 instead of 1.5 and now it works better. Had to run the "sudo docker build -t aspnet-home-helloweb ." a couple of times to get rid of the request timeouts.

Now I am stuck on the following command:
```
sudo docker run -it -p 5004:5004 aspnet-home-helloweb
```
=>
```
System.InvalidOperationException: Unable to load application or execute command 'project.json'. Available commands: web, kestrel.
  at Microsoft.Dnx.ApplicationHost.Program.ThrowEntryPointNotfoundException (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.Exception innerException) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain (Microsoft.Dnx.Runtime.DefaultHost host, System.String applicationName, System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
  at Microsoft.Dnx.Host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args, IRuntimeEnvironment env, System.Runtime.Versioning.FrameworkName targetFramework) [0x00000] in <filename unknown>:0 
```
Will inform the aspnet team. Thanks.

**Comment by ahmetalpbalkan** [comment]
@davidwincent are you using the dockerfile at https://github.com/aspnet/Home/tree/dev/samples/1.0.0-beta7/HelloWeb ?

**Comment by davidwincent** [comment]
I am using: https://github.com/aspnet/Home/tree/dev/samples/latest/HelloWeb

Is it the same?

**Comment by ahmetalpbalkan** [comment]
@davidwincent turns out repo owners forgot to point `samples/latest` to actual latest release... Please use the link I provided above, in the meanwhile I opened an issue at https://github.com/aspnet/Home/issues/936 .

**Comment by davidwincent** [comment]
Thanks! Works like a charm!

If any other lost soul is to find this thread, here is how I installed docker.io 
https://docs.docker.com/installation/ubuntulinux/

(do not use apt-get install docker.io - it will give you an outdated version)
