### ISSUE TITLE
Change base image

### ISSUE THREAD

**Issue by glennc** [aspnet/aspnet-docker#97]
I am thinking more and more that we need to change the base image and install Mono ourselves.

The Ubuntu base that is being used by almost everyone to test out things like Kestrel is Jessie based. So  I think we are going to get less issues like #95 if we are at least using Jessie. Alternatively we could use Ubuntu 14.04. But I don't really know the size difference, I am hesitant to add a bunch of Ubuntu packages if they aren't really needed.

Does anyone else have any thoughts?

**Comment by ahmetalpbalkan** [comment]
Ubuntu as a base image  is mostly something people new to Docker do. Also http://mjg59.dreamwidth.org/36312.html. Correct way to go is Debian (like all other official language images).

Installing mono ourselves works for me. Except you have to follow Mono security mailing liBut let ke know once that happens, we need to update the trigger at the

**Comment by glennc** [comment]
My issue isn't really size at all, that was just an aside. It is that we don't test on Wheezy. Jessie is the Debian base for the Ubuntu version that all of the testing and support happens on. So by running on Wheezy we are on an older version of Debian then what people are testing the bits on before they release. Seems we are asking for more bugs that we can't explain by doing that.

**Comment by ahmetalpbalkan** [comment]
If the issue is wheezy vs jessie, please consider suggesting mono image to update its base. Otherwise, Debian is usually more convenient to run apps and there are reasons why most base images are not on top of ubunti. Also if we are going to install mono ourselves we definitely need to track their security group and push updates proactively as there was a massive TLS vuln in mono a few months ago and it was immediately fixed in the official Docker image. We should be on par with that.

**Comment by glennc** [comment]
That makes sense, I think I will close this and ignore it for now. It is likely mostly a problem for Core CLR anyway.

**Comment by adamschmidt** [comment]
What's the resolution for those people whose start point is microsoft/aspnet:1.0.0-beta7? Use microsoft/aspnet:1.0.0-beta7-coreclr instead while this gets fixed in beta8+?

**Comment by ahmetalpbalkan** [comment]
@adamschmidt I'm not sure I understand your question and relevance of it to the issue.

**Comment by adamschmidt** [comment]
Apologies - missed a bit of context. This thread was linked to an issue not being able to load libdl (https://github.com/aspnet/aspnet-docker/issues/95). Just wondering if moving away from the mono-based image (as all the documentation, yeoman bootstrapper, etc elude to) fixes that issue, or if it's something entirely different.

**Comment by ahmetalpbalkan** [comment]
@adamschmidt I see, let's move your question there and keep that thread going.
