### ISSUE TITLE
error in dnu restore

### ISSUE THREAD

**Issue by FDonald** [aspnet/aspnet-docker#99]
When I launch docker build command with latest version (1.0.0-beta-7) dnu restore fails with message:

*Warning: FindPackagesById: Microsoft.AspNet.Mvc
  Error: NameResolutionFailure*

*System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Exception: Couldn't resolve host name.*

However, when I execute dnu restore from command line, (1.0.0-rc1-15838) dnu restore works.

**Comment by friism** [comment]
Is networking operational from within the VM where Docker is running? Try running `boot2docker ssh` or `docker-machine ssh dev` and then run `ping bing.com`.

**Comment by FDonald** [comment]
Thank you for answer.
I can't create docker-machine on my VM Ubuntu 14.04.3 LTS. However, networking is ok.
*PING bing.com (204.79.197.200) 56(84) bytes of data.
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=1 ttl=117 time=49.4 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=2 ttl=117 time=47.7 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=3 ttl=117 time=47.6 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=4 ttl=117 time=48.2 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=5 ttl=117 time=46.7 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=6 ttl=117 time=47.7 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=7 ttl=117 time=48.5 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=8 ttl=117 time=47.6 ms
64 bytes from a-0001.a-msedge.net (204.79.197.200): icmp_seq=9 ttl=117 time=47.0 ms*

**Comment by ahmetalpbalkan** [comment]
@glennc any ideas why rc1 is showing up in beta7 image?

**Comment by glennc** [comment]
Going to need more details, I don't understand what's happening at the moment.

You are running a container from the beta7 image and it is telling you that you have rc1?

The error you are getting in is a networking one, or NuGet/MyGet being down. But I don't understand why  you see RC1 in a beta7 container.

**Comment by FDonald** [comment]
OK, let me explain this.
I can run an mvc 6 web Api in an Ubuntu with RC1 installed (method 1), but when I try to build a container from beta 7 (method 2) I got the error. I think may be an error in container. Why not a docker container with RC1?
My Ubuntu is a VirtualBox VM with a network NAT adapter.

**Comment by glennc** [comment]
So you are taking the beta7 image and then installing RC1 on it, and getting errors restoring?

Are you using Mono or Core CLR? The pre-reqs for Core CLR have definitely changed between beta7 and RC, so you would need to install the extra dependencies. Though I don't know that any of them would cause the exact error you are seeing.

We don't create docker images for versions that haven't been released yet, that's why there isn't an RC image. Originally we had an image that always pulled the latest DNX, but it was fairly unstable. As the DNX gets closer and closer to v1 we might be able to do that as the number of breaking changes should go down.

**Comment by muratg** [comment]
@FDonald We now have an RC1 based image that you can use directly. 

Please reopen or file another bug if you still have issues with that image.
